Repository pixijs/pixijs, pull requests merged in 2018-06, with the labels that each got.

#4934 Fixes Sprite's texture listener not getting removed
  src/core/sprites/Sprite.js
  test/core/Sprite.js
Labels: Difficulty: Easy, Domain: Tests, Priority: Medium, Type: Bug, Version: v4.x

#4951 Creates unit-test and improves single and multiple image font loading
  src/extras/BitmapText.js
  src/loaders/bitmapFontParser.js
  test/extras/BitmapText.js
  test/extras/resources/font-no-page.fnt
  test/loaders/bitmapFontParser.js
  test/loaders/resources/split_font2.fnt
Labels: Difficulty: Medium, Domain: API, Plugin: Text, Priority: High, Type: Bug, Version: v4.x, Version: v5.x

#4956 TextMetrics.wordWrap - Don't add a newline if it's the last token/word
  src/core/text/TextMetrics.js
Labels: Difficulty: Medium, Plugin: Text, Priority: High, Type: Bug, Version: v4.x, Version: v5.x

#4933 [next] Application plugin structure
  bundles/pixi.js/package.json
  bundles/pixi.js/src/index.js
  packages/app/README.md
  packages/app/package.json
  packages/app/src/Application.js
  packages/app/src/ResizePlugin.js
  packages/app/src/index.js
  packages/app/test/index.js
  packages/canvas/canvas-graphics/src/Graphics.js
  packages/loaders/README.md
  packages/loaders/src/LoaderPlugin.js
  packages/loaders/src/index.js
  packages/loaders/test/LoaderPlugin.js
  packages/loaders/test/index.js
  packages/mixin-app-loader/LICENSE
  packages/mixin-app-loader/README.md
  packages/mixin-app-loader/package.json
  packages/mixin-app-loader/src/index.js
  packages/mixin-app-loader/test/.eslintrc.json
  packages/mixin-app-loader/test/index.js
  packages/ticker/README.md
  packages/ticker/src/TickerPlugin.js
  packages/ticker/src/index.js
  packages/ticker/test/Ticker.js
  packages/ticker/test/TickerPlugin.js
  packages/ticker/test/index.js
Labels: Difficulty: Easy, Domain: API, Priority: Medium, Type: Enhancement, Type: Refactor, Version: v5.x

#4969 Do not quote escape generic font families
  src/core/text/TextStyle.js
  test/core/TextStyle.js
Labels: Difficulty: Easy, Domain: API, Plugin: Text, Priority: High, Type: Bug, Version: v4.x, Version: v5.x

#4979 Added links to TextStyle Editor
  src/core/text/Text.js
  src/core/text/TextStyle.js
Labels: Difficulty: Easy, Domain: Documentation, Priority: Low, Version: v4.x

#4966 Coerce null to Texture.EMPTY in Sprite.texture
  src/core/sprites/Sprite.js
Labels: Version: v4.x
