Repository pixijs/pixijs, pull requests merged in 2018-12, with the labels that each got.

#5243 Fix TilingSprite:_renderCanvas to account rotated textures from texture atlas
  src/extras/TilingSprite.js
Labels: Difficulty: Medium, Domain: API, Plugin: Tiling Sprite, Priority: Medium, Renderer: Canvas, Type: Enhancement, Version: v4.x, Version: v5.x

#5261 Fixes defaultAnchor cloning with Texture.clone
  src/core/textures/Texture.js
  test/core/Texture.js
Labels: Difficulty: Easy, Domain: API, Priority: Medium, Type: Bug, Version: v4.x, Version: v5.x

#5057 Ability to set individual display components to be drawn to rounded pixels
  packages/app/src/Application.js
  packages/canvas/canvas-mesh/src/CanvasMeshRenderer.js
  packages/canvas/canvas-mesh/src/NineSlicePlane.js
  packages/canvas/canvas-particles/src/ParticleContainer.js
  packages/canvas/canvas-renderer/src/CanvasRenderer.js
  packages/canvas/canvas-renderer/src/autoDetectRenderer.js
  packages/canvas/canvas-sprite/src/CanvasSpriteRenderer.js
  packages/core/src/AbstractRenderer.js
  packages/core/src/Renderer.js
  packages/mesh/package.json
  packages/mesh/src/Mesh.js
  packages/particles/src/ParticleContainer.js
  packages/settings/src/settings.js
  packages/sprite/src/Sprite.js
  packages/text-bitmap/src/BitmapText.js
  tools/renders/src/Renderer.js
Labels: Domain: API, Type: Enhancement, Version: v5.x

#5257 Problem with destroying active framebuffer
  src/core/renderers/webgl/TextureManager.js
Labels: Priority: Critical, Type: Bug

#5245 Fix Graphics _localBounds calculation
  src/core/graphics/Graphics.js
Labels: Difficulty: Medium, Plugin: Graphics, Type: Bug, Version: v4.x, Version: v5.x

#5264 re enabled graphics batching for next
  packages/graphics/src/GraphicsGeometry.js
Labels: Difficulty: Easy, Priority: High

#5262 Fixes old examples for BaseRenderTexture & RenderTexture
  src/core/textures/BaseRenderTexture.js
  src/core/textures/RenderTexture.js
Labels: Difficulty: Easy, Domain: Documentation, Version: v4.x

#5220 Bugfix/geometry cache fix
  packages/core/src/batch/BatchRenderer.js
  packages/core/src/batch/BatchSystem.js
  packages/core/src/geometry/GeometrySystem.js
Labels: Difficulty: Medium, Type: Bug, Version: v5.x

#5276 [next] Properly deprecate roundPixels Renderer option
  packages/core/src/AbstractRenderer.js
  packages/utils/src/logging/deprecation.js
Labels: Difficulty: Easy, Domain: API, Priority: Medium, Type: Enhancement, Version: v5.x

#5294 Bugfix/gl lines batched
  packages/core/src/batch/BatchRenderer.js
  packages/graphics/src/GraphicsGeometry.js
Labels: Difficulty: Easy, Type: Bug

#5305 Adds missing to clone prop for alignment
  src/core/graphics/GraphicsData.js
Labels: Difficulty: Easy, Type: Bug, Version: v4.x
