Repository pixijs/pixijs, pull requests merged in 2018-11, with the labels that each got.

#5202 Mask graphics holes in CanvasRenderer
  src/core/graphics/canvas/CanvasGraphicsRenderer.js
  src/core/renderers/canvas/utils/CanvasMaskManager.js
Labels: Difficulty: Medium, Priority: High, Renderer: Canvas, Type: Bug, Version: v4.x

#5120 LOD Bias support for BaseTexture (fixes #2277)
  src/core/settings.js
  src/core/sprites/webgl/generateMultiTextureShader.js
Labels: Renderer: WebGL, Version: v4.x

#5211 Revert "LOD Bias support for BaseTexture (fixes #2277)"
  src/core/settings.js
  src/core/sprites/webgl/generateMultiTextureShader.js
Labels: Difficulty: Medium, Priority: Critical, Type: Bug, Version: v4.x

#5214 [Next] jsdoc fixes for settings
  packages/canvas/canvas-mesh/src/settings.js
  packages/core/src/settings.js
  packages/settings/src/settings.js
  packages/ticker/src/settings.js
  packages/utils/src/settings.js
Labels: Domain: Documentation, Version: v5.x

#5204 [Next] zIndex support take 2
  packages/display/package.json
  packages/display/src/Container.js
  packages/display/src/DisplayObject.js
  packages/display/src/index.js
  packages/display/src/settings.js
  packages/display/test/Container.js
Labels: Domain: API, Version: v5.x

#5217 Bug fix - tint / alpha was broken for non batched graphics objects
  packages/graphics/src/Graphics.js
Labels: Difficulty: Easy, Priority: Critical, Version: v5.x

#5218 UV precision bug
  src/core/textures/TextureUvs.js
Labels: Priority: Critical, Renderer: WebGL, Type: Bug, Version: v4.x

#5225 UpdateTexture should not switch FrameBuffer
  src/core/renderers/webgl/TextureManager.js
  src/core/renderers/webgl/utils/RenderTarget.js
Labels: Difficulty: Medium, Priority: Medium, Renderer: WebGL, Type: Bug, Version: v4.x

#5230 Transform rotation cache
  src/core/display/TransformStatic.js
Labels: Difficulty: Easy, Plugin: Transforms, Type: Enhancement, Version: v4.x, Version: v5.x
