Repository pixijs/pixijs, pull requests merged in 2018-04, with the labels that each got.

#4768 Add/reorganize contributor documentation
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: Difficulty: Easy, Domain: Documentation, Priority: Low, Type: Enhancement, Version: v4.x

#4820 Adds Application property resizeTo, renames autoResize to autoDensity
  bundles/pixi.js/src/deprecated.js
  packages/app/src/Application.js
  packages/app/test/index.js
  packages/canvas/canvas-renderer/src/CanvasRenderer.js
  packages/canvas/canvas-renderer/src/autoDetectRenderer.js
  packages/core/src/AbstractRenderer.js
  packages/core/src/Renderer.js
Labels: Difficulty: Easy, Domain: API, Priority: Low, Type: Enhancement, Version: v5.x

#4828 [next] Documentation For New Systems in v5
  packages/core/src/Renderer.js
  packages/core/src/System.js
  packages/core/src/batch/BatchSystem.js
  packages/core/src/context/ContextSystem.js
  packages/core/src/filters/Filter.js
  packages/core/src/filters/FilterSystem.js
  packages/core/src/filters/spriteMask/SpriteMaskFilter.js
  packages/core/src/framebuffer/FramebufferSystem.js
  packages/core/src/geometry/Geometry.js
  packages/core/src/geometry/GeometrySystem.js
  packages/core/src/mask/MaskSystem.js
  packages/core/src/mask/StencilSystem.js
  packages/core/src/projection/ProjectionSystem.js
  packages/core/src/renderTexture/RenderTextureSystem.js
  packages/core/src/state/StateSystem.js
  packages/core/src/textures/TextureGCSystem.js
  packages/core/src/textures/TextureSystem.js
Labels: Difficulty: Easy, Domain: Documentation, Priority: Medium, Type: Enhancement, Version: v5.x

#4832 Next from methods
  packages/app/src/Application.js
  packages/core/src/renderTexture/BaseRenderTexture.js
  packages/core/src/renderTexture/RenderTexture.js
  packages/core/src/textures/Texture.js
  packages/mesh/src/NineSlicePlane.js
  packages/mesh/src/Plane.js
  packages/mesh/src/Rope.js
  packages/particles/src/ParticleContainer.js
  packages/prepare/src/BasePrepare.js
  packages/sprite-animated/src/AnimatedSprite.js
  packages/sprite-tiling/src/TilingSprite.js
  packages/sprite/src/Sprite.js
  packages/spritesheet/test/Spritesheet.js
  packages/text-bitmap/test/BitmapFontLoader.js
Labels: Difficulty: Easy, Domain: Documentation, Domain: Tests, Priority: Medium, Version: v5.x

#4794 Fixes for TextMetrics WordWrap newline issue
  src/core/text/TextMetrics.js
  src/core/text/TextStyle.js
  test/core/TextMetrics.js
Labels: Difficulty: Medium, Plugin: Text, Priority: High, Type: Bug, Version: v4.x, Version: v5.x

#4858 backport filter pool key
  src/core/renderers/webgl/managers/FilterManager.js
  src/core/renderers/webgl/utils/RenderTarget.js
Labels: Priority: Medium, X-files

#4872 Fix pointertap emission when sliding held mouse to a second object
  src/interaction/InteractionManager.js
  test/interaction/InteractionManager.js
Labels: Difficulty: Medium, Plugin: Interaction Manager, Priority: High, Type: Bug, Version: v4.x, Version: v5.x
