Repository pixijs/pixijs, pull requests merged in 2018-08, with the labels that each got.

#5061 Docs to show correct default settings on plane constructor
  src/mesh/Plane.js
Labels: Domain: Documentation, Version: v4.x

#5054 Renderers' render transform param should be a Matrix, not Transform
  src/core/renderers/canvas/CanvasRenderer.js
  src/core/renderers/webgl/WebGLRenderer.js
Labels: Difficulty: Easy, Domain: Documentation, Priority: Medium, Type: Bug, Version: v4.x, Version: v5.x

#5010 Fixes #5006 for the arc method by not adding an additional point if i…
  src/core/graphics/Graphics.js
Labels: Difficulty: Medium, Plugin: Graphics, Priority: Medium, Type: Bug, Version: v4.x, Version: v5.x

#5073 [docs] Add missing period to pivot docs.
  src/core/display/DisplayObject.js
  src/core/display/Transform.js
  src/core/display/TransformStatic.js
Labels: Difficulty: Easy, Domain: Documentation, Priority: Low, Version: v4.x, Version: v5.x

#5076 Add missing GraphicsData default param.
  bundles/pixi.js/pixi.js.d.ts
  packages/graphics/src/GraphicsData.js
Labels: Domain: Types, Type: Bug, Version: v5.x

#5077 fix Video type wrongly set
  src/core/textures/VideoBaseTexture.js
  test/core/VideoBaseTexture.js
  test/core/index.js
Labels: Difficulty: Easy, Domain: API, Priority: Medium, Type: Bug, Version: v4.x

#5045 Fixes trimming a Text object with an empty string (#5039)
  src/core/text/Text.js
  src/core/utils/trimCanvas.js
  test/core/Text.js
Labels: Difficulty: Easy, Plugin: Text, Priority: Medium, Type: Bug, Version: v4.x, Version: v5.x

#5059 Setting text to be "" means it is actually "", and not transformed to " "
  packages/text-bitmap/src/BitmapText.js
  packages/text/src/Text.js
  packages/text/test/Text.js
Labels: Plugin: Text, Version: v5.x

#5060 Able to set resolution of text separately to the renderer
  packages/text/package.json
  packages/text/src/Text.js
  packages/text/test/Text.js
Labels: Domain: API, Plugin: Text, Version: v5.x

#5049 Next speedup
  .gitignore
  packages/core/src/geometry/GeometrySystem.js
  packages/core/src/textures/TextureSystem.js
Labels: Difficulty: Easy, Domain: Performance, Version: v5.x

#5083 Removes unnecessary `new` usage for `fromUrl`
  test/core/VideoBaseTexture.js
Labels: Difficulty: Easy, Domain: API, Priority: Medium, Version: v4.x

#5093 Fixes ObservablePoint compatibility with Point
  src/core/math/ObservablePoint.js
Labels: Difficulty: Easy, Domain: API, Priority: Low, Type: Bug, Version: v4.x, Version: v5.x

#5095 Fixes typos in documentation
  README.md
  src/core/renderers/webgl/WebGLRenderer.js
  src/core/renderers/webgl/filters/Filter.js
  src/core/renderers/webgl/managers/FilterManager.js
  src/core/renderers/webgl/managers/StencilManager.js
  src/core/renderers/webgl/utils/RenderTarget.js
Labels: Difficulty: Easy, Domain: Documentation, Priority: Low, Type: Bug, Version: v4.x, Version: v5.x

#5084 prevent gaps in duplicate lineTo calls
  src/core/graphics/Graphics.js
  test/core/Graphics.js
Labels: Difficulty: Easy, Domain: API, Plugin: Graphics, Priority: Medium, Type: Bug, Version: v4.x, Version: v5.x

#5030 Fixes generation of textures on the canvas renderer when it has no parent
  src/core/renderers/SystemRenderer.js
Labels: Renderer: Canvas, Version: v4.x

#5033 check if tint & fillColor are changed
  src/core/graphics/Graphics.js
Labels: Difficulty: Easy, Domain: Performance, Plugin: Graphics, Priority: Low, Type: Enhancement, Version: v4.x
