Repository pixijs/pixijs, pull requests merged in 2018-09, with the labels that each got.

#5122 Fix cache as bitmap filters check
  src/extras/cacheAsBitmap.js
Labels: Plugin: Filters, Plugin: cacheAsBitmap, Version: v4.x

#5126 Deprecation util function
  bundles/pixi.js/src/deprecated.js
  packages/utils/src/index.js
  packages/utils/src/logging/deprecation.js
  packages/utils/src/logging/index.js
Labels: Version: v5.x

#5128 Extra constructor property to control video autoPlay
  src/core/textures/Texture.js
  src/core/textures/VideoBaseTexture.js
Labels: Domain: API, Version: v4.x

#5108 Fix the exception if an unused uniform is defined.
  src/core/renderers/webgl/managers/FilterManager.js
Labels: Plugin: Filters, Version: v4.x
