Repository pixijs/pixijs, pull requests merged in 2018-03, with the labels that each got.

#4728 [next] blendFuncSeparate fix
  packages/core/src/state/StateSystem.js
  packages/core/src/state/utils/mapWebGLBlendModesToPixi.js
Labels: Difficulty: Easy, Priority: High, Type: Bug, Version: v5.x

#4729 [next] image bitmap bug
  packages/core/src/textures/resources/ImageResource.js
Labels: Difficulty: Hard, Priority: High, Type: Bug, Version: v5.x

#4721 [next] Mesh and Texture fixes
  packages/canvas/canvas-mesh/src/NineSlicePlane.js
  packages/core/src/renderTexture/RenderTexture.js
  packages/core/src/textures/RenderTexture.js
  packages/core/src/textures/Texture.js
  packages/core/src/textures/TextureMatrix.js
  packages/mesh/src/Mesh.js
  packages/mesh/src/MeshRenderer.js
  packages/mesh/src/NineSlicePlane.js
  packages/mesh/src/Plane.js
  packages/mesh/src/Rope.js
  packages/mesh/src/mesh.vert
  packages/particles/src/ParticleContainer.js
  packages/sprite-tiling/src/TilingSprite.js
  packages/sprite-tiling/src/TilingSpriteRenderer.js
  packages/sprite/src/Sprite.js
Labels: Difficulty: Hard, Plugin: Mesh, Type: Bug, Type: Enhancement, Version: v5.x

#4737 Hotfix for rollup-plugin-commonjs
  package.json
Labels: Difficulty: Easy, Domain: Tooling, Priority: Critical, Type: Bug, Version: v5.x

#4730 Add unit tests for Application.ticker setter
  src/core/Application.js
  test/core/Application.js
Labels: Difficulty: Easy, Domain: Tests, Priority: Low, Type: Enhancement, Version: v4.x

#4724 Polyfill interactionData buttons property via event.which for Safari browser
  src/interaction/InteractionData.js
  src/interaction/InteractionEvent.js
  src/interaction/InteractionManager.js
Labels: Difficulty: Easy, Domain: API, Plugin: Interaction Manager, Type: Browser Bug, Version: v4.x

#4743 Fixes the default filter resolution to use the proper PIXI.setting
  src/core/renderers/webgl/filters/Filter.js
Labels: Difficulty: Easy, Domain: API, Plugin: Filters, Priority: Low, Type: Bug, Version: v4.x, Version: v5.x

#4545 TextMetrics.wordWrap() ignores TextStyle.letterSpacing Issue #4544
  src/core/text/TextMetrics.js
  test/core/TextMetrics.js
  test/core/index.js
Labels: Difficulty: Easy, Domain: API, Plugin: Text, Priority: Low, Type: Bug, Version: v4.x, Version: v5.x

#4722 [next] Filter fullScreen mode
  packages/core/src/filters/FilterSystem.js
  packages/core/src/renderTexture/RenderTexture.js
  packages/math/src/shapes/Rectangle.js
Labels: Difficulty: Medium, Plugin: Filters, Type: Bug, Type: Enhancement, Version: v5.x

#4758 Fix typo in PIXI.WRAP_MODES docs
  src/core/const.js
Labels: Difficulty: Easy, Domain: Documentation, Type: Bug, Version: v4.x, Version: v5.x

#4680 particle container multiple renderers possible fix
  src/particles/ParticleContainer.js
  src/particles/webgl/ParticleBuffer.js
  src/particles/webgl/ParticleRenderer.js
Labels: Plugin: Particles, Priority: Low, Type: Bug, Version: v4.x

#4749 Adds package-lock.json, upgrades Travis to Node.js v8
  .travis.yml
  package-lock.json
Labels: Difficulty: Easy, Domain: Tooling, Priority: Medium, Type: Enhancement, Version: v5.x

#4760 [next] Adds TypeScript typings to bundles
  bundles/pixi.js-legacy/package.json
  bundles/pixi.js-legacy/pixi.js-legacy.d.ts
  bundles/pixi.js/package.json
  bundles/pixi.js/pixi.js.d.ts
Labels: Difficulty: Medium

#4763 [next] Disables release build
  .travis.yml
  packages/graphics/src/GraphicsRenderer.js
Labels: Difficulty: Easy, Domain: Tooling, Priority: Critical, Version: v5.x

#4764 [next] Typings CanvasRenderer issue
  bundles/pixi.js/pixi.js.d.ts
Labels: Domain: Types, Priority: Critical, Version: v5.x

#4767 [next] Fixes missing dist files from bundles
  bundles/pixi.js-legacy/package.json
  bundles/pixi.js/package.json
Labels: Difficulty: Easy, Priority: High, Type: Bug, Version: v5.x

#4738 Repeating deprecation warnings #4443
  src/deprecation.js
Labels: Difficulty: Easy, Domain: API, Priority: Low, Type: Enhancement, Version: v4.x

#4779 Adds Number.isInteger polyfill
  src/polyfill/Number.isInteger.js
  src/polyfill/index.js
Labels: Difficulty: Easy, Domain: API, Priority: High, Type: Browser Bug, Version: v4.x, Version: v5.x

#4775 Clean up of sprite helper functions
  bundles/pixi.js/src/deprecated.js
  packages/core/src/textures/Texture.js
  packages/sprite/src/Sprite.js
Labels: Difficulty: Easy, Domain: API, Priority: Medium, Type: Refactor, Version: v5.x
