Repository pixijs/pixijs, pull requests merged in 2018-05, with the labels that each got.

#4875 Adds Patreon support link
  bundles/pixi.js/package.json
  bundles/pixi.js/scripts/support-pixi.js
Labels: Difficulty: Easy, Priority: High, Type: Enhancement, Version: v5.x

#4880 fix data_uri regex to allow charset=utf8;base64 for the encoding part…
  src/core/const.js
  src/core/utils/index.js
  test/core/util.js
Labels: Difficulty: Medium, Domain: Tooling, Priority: Medium, Type: Enhancement, Version: v4.x, Version: v5.x

#4886 Added Line alignment property to lineStyle
  src/core/graphics/Graphics.js
  src/core/graphics/GraphicsData.js
  src/core/graphics/webgl/utils/buildCircle.js
  src/core/graphics/webgl/utils/buildLine.js
Labels: Difficulty: Easy, Plugin: Graphics, Renderer: WebGL, Version: v4.x, Version: v5.x

#4837 Feature/geometry signature
  packages/core/src/geometry/GeometrySystem.js
  packages/core/src/shader/ShaderSystem.js
Labels: Version: v5.x

#4838 Set bound texture size on context change
  packages/core/src/textures/TextureSystem.js
Labels: Version: v5.x

#4853 Cumulative typings update
  bundles/pixi.js/pixi.js.d.ts
Labels: Domain: Types

#4909 Move pointertap after pointerup for clicks.
  src/interaction/InteractionManager.js
Labels: Difficulty: Medium, Domain: API, Plugin: Interaction Manager, Priority: High, Type: Bug, Version: v4.x, Version: v5.x

#4922 Allow passing DisplayObject destroy options from PIXI.Application
  src/core/Application.js
  src/loaders/index.js
  test/core/Application.js
Labels: Difficulty: Easy, Domain: API, Priority: Medium, Type: Enhancement, Version: v4.x, Version: v5.x

#4926 Fix fromBuffer arguments types
  bundles/pixi.js/pixi.js.d.ts
Labels: Difficulty: Easy, Domain: Types, Priority: Medium, Type: Bug, Version: v5.x

#4550 Add ability to customize strings '|MÃ‰q' and 'M' in TextMetrics.measureFont()
  src/core/text/TextMetrics.js
Labels: Difficulty: Easy, Domain: API, Plugin: Text, Priority: Low, Type: Enhancement, Version: v4.x, Version: v5.x

#4641 Support for multiple textures for single bitmap font.
  src/extras/BitmapText.js
  src/loaders/bitmapFontParser.js
  test/loaders/bitmapFontParser.js
  test/loaders/resources/split_font.fnt
  test/loaders/resources/split_font_ab.png
  test/loaders/resources/split_font_cd.png
Labels: Difficulty: Medium, Domain: API, Plugin: Text, Priority: Low, Type: Enhancement, Version: v4.x, Version: v5.x

#4658 Graphics: adaptive calculation of quadratic curve and arc subdivision
  src/core/graphics/Graphics.js
  src/core/graphics/utils/bezierCurveTo.js
Labels: Difficulty: Medium, Domain: API, Plugin: Graphics, Priority: Low, Type: Enhancement, Version: v4.x

#4435 Accessibility Updates: Shift-Tab, div order, and button names
  src/accessibility/AccessibilityManager.js
Labels: Difficulty: Hard, Domain: API, Priority: Medium, Type: Enhancement, Version: v4.x

#4752 Add tests for TilingSprite.getLocalBounds
  src/extras/TilingSprite.js
  test/core/TilingSprite.js
Labels: Domain: Tests, Priority: Low, Type: Enhancement, Version: v4.x

#4748 Add tests for WebGLRenderer
  test/core/WebGLRenderer.js
  test/withGL.js
Labels: Domain: Tests, Priority: Low, Type: Enhancement, Version: v4.x

#4744 Add unit tests for AnimatedSprite
  test/core/AnimatedSprite.js
  test/core/index.js
Labels: Difficulty: Easy, Domain: Tests, Plugin: AnimatedSprite, Priority: Low, Type: Enhancement, Version: v4.x

#4642 Char spacing
  src/extras/BitmapText.js
  test/extras/BitmapText.js
  test/extras/index.js
  test/extras/resources/font.fnt
  test/extras/resources/font.png
  test/index.js
Labels: Difficulty: Medium, Domain: API, Plugin: Text, Type: Enhancement, Version: v4.x

#4932 [next] Fixes Multi-Texture BitmapText Fonts
  packages/text-bitmap/src/BitmapFontLoader.js
  packages/text-bitmap/test/BitmapFontLoader.js
  packages/text-bitmap/test/resources/font1.fnt
Labels: Difficulty: Medium, Domain: Tooling, Plugin: Loader, Plugin: Text, Priority: Critical, Type: Bug, Version: v5.x
