Repository pixijs/pixijs, pull requests merged in 2019-08, with the labels that each got.

#5947 Fixes text shadows for v5, take 2
  packages/text/src/Text.js
Labels: Plugin: Text, Version: v5.x

#5958 The RenderTexturePool should create renderTextures at resolution of 1
  packages/core/src/renderTexture/RenderTexturePool.js
Labels: Renderer: WebGL, Version: v5.x

#5981 Fix lineStyle+fillStyle drawCalls count
  packages/graphics/src/GraphicsGeometry.js
Labels: Plugin: Graphics, Priority: Critical

#5959 Removed the ceil'ing of width and height in base texture
  packages/core/src/textures/BaseTexture.js
Labels: Version: v5.x, X-files

#5946 RenderTexturePool and FilterSystem changes
  packages/core/src/filters/FilterSystem.js
  packages/core/src/renderTexture/RenderTexture.js
  packages/core/src/renderTexture/RenderTexturePool.js
  packages/core/src/textures/Texture.js
Labels: Plugin: Filters

#5986 Texture resolution type missing
  packages/core/src/textures/Texture.js
  packages/graphics/src/GraphicsGeometry.js
Labels: Domain: Types

#6019 Fixed the name of the util function
  packages/utils/src/data/pow2.js
Labels: Domain: Documentation, Domain: Types

#6018 Bump floss and electron
  package-lock.json
  package.json
  scripts/renders/main.js
Labels: Version: v4.x

#5983 v4.x nested masks + filter
  src/core/renderers/webgl/managers/StencilManager.js
Labels: Version: v4.x

#6035 Fixes the error event for BaseTexture resources
  packages/core/src/textures/BaseTexture.js
  packages/core/src/textures/resources/ImageResource.js
  packages/core/src/textures/resources/Resource.js
  packages/core/src/textures/resources/SVGResource.js
  packages/core/src/textures/resources/VideoResource.js
  packages/core/test/BaseTexture.js
Labels: Difficulty: Easy, Domain: API, Type: Bug

#5989 InteractionManager: dispatch 'mouse/pointer-over' after 'mouse/pointer-out'
  packages/interaction/src/InteractionManager.js
  packages/interaction/test/InteractionManager.js
Labels: Plugin: Interaction Manager, Type: Bug, Version: v5.x

#5964 Support for lineStyle and lineTextureStyle options
  packages/graphics/src/Graphics.js
  packages/graphics/test/index.js
Labels: Plugin: Graphics

#6034 Adds a strict mode for using texture caches
  packages/core/src/settings.js
  packages/core/src/textures/BaseTexture.js
  packages/core/src/textures/Texture.js
  packages/core/test/BaseTexture.js
  packages/core/test/Texture.js
Labels: Difficulty: Easy, Domain: API

#6043 InteractionManager: fix event.stopPropagation()
  packages/interaction/src/InteractionEvent.js
  packages/interaction/src/InteractionManager.js
  packages/interaction/test/InteractionManager.js
Labels: Plugin: Interaction Manager, Priority: Critical
