Repository pixijs/pixijs, pull requests merged in 2019-02, with the labels that each got.

#5396 Renamed LoaderPlugin to AppLoaderPlugin
  packages/loaders/README.md
Labels: Difficulty: Easy, Domain: Documentation

#5401 Fix non-batched graphics.
  packages/graphics/src/GraphicsGeometry.js
Labels: Priority: Critical, Type: Bug, Version: v5.x

#5405 MultiRenderer async problem
  packages/core/src/textures/resources/ImageResource.js
Labels: Priority: Critical, Type: Bug, Version: v5.x

#5424 Renderer docs
  packages/core/src/Renderer.js
Labels: Domain: Documentation

#5425 Rename `renderTexture` field to `current`, like in FramebufferSystem
  packages/core/src/filters/FilterSystem.js
  packages/core/src/renderTexture/RenderTextureSystem.js
Labels: Domain: API

#5423 [v4] cacheAsBitmap fix calculateBounds problem
  src/extras/cacheAsBitmap.js
Labels: Plugin: cacheAsBitmap, Priority: High, Type: Bug, Version: v4.x, Version: v5.x

#5432 RenderTextureSystem invalidation problem
  packages/core/src/framebuffer/FramebufferSystem.js
  packages/core/src/renderTexture/RenderTextureSystem.js
Labels: Type: Bug, Version: v5.x

#5436 v4.x - SpriteMaskFilter clear param
  src/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter.js
Labels: Plugin: Filters, Type: Bug, Version: v4.x

#5435 SpriteMaskFilter clear param
  packages/core/src/filters/spriteMask/SpriteMaskFilter.js
Labels: Plugin: Filters, Type: Bug, Version: v5.x

#5443 [v4.x] Adaptive curves fix
  src/core/graphics/Graphics.js
Labels: Priority: Low, Type: Bug, Version: v4.x

#5442 Adaptive curve formulas fix
  packages/graphics/src/const.js
  packages/graphics/src/utils/QuadraticUtils.js
  packages/graphics/test/index.js
Labels: Priority: Critical, Type: Bug, Version: v5.x

#5444 SpriteMask filterArea 1-frame lag
  packages/core/src/mask/MaskSystem.js
Labels: Type: Bug

#5445 [v4.x] mask filterArea 1-frame lag
  src/core/renderers/webgl/managers/MaskManager.js
Labels: Type: Bug

#5430 V4.x reset textures
  src/core/renderers/webgl/WebGLRenderer.js
Labels: Type: Bug, Version: v4.x

#5450 Fix typings
  packages/core/src/textures/resources/VideoResource.js
  packages/text/src/TextMetrics.js
  packages/ticker/src/Ticker.js
  packages/ticker/src/TickerListener.js
Labels: Difficulty: Easy, Domain: Documentation, Domain: Tooling

#5452 Spritesheet definition
  types/loader.d.ts
Labels: Domain: Types, Version: v5.x

#5453 Detect close stroke shapes
  packages/graphics/src/utils/buildLine.js
Labels: Plugin: Graphics, Type: Bug, Version: v5.x

#5451 Update hard coded vertSize's in BatchRenderer.js
  packages/core/src/batch/BatchRenderer.js
Labels: Type: Refactor, Version: v5.x

#5431 Make `reset` work like in v4.
  packages/core/src/framebuffer/FramebufferSystem.js
  packages/core/src/renderTexture/RenderTextureSystem.js
  packages/core/src/shader/ShaderSystem.js
  packages/core/src/state/StateSystem.js
  packages/core/src/textures/TextureSystem.js
Labels: Type: Bug, Type: Refactor, Version: v5.x

#5422 Mipmap pow2 compatibility
  packages/constants/src/index.js
  packages/core/src/textures/BaseTexture.js
  packages/core/src/textures/TextureSystem.js
  packages/settings/src/settings.js
Labels: Renderer: WebGL, Type: Feature Request, Version: v5.x

#5395 Fixes depthTexture to work properly
  packages/core/src/framebuffer/Framebuffer.js
  packages/core/src/framebuffer/FramebufferSystem.js
  packages/core/src/textures/resources/DepthResource.js
Labels: Type: Enhancement, Version: v5.x

#5456 Unused dependency. Canvas-renderer goes into all es builds
  packages/sprite/package.json
Labels: Type: Bug, Version: v5.x

#5473 Updates to EventEmitter3 latest release
  packages/core/package.json
  packages/core/test/ArrayResource.js
  packages/display/package.json
  packages/interaction/package.json
  packages/loaders/package.json
  packages/utils/package.json
  types/events.d.ts
Labels: Difficulty: Easy, Domain: API, Domain: Types, Priority: Low, Type: Feature Request, Version: v5.x

#5480 Moved resolution check to when a texture is created
  packages/core/src/textures/Texture.js
Labels: Difficulty: Easy, Version: v5.x

#5472 Adds Containers events for addedTo and removedFrom
  packages/display/src/Container.js
  packages/display/test/Container.js
Labels: Difficulty: Easy, Domain: API, Priority: Low, Type: Feature Request, Version: v5.x
