Repository pixijs/pixijs, pull requests merged in 2019-05, with the labels that each got.

#5633 Texture destroy throws a deprecation warning
  packages/core/src/textures/Texture.js
Labels: Priority: High, Type: Bug, Version: v5.x

#5635 Adds name to root package.json so Lerna lifecycle hooks are used
  package.json
Labels: Domain: Tooling, Priority: High, Type: Bug, Version: v5.x

#5631 Temporary disable createImageBitmap in resources
  packages/core/src/textures/resources/ImageResource.js
  packages/core/src/textures/resources/autoDetectResource.js
  packages/core/test/ImageResource.js
  packages/settings/src/settings.js
Labels: Priority: High, Version: v5.x

#5637 Minor doc fixes for TypeScript definitions
  packages/loaders/src/Loader.js
  packages/sprite/src/Sprite.js
  packages/text/src/TextMetrics.js
Labels: Domain: Types

#5648 beginTextureFill texture region height
  packages/graphics/src/GraphicsGeometry.js
Labels: Plugin: Graphics, Type: Bug

#5643 trigger resize on update if needed
  bundles/pixi.js/src/useDeprecated.js
  packages/core/src/textures/BaseTexture.js
  packages/core/src/textures/Texture.js
  packages/core/src/textures/resources/BaseImageResource.js
  packages/core/test/CanvasResource.js
  packages/core/test/Texture.js
Labels: Priority: High, Version: v5.x

#5660 Fixes video not working in 5.0.1
  packages/core/src/textures/resources/BaseImageResource.js
Labels: Priority: High, Type: Bug, Version: v5.x

#5684 Fix baseTexture loaded event
  packages/core/src/textures/Texture.js
Labels: Plugin: Texture Resource, Priority: High

#5729 RenderTexture hint
  packages/core/src/renderTexture/RenderTexture.js
Labels: Domain: Documentation

#5732 finally actually added the polygon offset check :)
  packages/core/src/state/StateSystem.js
Labels: Difficulty: Easy

#5740 [V4.x] Blendmode ADD again
  src/core/renderers/webgl/utils/mapWebGLBlendModesToPixi.js
Labels: Type: Bug, Version: v4.x

#5733 Fixes regression on CanvasRenderer using tint with Sprite, AnimatedSprite and TilingSprite, BitmapText
  packages/canvas/canvas-sprite-tiling/src/TilingSprite.js
  packages/canvas/canvas-sprite/src/CanvasSpriteRenderer.js
  packages/canvas/canvas-sprite/src/Sprite.js
  packages/sprite-animated/src/AnimatedSprite.js
  packages/sprite-tiling/src/TilingSprite.js
  packages/sprite/src/Sprite.js
Labels: Renderer: Canvas, Type: Bug, Version: v5.x

#5739 BlendMode alpha fix.
  packages/core/src/state/utils/mapWebGLBlendModesToPixi.js
Labels: Type: Bug, Version: v5.x

#5701 FilterSystem: remove division that can cause problems
  packages/core/src/filters/FilterSystem.js
Labels: Plugin: Filters, X-files
