Repository pixijs/pixijs, pull requests merged in 2019-07, with the labels that each got.

#5833 Max FPS can be disabled by setting to 0.
  packages/ticker/src/Ticker.js
Labels: Resolution: Merged, Version: v5.x

#5858 Adds new ImageBitmapResource
  packages/core/src/textures/resources/CanvasResource.js
  packages/core/src/textures/resources/ImageBitmapResource.js
  packages/core/src/textures/resources/index.js
  packages/core/test/ImageBitmapResource.js
  packages/core/test/autoDetectResource.js
  packages/core/test/index.js
Labels: Plugin: Texture Resource, Resolution: Merged

#5871 Batch renderer types
  packages/core/src/batch/BatchPluginFactory.js
  packages/core/src/batch/BatchRenderer.js
Labels: Resolution: Merged

#5695 touchmoves will now have the 'target' property set
  packages/interaction/src/InteractionManager.js
Labels: Plugin: Interaction Manager, Version: v5.x

#5890 Moved _renderCanvas call from text package into new canvas-text package
  bundles/pixi.js-legacy/package.json
  bundles/pixi.js-legacy/src/index.js
  packages/canvas/canvas-text/LICENSE
  packages/canvas/canvas-text/README.md
  packages/canvas/canvas-text/package.json
  packages/canvas/canvas-text/src/Text.js
  packages/canvas/canvas-text/src/index.js
  packages/text/src/Text.js
  tools/integration-tests/package.json
  tools/integration-tests/test/display/getLocalBounds.js
Labels: Plugin: Text, Version: v5.x

#5898 Uses super instead of prototype.call
  packages/core/src/Renderer.js
Labels: Priority: Low

#5836 Supports resolutions less than 1
  packages/canvas/canvas-extract/src/CanvasExtract.js
  packages/canvas/canvas-sprite/src/CanvasSpriteRenderer.js
  packages/core/src/textures/BaseTexture.js
  packages/extract/src/Extract.js
  packages/text/src/Text.js
Labels: Version: v5.x, X-files

#5933 Fix return GraphicsGeometry chain, not GraphicsData
  packages/graphics/src/GraphicsGeometry.js
Labels: Plugin: Graphics, Priority: Low

#5945 Fixing batch breaking by empty filter array.
  packages/display/src/Container.js
Labels: Plugin: Filters, The Best, Version: v4.x, Version: v5.x

#5951 A couple of more deprecations after moving from v4 to v5
  bundles/pixi.js/src/useDeprecated.js
Labels: Version: v5.x

#5950 Fix the DisplayObject type declaration
  types/events.d.ts
Labels: Domain: Types

#5963 Updated docs on app ticker
  packages/app/src/Application.js
Labels: Domain: Documentation, Version: v5.x

#5952 Support manual changes in GraphicsData
  packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.js
  packages/graphics/src/GraphicsGeometry.js
Labels: Plugin: Graphics

#5970 Fix dev with getTestContext tweak
  packages/core/src/shader/utils/getTestContext.js
Labels: Priority: Critical

#5971 Removed duplicate type declaration
  types/events.d.ts
Labels: Domain: Types
