Repository pixijs/pixijs, pull requests merged in 2019-03, with the labels that each got.

#5482 Provides better documentation for color utilities
  packages/utils/src/color/hex.js
Labels: Domain: Documentation

#5488 Mistake in typings
  packages/core/src/shader/Program.js
Labels: Domain: Types

#5492 Fix a bug when resizing render texture with resolution other than one
  packages/core/src/framebuffer/Framebuffer.js
Labels: Difficulty: Easy, Priority: Critical, Version: v5.x

#5513 Update documentation for RopeGeometry
  packages/mesh-extras/src/geometry/RopeGeometry.js
Labels: Difficulty: Easy, Domain: Documentation

#5526 Fix arc duplicating points
  packages/graphics/src/Graphics.js
Labels: Plugin: Graphics, Type: Bug

#5527 Graphics holes docs fix
  packages/graphics/src/GraphicsData.js
  packages/graphics/src/GraphicsGeometry.js
Labels: Domain: Types, Plugin: Graphics

#5530 Cleans up ICanvasImageSource typings/docs
  packages/canvas/canvas-renderer/src/BaseTexture.js
  packages/canvas/canvas-sprite/src/CanvasSpriteRenderer.js
Labels: Domain: Documentation, Domain: Types

#5532 Fixes premultiply docs
  packages/utils/src/color/premultiply.js
Labels: Domain: Documentation

#5535 Bumps all build dependencies
  bundles/pixi.js-legacy/package.json
  bundles/pixi.js/package.json
  package-lock.json
  package.json
  packages/accessibility/package.json
  packages/app/package.json
  packages/canvas/canvas-display/package.json
  packages/canvas/canvas-extract/package.json
  packages/canvas/canvas-graphics/package.json
  packages/canvas/canvas-mesh/package.json
  packages/canvas/canvas-particles/package.json
  packages/canvas/canvas-prepare/package.json
  packages/canvas/canvas-renderer/package.json
  packages/canvas/canvas-sprite-tiling/package.json
  packages/canvas/canvas-sprite/package.json
  packages/constants/package.json
  packages/core/package.json
  packages/display/package.json
  packages/extract/package.json
  packages/filters/filter-alpha/package.json
  packages/filters/filter-blur/package.json
  packages/filters/filter-color-matrix/package.json
  packages/filters/filter-displacement/package.json
  packages/filters/filter-fxaa/package.json
  packages/filters/filter-noise/package.json
  packages/graphics/package.json
  packages/interaction/package.json
  packages/loaders/package.json
  packages/math/package.json
  packages/mesh-extras/package.json
  packages/mesh/package.json
  packages/mixin-cache-as-bitmap/package.json
  packages/mixin-get-child-by-name/package.json
  packages/mixin-get-global-position/package.json
  packages/particles/package.json
  packages/polyfill/package.json
  packages/prepare/package.json
  packages/runner/package.json
  packages/settings/package.json
  packages/sprite-animated/package.json
  packages/sprite-tiling/package.json
  packages/sprite/package.json
  packages/spritesheet/package.json
  packages/text-bitmap/package.json
  packages/text/package.json
  packages/ticker/package.json
  packages/utils/package.json
  rollup.config.js
  tools/integration-tests/package.json
Labels: Difficulty: Easy, Domain: Tooling
