Repository pixijs/pixijs, pull requests merged in 2019-04, with the labels that each got.

#5556 Properly deprecate BaseTexture v4 members and methods
  bundles/pixi.js/src/useDeprecated.js
Labels: Difficulty: Easy, Version: v5.x

#5558 Cant bind active destroyed vao
  packages/core/src/geometry/GeometrySystem.js
Labels: Difficulty: Easy, Version: v5.x

#5567 Fix for rounded rect #5540
  packages/graphics/src/utils/buildCircle.js
  packages/graphics/src/utils/buildRoundedRectangle.js
Labels: Plugin: Graphics, Type: Bug, Version: v5.x

#5546 Assure that TICK is different for multi-textured renderers
  packages/core/src/batch/BatchRenderer.js
  packages/core/src/textures/BaseTexture.js
  packages/graphics/src/GraphicsGeometry.js
Labels: Plugin: Graphics, Priority: Critical, Type: Bug

#5572 Fixes canvas and filters being copied
  package.json
Labels: Difficulty: Easy, Domain: Tooling

#5555 Filter migration
  bundles/pixi.js/src/useDeprecated.js
  packages/core/src/filters/Filter.js
  packages/core/src/filters/FilterSystem.js
  packages/core/src/filters/filterTransforms.js
  packages/core/src/filters/spriteMask/SpriteMaskFilter.js
  packages/core/src/textures/TextureMatrix.js
  packages/filters/filter-displacement/src/DisplacementFilter.js
Labels: Difficulty: Hard, Plugin: Filters

#5592 Adds format and quality options to extract plugins
  packages/canvas/canvas-extract/src/CanvasExtract.js
  packages/extract/src/Extract.js
Labels: Plugin: Extract, Version: v5.x

#5599 Adds a potentially taller character to the metrics string
  packages/text/src/TextMetrics.js
Labels: Plugin: Text, Version: v5.x

#5600 Updated dependencies
  package-lock.json
  package.json
  packages/loaders/package.json
  packages/polyfill/package.json
  packages/runner/benchmark/package.json
  packages/utils/package.json
Labels: Version: v5.x

#5603 fix for cacheAsBitmap
  packages/core/src/Renderer.js
Labels: Difficulty: Easy, Priority: Critical, Version: v5.x

#5604 isWebGLSupported util function is now cached
  packages/utils/src/browser/isWebGLSupported.js
Labels: Version: v5.x

#5606 Ensure that a mouseout is fired with masked containers
  packages/interaction/src/InteractionManager.js
Labels: Plugin: Interaction Manager, Version: v5.x

#5602 Fragment shader precision detection
  packages/core/src/shader/Program.js
  packages/core/src/shader/utils/getMaxFragmentPrecision.js
  packages/core/src/shader/utils/index.js
  packages/core/src/shader/utils/setPrecision.js
  packages/settings/src/settings.js
Labels: Version: v5.x

#5591 [v4] Disables latest tagged Travis release
  .travis.yml
Labels: Difficulty: Easy, Domain: Tooling, Version: v4.x

#5590 [v5] Enables latest tagged Travis release
  .travis.yml
Labels: Difficulty: Easy, Domain: Tooling, Version: v5.x

#5608 Fixes emoji characters not displaying when letterSpacing style is used
  packages/text/src/Text.js
Labels: Plugin: Text, Version: v5.x

#5616 Updated comments and docs for deprecated methods / properties.
  README.md
  bundles/pixi.js-legacy/README.md
  bundles/pixi.js/src/useDeprecated.js
  packages/app/src/Application.js
  packages/canvas/canvas-mesh/src/CanvasMeshRenderer.js
  packages/core/src/renderTexture/BaseRenderTexture.js
  packages/core/src/textures/Texture.js
  packages/mesh-extras/package.json
  packages/mesh-extras/src/SimplePlane.js
  packages/mesh-extras/test/SimplePlane.js
  packages/mesh-extras/test/index.js
  packages/prepare/src/BasePrepare.js
  packages/settings/src/settings.js
  packages/sprite-animated/src/AnimatedSprite.js
  packages/sprite/src/Sprite.js
  packages/spritesheet/src/Spritesheet.js
  packages/spritesheet/test/SpritesheetLoader.js
  packages/ticker/src/Ticker.js
  tools/integration-tests/test/display/Bounds.js
Labels: Domain: Documentation, Version: v5.x
