Repository pixijs/pixijs, pull requests merged in 2019-01, with the labels that each got.

#5316 TextureMatrix and SimplePlane texture change fix
  packages/core/src/textures/TextureMatrix.js
  packages/mesh-extras/src/NineSlicePlane.js
  packages/mesh-extras/src/SimpleMesh.js
  packages/mesh-extras/src/SimplePlane.js
Labels: Difficulty: Medium, Plugin: Mesh, Type: Bug, Version: v5.x

#5320 Fixes issue where antialiasing setting is always true regardless of options passed in
  packages/core/src/Renderer.js
Labels: Difficulty: Easy

#5315 v4 - interaction assignment fix
  src/interaction/InteractionManager.js
Labels: Plugin: Interaction Manager, Type: Bug, Version: v4.x

#5328 Stencil RenderBuffer leak
  src/core/renderers/webgl/utils/RenderTarget.js
Labels: Priority: Critical, Type: Bug, Version: v4.x

#5329 A batch of small fixes and tweaks for v5
  packages/core/src/geometry/GeometrySystem.js
  packages/core/src/shader/Program.js
  packages/core/src/shader/utils/setPrecision.js
  packages/core/src/textures/TextureSystem.js
  packages/sprite/src/Sprite.js
Labels: Difficulty: Medium, Type: Bug, Version: v5.x

#5327 Updates build tool dependencies
  .eslintrc.json
  bundles/pixi.js-legacy/package.json
  bundles/pixi.js/package.json
  lerna.json
  package-lock.json
  package.json
  rollup.config.js
  test/index.js
Labels: Difficulty: Medium, Domain: Tooling, Priority: High, Type: Enhancement, Version: v5.x

#5343 Temporarily skip problematic tests
  packages/ticker/test/Ticker.js
  test/index.js
  test/packages.js
Labels: Difficulty: Easy, Domain: Tests, Priority: Critical

#5317 Auto generation for typescript definitions
  .gitignore
  bundles/pixi.js-legacy/pixi.js-legacy.d.ts
  bundles/pixi.js/pixi.js.d.ts
  jsdoc.conf.json
  package-lock.json
  package.json
  types/assemble.js
  types/events.d.ts
  types/jsdoc-legacy.conf.json
  types/jsdoc.conf.json
  types/loader.d.ts
Labels: Difficulty: Medium, Domain: Documentation, Domain: Tooling, Domain: Types, Priority: High, Type: Enhancement, Version: v5.x

#5360 V4 rectangle fit
  src/core/math/shapes/Rectangle.js
  test/core/Rectangle.js
Labels: Plugin: Filters, Priority: Critical, Type: Bug, Version: v5.x

#5358 DisplayObject is not sprite by default
  packages/display/src/DisplayObject.js
Labels: Priority: Critical, Version: v5.x

#5357 V5/ticker enhancements
  packages/ticker/src/Ticker.js
Labels: Version: v5.x

#5355 Allows developer to limit the texture update rate of videos
  packages/core/src/textures/resources/VideoResource.js
  packages/core/src/textures/resources/autoDetectResource.js
  packages/core/test/VideoResource.js
Labels: Version: v5.x

#5363 Animated Sprite does not full destroy properly
  packages/sprite-animated/src/AnimatedSprite.js
Labels: Version: v5.x

#5362 Updating package.json descriptions.
  README.md
  packages/app/package.json
  packages/canvas/canvas-display/package.json
  packages/canvas/canvas-extract/package.json
  packages/canvas/canvas-graphics/package.json
  packages/canvas/canvas-mesh/package.json
  packages/canvas/canvas-particles/package.json
  packages/canvas/canvas-prepare/package.json
  packages/canvas/canvas-renderer/package.json
  packages/canvas/canvas-sprite-tiling/package.json
  packages/canvas/canvas-sprite/package.json
  packages/constants/package.json
  packages/display/package.json
  packages/filters/filter-alpha/package.json
  packages/filters/filter-blur/package.json
  packages/filters/filter-color-matrix/package.json
  packages/filters/filter-displacement/package.json
  packages/filters/filter-fxaa/package.json
  packages/filters/filter-noise/package.json
  packages/fragments/package.json
  packages/graphics/package.json
  packages/interaction/package.json
  packages/loaders/package.json
  packages/math/package.json
  packages/mesh/package.json
  packages/mixin-cache-as-bitmap/package.json
  packages/mixin-get-child-by-name/package.json
  packages/mixin-get-global-position/package.json
  packages/particles/package.json
  packages/prepare/package.json
  packages/settings/package.json
  packages/sprite-animated/package.json
  packages/sprite-tiling/package.json
  packages/sprite/package.json
  packages/spritesheet/package.json
  packages/text-bitmap/package.json
  packages/text/package.json
  packages/ticker/package.json
  packages/utils/package.json
Labels: Version: v5.x

#5368 Fixes CanvasExtract plugin canvas method without target
  src/extract/canvas/CanvasExtract.js
Labels: Difficulty: Easy, Plugin: Extract, Renderer: Canvas, Type: Bug, Version: v4.x, Version: v5.x

#5369 A system ticker to sit alongside the shared ticker.
  packages/interaction/src/InteractionManager.js
  packages/interaction/test/MockPointer.js
  packages/prepare/src/BasePrepare.js
  packages/prepare/test/BasePrepare.js
  packages/ticker/src/Ticker.js
  packages/ticker/src/TickerPlugin.js
  packages/ticker/test/Ticker.js
Labels: Version: v5.x

#5375 v5 - Fixes Text drop shadows
  packages/text/src/Text.js
  packages/utils/src/color/hex.js
Labels: Plugin: Text, Version: v5.x

#5364 BasePrepare was imbedding settings rather than having a settings.js file like other classes
  packages/prepare/src/BasePrepare.js
  packages/prepare/src/index.js
  packages/prepare/src/settings.js
  packages/ticker/src/index.js
  packages/utils/src/index.js
Labels: Version: v5.x

#5377 there is no BLEND_MODES.NONE
  packages/constants/src/index.js
  packages/core/src/state/State.js
Labels: Version: v5.x

#5349 Proper disposal for mesh and graphics geometries
  packages/core/src/geometry/Buffer.js
  packages/core/src/geometry/GLBuffer.js
  packages/core/src/geometry/Geometry.js
  packages/core/src/geometry/GeometrySystem.js
  packages/graphics/src/Graphics.js
  packages/mesh/src/Mesh.js
Labels: Priority: Critical, Type: Enhancement, Version: v5.x

#5392 Fix for BLEND_MODES.NONE in StateSystem
  packages/core/src/state/StateSystem.js
Labels: Difficulty: Easy, Priority: Critical, Type: Bug, Version: v5.x

#5393 V4.x nineslice tint
  src/mesh/NineSlicePlane.js
Labels: Plugin: Mesh, Type: Bug, Version: v4.x
