Repository pixijs/pixijs, pull requests merged in 2019-12, with the labels that each got.

#6258 Little shader speed up!
  packages/core/src/shader/utils/compileProgram.js
Labels: Difficulty: Easy, Domain: Performance

#6270 BlurFilter: clear temporary texture
  packages/filters/filter-blur/src/BlurFilterPass.js
Labels: Plugin: Filters, Type: Bug

#6234 Fixes roundPixels calculation differences between v4 and v5
  packages/mesh/src/Mesh.js
  packages/sprite/src/Sprite.js
Labels: Renderer: WebGL, Version: v5.x
