Repository pixijs/pixijs, pull requests merged in 2019-06, with the labels that each got.

#5749 change blend mode type from `boolean` to `number`
  packages/core/src/state/State.js
Labels: Domain: Types

#5755 typings renderTexture bind
  packages/core/src/renderTexture/RenderTextureSystem.js
Labels: Domain: Types

#5772 Fixes issue with docs/types with BatchPluginFactory
  packages/core/src/batch/BatchPluginFactory.js
  packages/core/src/index.js
Labels: Domain: Types

#5782 Hotfix for OffscreenCanvas + Firefox
  packages/core/src/textures/resources/CanvasResource.js
Labels: Priority: Critical

#5779 Adds support for deploying Typescript typings to pixijs.download
  package.json
Labels: Domain: Tooling, Domain: Types

#5787 Fix JSDoc type of refCount
  packages/core/src/geometry/Geometry.js
Labels: Domain: Documentation

#5791 Feature/set state rename
  bundles/pixi.js/src/useDeprecated.js
  packages/core/src/batch/BatchRenderer.js
  packages/core/src/filters/FilterSystem.js
  packages/core/src/state/StateSystem.js
  packages/graphics/src/Graphics.js
  packages/mesh/src/Mesh.js
Labels: Difficulty: Easy

#5811 Adds a setting that allows disabling the 'failIfMajorPerformanceCaveat' flag used in the 'isWebGLSupported' function
  packages/utils/src/browser/isWebGLSupported.js
  packages/utils/src/settings.js
Labels: Version: v5.x

#5835 Small optimisation with text and gradients
  packages/text/src/Text.js
Labels: Version: v5.x

#5834 Fixes the prepare system in v5
  bundles/pixi.js/src/useDeprecated.js
  packages/core/src/textures/BaseTexture.js
  packages/core/src/textures/TextureGCSystem.js
  packages/core/src/textures/TextureSystem.js
  packages/prepare/src/Prepare.js
Labels: Priority: High, Version: v5.x
