Repository pixijs/pixijs, pull requests merged in 2020-04, with the labels that each got.

#6469 Line height & leading support for vertical text gradients
  packages/text/src/Text.ts
Labels: ✅ Ready To Merge

#6534 Unsubscribe from baseTexture loaded event on Texture::destroy
  packages/core/src/textures/Texture.ts
  packages/core/test/Texture.js
Labels: ✅ Ready To Merge

#6532 Fixes SimpleRope on Canvas renderer
  packages/canvas/canvas-mesh/src/SimpleRope.js
Labels: ✅ Ready To Merge

#6539 Handle extreme radius inputs for rounded rect
  packages/graphics/src/utils/buildRoundedRectangle.ts
Labels: ✅ Ready To Merge

#6540 Fix issue with preparing Graphics without shader
  packages/prepare/src/Prepare.ts
Labels: ⏰ Future Work, ✅ Ready To Merge

#6551 Fix ismobilejs breakage
  packages/settings/package.json
  packages/settings/src/utils/isMobile.ts
Labels: 🔥 High Priority

#6508 Fix Texture leak with SpritesheetLoader
  packages/spritesheet/src/SpritesheetLoader.ts
  packages/spritesheet/test/SpritesheetLoader.js
Labels: ✅ Ready To Merge

#6559 Fixed example code for RenderTexture.create()
  packages/core/src/renderTexture/RenderTexture.ts
Labels: ✅ Ready To Merge

#6486 Fix SVG disposed while loading
  packages/core/src/textures/resources/SVGResource.ts
Labels: ✅ Ready To Merge

#6561 RenderTexture#destroy destroys the depth texture as well.
  packages/core/src/framebuffer/Framebuffer.ts
  packages/core/src/framebuffer/FramebufferSystem.ts
  packages/core/src/renderTexture/BaseRenderTexture.ts
  packages/core/test/RenderTexture.js
  packages/core/test/index.js
Labels: ✅ Ready To Merge

#6562 Added center to list of "points" in circle-shape so it can be transfo…
  packages/graphics/src/utils/buildCircle.ts
  packages/graphics/test/index.js
Labels: ✅ Ready To Merge

#6520 Fix filters to sum padding instead of max padding
  packages/core/src/filters/FilterSystem.ts
Labels: ✅ Ready To Merge

#6565 Removed center from points
  packages/graphics/src/utils/buildCircle.ts
  packages/graphics/test/index.js
Labels: ✅ Ready To Merge, 🔥 High Priority

#6564 Support BitmapText resolution on high-density displays (fixes #5171)
  packages/text-bitmap/src/BitmapFont.ts
Labels: ✅ Ready To Merge

#6546 [RFC] Github Actions
  .editorconfig
  .github/workflows/nodejs.yml
  .travis.yml
  README.md
Labels: ✅ Ready To Merge

#6580 Hotfix for Spritesheet memory leak PR #6508
  packages/spritesheet/src/Spritesheet.ts
  packages/spritesheet/src/SpritesheetLoader.ts
Labels: ✅ Ready To Merge, 🔥 High Priority

#6584 Docs updated for line join, cap, & miter limit features
  packages/constants/src/index.ts
  packages/core/src/Renderer.ts
  packages/graphics/src/Graphics.ts
  packages/graphics/src/const.ts
  packages/graphics/src/styles/LineStyle.ts
  packages/graphics/src/utils/buildLine.ts
  types/jsdoc.conf.json
Labels: ✅ Ready To Merge
