Repository pixijs/pixijs, pull requests merged in 2020-05, with the labels that each got.

#6588 Fix IE11 canvas renderer setTransform problem
  packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.js
Labels: ✅ Ready To Merge, 🔥 High Priority

#6601 Fix typo
  packages/core/src/batch/AbstractBatchRenderer.ts
Labels: ✅ Ready To Merge

#6598 Update graphics README.md
  packages/graphics/README.md
Labels: ✅ Ready To Merge

#6503 Convert canvas-extract to TypeScript
  packages/canvas/canvas-extract/package.json
  packages/canvas/canvas-extract/src/CanvasExtract.ts
  packages/canvas/canvas-extract/src/index.ts
Labels: ✅ Ready To Merge

#6591 Map video file extension to correct mime subtype where necessary
  packages/core/src/textures/resources/VideoResource.ts
Labels: ✅ Ready To Merge

#6581 Support Github Actions, remove Travis (#6546)
  .editorconfig
  .github/workflows/nodejs.yml
  .travis.yml
  README.md
  package.json
Labels: ✅ Ready To Merge

#6607 Build for all push branches including ones with slashes
  .github/workflows/nodejs.yml
Labels: ✅ Ready To Merge, 🔥 High Priority

#6605 Fixes #6604 slow runs on CI timing out mocha
  packages/core/test/MaskSystem.js
Labels: ✅ Ready To Merge, 🔥 High Priority

#6603 If the user agent string didn't include the OS version one day, it'd default to allowMax
  packages/settings/src/utils/maxRecommendedTextures.ts
Labels: ✅ Ready To Merge, 👀 Needs Review, 🥶 Low Priority

#6618 Fix typo in Graphic.clone documentation
  packages/graphics/src/Graphics.ts
Labels: ✅ Ready To Merge

#6613 Introduces optional Graphics Extras Package
  packages/graphics-extras/README.md
  packages/graphics-extras/global.d.ts
  packages/graphics-extras/package.json
  packages/graphics-extras/src/drawChamferRect.ts
  packages/graphics-extras/src/drawFilletRect.ts
  packages/graphics-extras/src/drawRegularPolygon.ts
  packages/graphics-extras/src/drawTorus.ts
  packages/graphics-extras/src/index.ts
  packages/graphics/global.d.ts
  packages/graphics/src/Graphics.ts
Labels: ✅ Ready To Merge

#6600 BitmapFontFactory
  packages/text-bitmap/package.json
  packages/text-bitmap/src/BitmapFont.ts
  packages/text-bitmap/src/BitmapText.ts
  packages/text-bitmap/src/BitmapTextStyle.ts
  packages/text-bitmap/src/utils/generateFillStyle.ts
  packages/text-bitmap/test/BitmapFont.js
  packages/text-bitmap/test/index.js
Labels: ✅ Ready To Merge

#6626 Convert mixin-get-child-by-name to TS
  packages/display/global.d.ts
  packages/display/src/Container.ts
  packages/mixin-get-child-by-name/global.d.ts
  packages/mixin-get-child-by-name/src/index.ts
Labels: ✅ Ready To Merge

#6632 Slack Invite!
  README.md
Labels: ✅ Ready To Merge

#6634 Fix JSDoc comments for @param tags so that there is a hypen before description
  packages/app/src/Application.ts
  packages/canvas/canvas-renderer/src/CanvasRenderer.ts
  packages/core/src/Renderer.ts
  packages/core/src/batch/BatchGeometry.ts
  packages/core/src/batch/BatchSystem.ts
  packages/core/src/context/ContextSystem.ts
  packages/core/src/filters/FilterSystem.ts
  packages/core/src/framebuffer/FramebufferSystem.ts
  packages/core/src/geometry/Attribute.ts
  packages/core/src/geometry/Buffer.ts
  packages/core/src/geometry/Geometry.ts
  packages/core/src/geometry/GeometrySystem.ts
  packages/core/src/mask/MaskData.ts
  packages/core/src/renderTexture/RenderTexturePool.ts
  packages/core/src/shader/ShaderSystem.ts
  packages/core/src/state/StateSystem.ts
  packages/core/src/textures/BaseTexture.ts
  packages/core/src/textures/Texture.ts
  packages/core/src/textures/TextureMatrix.ts
  packages/core/src/textures/resources/ArrayResource.ts
  packages/core/src/textures/resources/BaseImageResource.ts
  packages/core/src/textures/resources/BufferResource.ts
  packages/core/src/textures/resources/CubeResource.ts
  packages/core/src/textures/resources/DepthResource.ts
  packages/core/src/textures/resources/ImageResource.ts
  packages/core/src/textures/resources/Resource.ts
  packages/core/src/textures/resources/SVGResource.ts
  packages/display/src/Bounds.ts
  packages/display/src/Container.ts
  packages/display/src/DisplayObject.ts
  packages/filters/filter-alpha/src/AlphaFilter.ts
  packages/graphics/src/Graphics.ts
  packages/graphics/src/GraphicsGeometry.ts
  packages/interaction/src/InteractionData.js
  packages/math/src/Matrix.ts
  packages/mesh-extras/src/NineSlicePlane.ts
  packages/mesh/src/Mesh.ts
  packages/particles/src/ParticleContainer.ts
  packages/runner/src/Runner.ts
  packages/sprite-tiling/src/TilingSpriteRenderer.ts
  packages/sprite/src/Sprite.ts
  packages/spritesheet/src/Spritesheet.ts
  packages/text-bitmap/src/BitmapFontLoader.ts
  packages/text-bitmap/src/formats/TextFormat.ts
  packages/text/src/TextMetrics.ts
  packages/text/src/TextStyle.ts
  packages/utils/src/color/hex.ts
  packages/utils/src/color/premultiply.ts
  packages/utils/src/data/pow2.ts
  packages/utils/src/data/removeItems.ts
  packages/utils/src/index.ts
Labels: ✅ Ready To Merge

#6640 Improve API usage of BitmapFont.from
  packages/text-bitmap/src/BitmapFont.ts
  packages/text-bitmap/src/utils/drawGlyph.ts
  packages/text-bitmap/src/utils/index.ts
  packages/text-bitmap/src/utils/resolveCharacters.ts
  packages/text-bitmap/test/BitmapFont.js
Labels: ✅ Ready To Merge

#6622 Convert canvas-particles to TS
  packages/canvas/canvas-particles/src/ParticleContainer.ts
  packages/canvas/canvas-particles/src/index.ts
Labels: ✅ Ready To Merge

#6630 Convert mixin-cache-as-bitmap to TS
  packages/core/src/textures/Texture.ts
  packages/mixin-cache-as-bitmap/global.d.ts
  packages/mixin-cache-as-bitmap/src/index.ts
Labels: ✅ Ready To Merge

#6631 .gitignore the package.lock.json files in the packages
  .gitignore
Labels: ✅ Ready To Merge

#6637 Convert mixin-get-global-position to TS
  packages/mixin-get-global-position/global.d.ts
  packages/mixin-get-global-position/src/index.ts
Labels: ✅ Ready To Merge

#6641 BitmapText optimisation
  packages/core/src/textures/BaseTexture.ts
  packages/text-bitmap/package.json
  packages/text-bitmap/src/BitmapFont.ts
  packages/text-bitmap/src/BitmapText.ts
  packages/text-bitmap/test/BitmapText.js
Labels: ✅ Ready To Merge

#6645 Fix documented parameters
  packages/core/src/geometry/Attribute.ts
  packages/core/src/projection/ProjectionSystem.ts
  packages/core/src/textures/resources/BaseImageResource.ts
  packages/core/src/textures/resources/ImageResource.ts
  packages/graphics/src/Graphics.ts
  packages/graphics/src/utils/ArcUtils.ts
  packages/graphics/src/utils/buildLine.ts
Labels: ✅ Ready To Merge

#6649 Fix docs for graphicsUtils namespace and members
  packages/graphics/src/utils/Star.ts
  packages/graphics/src/utils/index.ts
Labels: ✅ Ready To Merge

#6654 convert polyfill package to TypeScript
  global.d.ts
  packages/polyfill/src/Math.sign.ts
  packages/polyfill/src/Number.isInteger.ts
  packages/polyfill/src/Object.assign.ts
  packages/polyfill/src/Promise.ts
  packages/polyfill/src/index.ts
  packages/polyfill/src/requestAnimationFrame.ts
Labels: ✅ Ready To Merge

#6656 convert interaction package to TypeScript
  packages/interaction/global.d.ts
  packages/interaction/src/InteractionData.ts
  packages/interaction/src/InteractionEvent.ts
  packages/interaction/src/InteractionManager.ts
  packages/interaction/src/InteractionTrackingData.ts
  packages/interaction/src/TreeSearch.ts
  packages/interaction/src/index.ts
  packages/interaction/src/interactiveTarget.ts
Labels: ✅ Ready To Merge

#6643 Change the default BitmapFont texture size
  packages/text-bitmap/src/BitmapFont.ts
Labels: ✅ Ready To Merge

#6669 Replace global for window in polyfill
  global.d.ts
  packages/polyfill/src/requestAnimationFrame.ts
Labels: 🔥 High Priority

#6658 Convert canvas-sprite to TypeScript
  packages/canvas/canvas-renderer/src/CanvasRenderer.ts
  packages/canvas/canvas-sprite/global.d.ts
  packages/canvas/canvas-sprite/src/CanvasSpriteRenderer.ts
  packages/canvas/canvas-sprite/src/Sprite.ts
  packages/canvas/canvas-sprite/src/index.ts
  packages/sprite/global.d.ts
  packages/sprite/src/Sprite.ts
Labels: ✅ Ready To Merge

#6663 convert canvas graphics package to TypeScript
  packages/canvas/canvas-graphics/global.d.ts
  packages/canvas/canvas-graphics/package.json
  packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.ts
  packages/canvas/canvas-graphics/src/Graphics.ts
  packages/canvas/canvas-graphics/src/index.ts
Labels: ✅ Ready To Merge

#6664 convert canvas mesh to TypeScript
  packages/canvas/canvas-mesh/global.d.ts
  packages/canvas/canvas-mesh/src/CanvasMeshRenderer.ts
  packages/canvas/canvas-mesh/src/Mesh.ts
  packages/canvas/canvas-mesh/src/MeshMaterial.ts
  packages/canvas/canvas-mesh/src/NineSlicePlane.ts
  packages/canvas/canvas-mesh/src/SimpleMesh.ts
  packages/canvas/canvas-mesh/src/SimpleRope.ts
  packages/canvas/canvas-mesh/src/index.ts
  packages/canvas/canvas-mesh/src/settings.ts
  packages/mesh-extras/global.d.ts
  packages/mesh-extras/src/NineSlicePlane.ts
  packages/mesh/global.d.ts
  packages/mesh/src/Mesh.ts
  packages/mesh/src/MeshMaterial.ts
Labels: ✅ Ready To Merge

#6671 Add options to style passed in BitmapText constructor.
  bundles/pixi.js/src/useDeprecated.js
  packages/text-bitmap/src/BitmapFont.ts
  packages/text-bitmap/src/BitmapText.ts
  packages/text-bitmap/src/BitmapTextStyle.ts
  packages/text-bitmap/test/BitmapFontLoader.js
  packages/text-bitmap/test/BitmapText.js
Labels: ✅ Ready To Merge

#6665 convert canvas tiling sprite to TypeScript
  packages/canvas/canvas-sprite-tiling/global.d.ts
  packages/canvas/canvas-sprite-tiling/src/TilingSprite.ts
  packages/canvas/canvas-sprite-tiling/src/index.ts
  packages/sprite-tiling/global.d.ts
  packages/sprite-tiling/src/TilingSprite.ts
  packages/sprite/src/Sprite.ts
Labels: ✅ Ready To Merge
