Repository pixijs/pixijs, pull requests merged in 2020-11, with the labels that each got.

#6880 Fixes to support running pixi in WebWorker
  packages/accessibility/src/AccessibilityManager.ts
  packages/app/src/ResizePlugin.ts
  packages/canvas/canvas-mesh/src/Mesh.ts
  packages/core/src/context/ContextSystem.ts
  packages/core/src/textures/resources/CanvasResource.ts
  packages/core/src/textures/resources/ImageBitmapResource.ts
  packages/core/src/textures/resources/ImageResource.ts
  packages/core/src/textures/resources/VideoResource.ts
  packages/interaction/src/InteractionManager.ts
  packages/polyfill/src/Promise.ts
  packages/polyfill/src/index.ts
  packages/polyfill/src/requestAnimationFrame.ts
  packages/settings/src/utils/isMobile.ts
  packages/text-bitmap/src/formats/XMLStringFormat.ts
  packages/unsafe-eval/src/bundle.ts
  packages/utils/src/browser/hello.ts
  packages/utils/src/browser/isWebGLSupported.ts
  packages/utils/src/network/determineCrossOrigin.ts
Labels: ✅ Ready To Merge

#6949 Use frame.x|y in getImageData call for CanvasExtract.
  packages/canvas/canvas-extract/src/CanvasExtract.ts
Labels: ✅ Ready To Merge, 🕷 Bug

#6960 [Feature]: toString methods for debugging
  packages/core/src/state/State.ts
  packages/core/src/textures/TextureUvs.ts
  packages/math/src/Matrix.ts
  packages/math/src/ObservablePoint.ts
  packages/math/src/Point.ts
  packages/math/src/Transform.ts
  packages/math/src/shapes/Circle.ts
  packages/math/src/shapes/Ellipse.ts
  packages/math/src/shapes/Polygon.ts
  packages/math/src/shapes/Rectangle.ts
  packages/math/src/shapes/RoundedRectangle.ts
Labels: ✅ Ready To Merge

#6968 Support text alignment 'justify' in BitmapText
  packages/text-bitmap/src/BitmapText.ts
  packages/text/src/TextStyle.ts
Labels: ✅ Ready To Merge

#6983 Enable scissor mask support by default
  packages/core/src/mask/MaskSystem.ts
Labels: ✅ Ready To Merge

#6868 framebuffer.blit() in StencilSystem.push
  packages/core/src/mask/StencilSystem.ts
Labels: ✅ Ready To Merge

#6999 inject global mixins into index.d.ts
  global.d.ts
  package-lock.json
  package.json
  scripts/injectGlobalMixins.ts
  tsconfig.json
Labels: ✅ Ready To Merge

#7010 Missed Version Substitution
  bundles/pixi.js/src/index.ts
Labels: ✅ Ready To Merge, 🔥 High Priority

#7015 Some fixes for 5.4.0
  packages/interaction/src/InteractionManager.ts
  packages/prepare/src/BasePrepare.ts
Labels: ✅ Ready To Merge

#7006 fix some types in 5.4.0-rc.2
  packages/canvas/canvas-renderer/src/CanvasRenderer.ts
  packages/core/src/Renderer.ts
  packages/core/src/autoDetectRenderer.ts
  packages/core/src/filters/FilterSystem.ts
  packages/core/src/framebuffer/FramebufferSystem.ts
  packages/core/src/geometry/Geometry.ts
  packages/core/src/renderTexture/BaseRenderTexture.ts
  packages/core/src/renderTexture/RenderTexture.ts
  packages/core/src/renderTexture/RenderTexturePool.ts
  packages/core/src/shader/Shader.ts
  packages/core/src/shader/UniformGroup.ts
  packages/core/src/textures/BaseTexture.ts
  packages/core/src/textures/Texture.ts
  packages/core/src/textures/resources/BaseImageResource.ts
  packages/core/src/textures/resources/SVGResource.ts
  packages/display/src/DisplayObject.ts
  packages/filters/filter-displacement/src/DisplacementFilter.ts
  packages/graphics/src/Graphics.ts
  packages/graphics/src/utils/Star.ts
  packages/interaction/src/InteractionManager.ts
  packages/loaders/src/LoaderResource.ts
  packages/mesh-extras/src/SimplePlane.ts
  packages/mesh/src/Mesh.ts
  packages/mixin-cache-as-bitmap/src/index.ts
  packages/particles/src/ParticleContainer.ts
  packages/prepare/src/BasePrepare.ts
  packages/sprite-animated/src/AnimatedSprite.ts
  packages/sprite-tiling/src/TilingSprite.ts
  packages/sprite/src/Sprite.ts
  packages/text/src/Text.ts
  packages/text/src/TextMetrics.ts
  packages/ticker/src/Ticker.ts
  packages/utils/src/color/premultiply.ts
  packages/utils/src/media/CanvasRenderTarget.ts
Labels: ✅ Ready To Merge

#7018 Fix memory leak with BitmapText
  packages/text-bitmap/src/BitmapText.ts
Labels: ✅ Ready To Merge

#7020 BASIS fixes
  packages/basis/assets/basis_transcoder.js
  packages/basis/src/BasisLoader.ts
  packages/basis/src/TranscoderWorkerWrapper.ts
  packages/compressed-textures/src/loaders/KTXLoader.ts
  packages/compressed-textures/src/resources/CompressedTextureResource.ts
Labels: ✅ Ready To Merge

#7025 Move constructor documentation params from class declaration
  packages/core/src/textures/BaseTexture.ts
  packages/core/src/textures/resources/ArrayResource.ts
  packages/core/src/textures/resources/CanvasResource.ts
  packages/core/src/textures/resources/CubeResource.ts
  packages/core/src/textures/resources/ImageBitmapResource.ts
  packages/core/src/textures/resources/SVGResource.ts
  packages/core/src/textures/resources/VideoResource.ts
  packages/graphics/src/utils/Star.ts
  packages/loaders/src/Loader.ts
Labels: ✅ Ready To Merge

#7023 Add overridable TextMetrics.isBreakingSpace for better CJK plugin support
  packages/text/src/TextMetrics.ts
  packages/text/test/TextMetrics.js
Labels: ✅ Ready To Merge

#7021 Fix bitmap font loader to load fonts with random placed args into <info> tag in 5.4.0-rc.2
  packages/text-bitmap/src/formats/XMLStringFormat.ts
  packages/text-bitmap/test/BitmapFontLoader.js
  packages/text-bitmap/test/resources/font-random-args.fnt
Labels: ✅ Ready To Merge

#6908 Don't set any defaults for properties of MeshMaterial and State in Mesh constructor
  packages/mesh/src/Mesh.ts
Labels: ✅ Ready To Merge

#7032 Fix serious performance problem in canvas renderer
  packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.ts
  packages/canvas/canvas-graphics/test/.eslintrc.json
  packages/canvas/canvas-graphics/test/CanvasGraphicsRenderer.js
  packages/canvas/canvas-graphics/test/index.js
Labels: ✅ Ready To Merge, 🔥 High Priority

#7033 Fix #7029
  packages/filters/filter-blur/src/BlurFilter.ts
  packages/filters/filter-blur/src/BlurFilterPass.ts
Labels: ✅ Ready To Merge
