Repository pixijs/pixijs, pull requests merged in 2020-12, with the labels that each got.

#7034 Fix #6245
  packages/core/src/filters/FilterSystem.ts
Labels: ✅ Ready To Merge

#7042 Silence harmless warning
  packages/text-bitmap/src/utils/drawGlyph.ts
  packages/text/src/Text.ts
Labels: ✅ Ready To Merge

#6985 Upgrade Webdoc
  package-lock.json
  package.json
  packages/core/src/textures/resources/AbstractMultiResource.ts
  packages/graphics-extras/src/drawChamferRect.ts
  packages/graphics-extras/src/drawFilletRect.ts
  packages/graphics-extras/src/drawRegularPolygon.ts
  packages/graphics-extras/src/drawTorus.ts
  packages/graphics/src/Graphics.ts
  packages/loaders/src/Loader.ts
  packages/text/src/TextMetrics.ts
Labels: ✅ Ready To Merge

#7045 Fix typescript definition errors
  packages/core/global.d.ts
  packages/display/src/Container.ts
  packages/utils/package.json
  scripts/injectGlobalMixins.ts
  tsconfig.json
Labels: 🔥 High Priority

#7059 Inline css-color-names, url types, declare loader globals
  packages/loaders/global.d.ts
  packages/utils/package.json
  packages/utils/src/index.ts
Labels: 🔥 High Priority

#7031 Fix measureFont
  packages/text/src/TextMetrics.ts
Labels: ✅ Ready To Merge

#7051 [Fix]: x, y matrix skew comment
  packages/math/src/Matrix.ts
Labels: ✅ Ready To Merge

#7061 Removes all legacy deprecations, better deprecation strategy for v6
  bundles/pixi.js-legacy/package.json
  bundles/pixi.js-legacy/test/index.js
  bundles/pixi.js/package.json
  bundles/pixi.js/src/index.ts
  bundles/pixi.js/src/useDeprecated.ts
  bundles/pixi.js/test/index.js
  packages/canvas/canvas-extract/src/CanvasExtract.ts
  packages/core/src/AbstractRenderer.ts
  packages/core/src/Renderer.ts
  packages/core/src/deprecations.ts
  packages/core/src/filters/FilterSystem.ts
  packages/core/src/index.ts
  packages/core/src/textures/BaseTexture.ts
  packages/core/src/textures/resources/ImageResource.ts
  packages/core/test/FilterSystem.js
  packages/graphics/src/Graphics.ts
  packages/graphics/test/index.js
  packages/interaction/src/InteractionManager.ts
  packages/sprite-tiling/src/TilingSprite.ts
  packages/text-bitmap/src/BitmapText.ts
  packages/text-bitmap/src/BitmapTextStyle.ts
Labels: ✅ Ready To Merge

#7062 [Fix]: Make renderer use alpha in main framebuffer by default
  packages/core/src/AbstractRenderer.ts
  packages/core/src/Renderer.ts
  packages/core/src/autoDetectRenderer.ts
  packages/settings/src/settings.ts
Labels: ✅ Ready To Merge

#7067 Deprecates transparent Option
  packages/app/src/Application.ts
  packages/canvas/canvas-renderer/src/CanvasRenderer.ts
  packages/core/src/AbstractRenderer.ts
  packages/core/src/Renderer.ts
  packages/core/src/autoDetectRenderer.ts
  packages/settings/src/settings.ts
Labels: ✅ Ready To Merge

#7065 Add strict engines support
  .npmrc
  package.json
Labels: ✅ Ready To Merge

#7068 FAIL_IF_MAJOR_PERFORMANCE_CAVEAT switched to false by default
  packages/utils/src/settings.ts
Labels: ✅ Ready To Merge

#7072 Fix CanvasRenderer support for backgroundAlpha
  packages/canvas/canvas-renderer/src/CanvasRenderer.ts
Labels: ✅ Ready To Merge

#7074 Fix: Clear full texture in filter system
  packages/core/src/filters/FilterSystem.ts
Labels: ✅ Ready To Merge, 🔥 High Priority

#7084 GraphicsGeometry JSDoc function signature
  packages/graphics/src/GraphicsGeometry.ts
Labels: ✅ Ready To Merge

#7083 Update README.md
  packages/runner/README.md
Labels: ✅ Ready To Merge

#7082 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: ✅ Ready To Merge

#7081 Fix fillGradientStops descending ordered
  packages/text/src/Text.ts
Labels: ✅ Ready To Merge

#7085 FilterSystem JSDoc function signature
  packages/core/src/filters/FilterSystem.ts
Labels: ✅ Ready To Merge

#7086 Accessibility package errata
  packages/accessibility/package.json
  packages/accessibility/src/AccessibilityManager.ts
Labels: ✅ Ready To Merge

#7087 Basis package jsdoc
  packages/basis/src/BasisLoader.ts
  packages/basis/src/TranscoderWorkerWrapper.ts
Labels: ✅ Ready To Merge

#7088 Core package jsdoc
  packages/core/src/batch/BatchShaderGenerator.ts
  packages/core/src/filters/Filter.ts
  packages/core/src/fragments/index.ts
  packages/core/src/framebuffer/Framebuffer.ts
  packages/core/src/geometry/GeometrySystem.ts
  packages/core/src/shader/ShaderSystem.ts
  packages/core/src/textures/TextureGCSystem.ts
Labels: ✅ Ready To Merge

#7089 Display package jsdoc
  packages/display/src/Container.ts
  packages/display/src/DisplayObject.ts
Labels: ✅ Ready To Merge

#7090 Graphics package jsdoc
  packages/graphics/src/Graphics.ts
  packages/graphics/src/styles/FillStyle.ts
  packages/graphics/src/utils/buildLine.ts
Labels: ✅ Ready To Merge

#7091 Interaction package jsdoc
  packages/interaction/src/InteractionManager.ts
Labels: ✅ Ready To Merge

#7092 Filter package jsdoc
  packages/filters/filter-blur/src/BlurFilter.ts
  packages/filters/filter-blur/src/BlurFilterPass.ts
Labels: ✅ Ready To Merge

#7078 Revert #6869
  packages/canvas/canvas-sprite-tiling/package.json
  packages/canvas/canvas-sprite-tiling/src/TilingSprite.ts
Labels: 🔥 High Priority

#7050 [Fix]: Filter system should work in world space and then restore projection transform.
  packages/core/src/filters/FilterState.ts
  packages/core/src/filters/FilterSystem.ts
  packages/core/src/renderTexture/RenderTextureSystem.ts
  packages/core/test/FilterSystem.js
  packages/core/test/MaskSystem.js
Labels: ✅ Ready To Merge, 🔥 High Priority, 🕷 Bug

#7097 Feature/buffer type
  packages/constants/src/index.ts
  packages/core/src/geometry/Buffer.ts
  packages/core/src/geometry/BufferSystem.ts
  packages/core/src/geometry/Geometry.ts
Labels: ✅ Ready To Merge

#7100 Fix tempRect x,y
  packages/core/src/filters/FilterSystem.ts
Labels: ✅ Ready To Merge

#7093 Fix: Geometry with different shaders leaked buffers
  packages/core/src/geometry/GeometrySystem.ts
  packages/core/test/Geometry.js
Labels: ✅ Ready To Merge, 🔥 High Priority, 🕷 Bug

#7075 Improve CLEAR_MODES docs
  packages/constants/src/index.ts
  packages/core/src/filters/FilterSystem.ts
  packages/core/test/FilterSystem.js
Labels: ✅ Ready To Merge

#7108 Fix bug with TilingSpriteRenderer reseting default UVs
  packages/sprite-tiling/src/TilingSpriteRenderer.ts
Labels: ✅ Ready To Merge

#7105 Fix: TilingSprite uvRespectAnchor = false mode.
  packages/canvas/canvas-sprite-tiling/src/TilingSprite.ts
  packages/sprite-tiling/src/TilingSprite.ts
Labels: ✅ Ready To Merge, 🔥 High Priority
