Repository pixijs/pixijs, pull requests merged in 2020-03, with the labels that each got.

#6470 Fixes incorrect mentions of deprecated namespaces
  packages/core/src/Renderer.ts
  packages/prepare/test/BasePrepare.js
  packages/prepare/test/CountLimiter.js
  packages/prepare/test/Prepare.js
  packages/text/src/TextStyle.ts
  packages/ticker/src/const.ts
Labels: Domain: Documentation, Version: v5.x

#6467 V4 backport localbounds
  src/core/display/Bounds.js
  src/core/display/Container.js
  src/core/display/DisplayObject.js
  src/core/graphics/Graphics.js
  src/extras/cacheAsBitmap.js
  test/core/Container.js
Labels: Plugin: Bounds, Version: v4.x

#6489 Any reference to scaleModes is done via using the enums setup
  packages/canvas/canvas-graphics/src/Graphics.js
  packages/core/src/AbstractRenderer.ts
  packages/core/src/framebuffer/Framebuffer.ts
  packages/core/src/textures/TextureSystem.ts
Labels: Version: v5.x
