Repository pixijs/pixijs, pull requests merged in 2020-06, with the labels that each got.

#6655 convert unsafe eval to TypeScript
  packages/unsafe-eval/package.json
  packages/unsafe-eval/src/bundle.ts
  packages/unsafe-eval/src/index.ts
  packages/unsafe-eval/src/install.ts
  packages/unsafe-eval/src/syncUniforms.js
  packages/unsafe-eval/src/syncUniforms.ts
Labels: ✅ Ready To Merge

#6666 convert canvas text to TypeScript
  packages/canvas/canvas-text/src/Text.ts
  packages/canvas/canvas-text/src/index.ts
  packages/text/src/Text.ts
Labels: ✅ Ready To Merge

#6675 Bugfix/polygon offset fix
  packages/core/src/state/StateSystem.ts
Labels: ✅ Ready To Merge, 🕷 Bug

#6673 Migrated bundles to TypeScript
  bundles/pixi.js-legacy/src/index.ts
  bundles/pixi.js/src/index.ts
  bundles/pixi.js/src/useDeprecated.ts
  packages/canvas/canvas-renderer/src/CanvasRenderer.ts
  packages/core/src/Renderer.ts
  packages/spritesheet/src/SpritesheetLoader.ts
  packages/text-bitmap/src/BitmapText.ts
  packages/text-bitmap/src/index.ts
  rollup.config.js
  tsconfig.json
Labels: ✅ Ready To Merge

#6693 Remove old unnecessary eslint rule
  packages/core/src/AbstractRenderer.ts
  packages/core/src/filters/Filter.ts
  packages/core/src/state/State.ts
  packages/core/src/textures/Texture.ts
  packages/core/src/textures/TextureMatrix.ts
  packages/core/src/textures/resources/VideoResource.ts
  packages/display/src/Container.ts
  packages/display/src/DisplayObject.ts
  packages/filters/filter-alpha/src/AlphaFilter.ts
  packages/filters/filter-blur/src/BlurFilter.ts
  packages/filters/filter-blur/src/BlurFilterPass.ts
  packages/filters/filter-color-matrix/src/ColorMatrixFilter.ts
  packages/filters/filter-displacement/src/DisplacementFilter.ts
  packages/filters/filter-noise/src/NoiseFilter.ts
  packages/interaction/src/InteractionTrackingData.ts
  packages/math/src/ObservablePoint.ts
  packages/math/src/Transform.ts
  packages/mesh-extras/src/NineSlicePlane.ts
  packages/particles/src/ParticleContainer.ts
  packages/sprite-animated/src/AnimatedSprite.ts
  packages/sprite-tiling/src/TilingSprite.ts
  packages/sprite/src/Sprite.ts
  packages/text-bitmap/src/BitmapText.ts
  packages/text/src/Text.ts
  packages/text/src/TextStyle.ts
  packages/ticker/src/Ticker.ts
  packages/utils/src/media/CanvasRenderTarget.ts
Labels: ✅ Ready To Merge

#6694 Formalize the Spritesheet format in TypeScript
  packages/core/src/textures/Texture.ts
  packages/math/src/IPoint.ts
  packages/spritesheet/src/Spritesheet.ts
Labels: ✅ Ready To Merge

#6696 Remove uses of ts-ignore in canvasUtils and canvas-graphics
  packages/canvas/canvas-graphics/src/Graphics.ts
  packages/canvas/canvas-renderer/src/canvasUtils.ts
Labels: ✅ Ready To Merge

#6697 Improves unused-vars usage, removes inline exceptions
  .eslintrc.json
  packages/canvas/canvas-display/src/Container.ts
  packages/canvas/canvas-display/src/DisplayObject.ts
  packages/core/src/batch/ObjectRenderer.ts
  packages/core/src/filters/Filter.ts
  packages/core/src/projection/ProjectionSystem.ts
  packages/core/src/textures/resources/Resource.ts
  packages/core/src/textures/resources/VideoResource.ts
  packages/display/src/Container.ts
  packages/display/src/DisplayObject.ts
  packages/graphics/src/utils/ArcUtils.ts
  packages/text/src/TextMetrics.ts
Labels: ✅ Ready To Merge

#6699 Converts generic string-map types to Dict typing in utils
  packages/core/src/filters/Filter.ts
  packages/core/src/geometry/Geometry.ts
  packages/core/src/geometry/GeometrySystem.ts
  packages/core/src/geometry/utils/interleaveTypedArrays.ts
  packages/core/src/geometry/utils/setVertexAttribArrays.ts
  packages/core/src/shader/GLProgram.ts
  packages/core/src/shader/Shader.ts
  packages/core/src/shader/ShaderSystem.ts
  packages/core/src/shader/UniformGroup.ts
  packages/core/src/shader/utils/compileProgram.ts
  packages/core/src/shader/utils/generateUniformsSync.ts
  packages/core/src/shader/utils/mapSize.ts
  packages/core/src/shader/utils/mapType.ts
  packages/core/src/textures/resources/VideoResource.ts
  packages/display/src/DisplayObject.ts
  packages/utils/src/logging/deprecation.ts
Labels: ✅ Ready To Merge

#6692 Add IBatchableElement to AbstractBatchRenderer
  packages/core/src/batch/AbstractBatchRenderer.ts
Labels: ✅ Ready To Merge

#6695 Remove use of ts-ignore in TextFormat
  packages/text-bitmap/src/formats/TextFormat.ts
  packages/text-bitmap/src/formats/XMLFormat.ts
Labels: ✅ Ready To Merge

#6698 Replace any with unknown in resource test functions
  packages/core/src/textures/resources/BufferResource.ts
  packages/core/src/textures/resources/CanvasResource.ts
  packages/core/src/textures/resources/CubeResource.ts
  packages/core/src/textures/resources/ImageBitmapResource.ts
  packages/core/src/textures/resources/ImageResource.ts
  packages/core/src/textures/resources/Resource.ts
  packages/core/src/textures/resources/SVGResource.ts
  packages/core/src/textures/resources/VideoResource.ts
  packages/core/src/textures/resources/autoDetectResource.ts
  packages/core/test/autoDetectResource.js
Labels: ✅ Ready To Merge

#6687 Provide a convenience Texture API to handle invalid URLs more effectively
  packages/core/src/textures/Texture.ts
  packages/core/test/Texture.js
Labels: ✅ Ready To Merge

#6703 Fixes broken generated typings
  packages/text-bitmap/src/BitmapFont.ts
  types/events.d.ts
Labels: ✅ Ready To Merge

#6705 Remove the use of Function as a type
  packages/core/src/shader/ShaderSystem.ts
  packages/core/src/shader/UniformGroup.ts
  packages/core/src/shader/utils/generateUniformsSync.ts
  packages/core/src/textures/resources/SVGResource.ts
Labels: ✅ Ready To Merge

#6706 Fix linting issues with InteractionManager
  packages/interaction/src/InteractionManager.ts
Labels: ✅ Ready To Merge

#6707 Remove all remaining instances of @ts-ignore
  packages/mesh/src/Mesh.ts
  packages/mesh/src/MeshBatchUvs.ts
  packages/mesh/src/MeshGeometry.ts
  packages/mesh/src/MeshMaterial.ts
  packages/prepare/src/BasePrepare.ts
  packages/sprite/src/Sprite.ts
  packages/utils/src/index.ts
Labels: ✅ Ready To Merge

#6708 Standardize the use of setter types
  packages/core/src/AbstractRenderer.ts
  packages/core/src/filters/Filter.ts
  packages/core/src/state/State.ts
  packages/core/src/textures/Texture.ts
  packages/core/src/textures/resources/VideoResource.ts
  packages/display/src/Container.ts
  packages/display/src/DisplayObject.ts
  packages/filters/filter-alpha/src/AlphaFilter.ts
  packages/filters/filter-blur/src/BlurFilter.ts
  packages/filters/filter-blur/src/BlurFilterPass.ts
  packages/filters/filter-color-matrix/src/ColorMatrixFilter.ts
  packages/filters/filter-displacement/src/DisplacementFilter.ts
  packages/filters/filter-noise/src/NoiseFilter.ts
  packages/graphics/src/Graphics.ts
  packages/interaction/src/InteractionManager.ts
  packages/interaction/src/InteractionTrackingData.ts
  packages/interaction/src/interactiveTarget.ts
  packages/math/src/ObservablePoint.ts
  packages/math/src/Transform.ts
  packages/mesh-extras/src/NineSlicePlane.ts
  packages/mesh-extras/src/SimpleMesh.ts
  packages/mesh-extras/src/SimplePlane.ts
  packages/mesh/src/Mesh.ts
  packages/mesh/src/MeshMaterial.ts
  packages/particles/src/ParticleContainer.ts
  packages/sprite-animated/src/AnimatedSprite.ts
  packages/sprite-tiling/src/TilingSprite.ts
  packages/sprite/src/Sprite.ts
  packages/text-bitmap/src/BitmapFont.ts
  packages/text-bitmap/src/BitmapText.ts
  packages/text/src/Text.ts
  packages/text/src/TextMetrics.ts
  packages/text/src/TextStyle.ts
  packages/ticker/src/Ticker.ts
Labels: ✅ Ready To Merge

#6435 Cubemap renderTexture support
  packages/core/src/framebuffer/FramebufferSystem.ts
  packages/core/src/textures/BaseTexture.ts
  packages/core/src/textures/TextureSystem.ts
  packages/core/src/textures/resources/AbstractMultiResource.ts
  packages/core/src/textures/resources/ArrayResource.ts
  packages/core/src/textures/resources/CubeResource.ts
  packages/core/src/textures/resources/index.ts
  packages/core/test/CubeResource.js
  packages/display/src/Bounds.ts
Labels: ⏰ Future Work, ✅ Ready To Merge

#6450 Make core independent from display
  packages/accessibility/src/AccessibilityManager.ts
  packages/canvas/canvas-renderer/src/CanvasRenderer.ts
  packages/core/package.json
  packages/core/src/AbstractRenderer.ts
  packages/core/src/Renderer.ts
  packages/display/src/DisplayObject.ts
  packages/display/test/DisplayObject.js
  packages/interaction/src/InteractionManager.ts
  packages/mixin-cache-as-bitmap/src/index.ts
Labels: ✅ Ready To Merge

#6710 Upgrade ESLint & TypeScript ESLint Plugins
  .eslintrc.json
  bundles/pixi.js/src/useDeprecated.ts
  package-lock.json
  package.json
  packages/core/src/batch/ObjectRenderer.ts
  packages/core/src/context/ContextSystem.ts
  packages/core/src/shader/ShaderSystem.ts
  packages/core/src/shader/utils/mapType.ts
  packages/core/src/shader/utils/uniformParsers.ts
  packages/core/src/textures/TextureGCSystem.ts
  packages/display/src/DisplayObject.ts
  packages/filters/filter-blur/src/generateBlurFragSource.ts
  packages/graphics/src/utils/buildCircle.ts
  packages/mesh/src/MeshMaterial.ts
  packages/prepare/src/BasePrepare.ts
  packages/runner/src/Runner.ts
  packages/spritesheet/src/Spritesheet.ts
  packages/spritesheet/src/SpritesheetLoader.ts
  packages/text-bitmap/src/formats/index.ts
  packages/unsafe-eval/src/install.ts
  packages/unsafe-eval/src/syncUniforms.ts
  packages/utils/src/data/getBufferType.ts
Labels: ✅ Ready To Merge

#6713 Add option for recursive search in @pixi/mixin-get-child-by-name
  packages/mixin-get-child-by-name/global.d.ts
  packages/mixin-get-child-by-name/src/index.ts
  packages/mixin-get-child-by-name/test/index.js
Labels: ✅ Ready To Merge
