Repository pixijs/pixijs, pull requests merged in 2021-05, with the labels that each got.

#7449 Fix improper example in BitmapText
  packages/text-bitmap/src/BitmapText.ts
Labels: ✅ Ready To Merge

#7451 Make getChildByName non-optional
  packages/mixin-get-child-by-name/global.d.ts
Labels: ✅ Ready To Merge

#7458 Fix GlobalMixins to be avoid issues with strictNullChecks
  packages/canvas/canvas-display/global.d.ts
  packages/canvas/canvas-graphics/global.d.ts
  packages/canvas/canvas-mesh/global.d.ts
  packages/canvas/canvas-sprite/global.d.ts
  packages/mixin-cache-as-bitmap/global.d.ts
  packages/mixin-get-child-by-name/global.d.ts
  packages/mixin-get-global-position/global.d.ts
Labels: ✅ Ready To Merge

#7406 Fix FXAA filter
  packages/filters/filter-fxaa/src/fxaa.frag
  packages/filters/filter-fxaa/src/fxaa.vert
Labels: ✅ Ready To Merge

#7450 feat: Use Fetch+blob for ImageBitmap
  packages/core/src/textures/resources/ImageResource.ts
Labels: ✅ Ready To Merge

#7440 Add multisample shortcut and parameters
  packages/core/src/AbstractRenderer.ts
  packages/core/src/renderTexture/BaseRenderTexture.ts
  packages/core/src/renderTexture/RenderTexture.ts
  packages/core/src/textures/BaseTexture.ts
Labels: ✅ Ready To Merge

#7471 Fixes TilingSprite.from usage with a Texture parameter
  packages/sprite-tiling/src/TilingSprite.ts
  packages/sprite-tiling/test/index.js
Labels: ✅ Ready To Merge

#7465 Do npm publish on GitHub Actions
  .github/workflows/nodejs.yml
  package.json
  scripts/tag-release.sh
Labels: ✅ Ready To Merge

#7476 Fixes unit-test failures from npm@7.12.0
  .github/workflows/nodejs.yml
Labels: ✅ Ready To Merge, 🔥 High Priority

#7472 Update webdoc dependencies
  package-lock.json
  package.json
Labels: ✅ Ready To Merge

#7474 Add missing dependency to compressed-textures
  packages/compressed-textures/package.json
Labels: ✅ Ready To Merge

#7463 Fix Mesh.canvasPadding
  packages/canvas/canvas-mesh/src/CanvasMeshRenderer.ts
Labels: ✅ Ready To Merge

#7439 Ceil height in TextMetrics.measureFont()
  packages/text/src/TextMetrics.ts
Labels: ✅ Ready To Merge

#7434 Fix incorrect bounds for drawPolygon with lineAlignment lower than 0.5
  packages/graphics/src/GraphicsGeometry.ts
  packages/graphics/src/utils/isPolygonClockwise.ts
  packages/graphics/test/index.js
Labels: ✅ Ready To Merge

#7491 Set _isConnectedToTicker to false when disposing VideoResource
  packages/core/src/textures/resources/VideoResource.ts
Labels: ✅ Ready To Merge

#7492 Fix UBO handling mat3 Matrix uniforms
  packages/core/src/shader/utils/uniformParsers.ts
Labels: ✅ Ready To Merge

#7489 Remove duplicate lines from BitmapText's drawGlyph
  packages/text-bitmap/src/utils/drawGlyph.ts
Labels: ✅ Ready To Merge

#7493 Fix geometry merging when geometries are of different sizes
  packages/core/src/geometry/Geometry.ts
  packages/core/test/Geometry.js
Labels: ✅ Ready To Merge

#7478 Fix SVG validation by supporting XML prolog and leading comments
  packages/core/src/textures/resources/SVGResource.ts
  packages/core/test/SVGResource.js
Labels: ✅ Ready To Merge, 🕷 Bug

#7487 Fix docs removeEventListener & addEventListener
  packages/events/src/FederatedEventTarget.ts
Labels: ✅ Ready To Merge

#7485 Fix filter-system frame rounding precision-issue
  packages/core/src/filters/FilterSystem.ts
  packages/core/test/FilterSystem.js
Labels: ✅ Ready To Merge

#7438 Fix default type and internalFormat of GLTexture
  packages/core/src/textures/GLTexture.ts
Labels: ✅ Ready To Merge

#7442 Round gl.scissor and gl.viewport arguments
  packages/core/src/framebuffer/FramebufferSystem.ts
  packages/core/src/mask/ScissorSystem.ts
  packages/core/src/renderTexture/RenderTextureSystem.ts
  packages/core/test/MaskSystem.js
Labels: ✅ Ready To Merge

#7501 Fix DisplayObject's parent type as Container
  packages/display/src/DisplayObject.ts
Labels: ✅ Ready To Merge

#7452 InteractionManager: replace useCapture with options
  packages/interaction/src/InteractionManager.ts
Labels: ✅ Ready To Merge

#7479 Fix lineWidth calculation in BitmapText#updateText
  packages/text-bitmap/src/BitmapText.ts
  packages/text-bitmap/test/BitmapText.js
Labels: ✅ Ready To Merge, 🕷 Bug

#7441 Multisampling and cacheAsBitmap
  packages/mixin-cache-as-bitmap/global.d.ts
  packages/mixin-cache-as-bitmap/src/index.ts
Labels: ✅ Ready To Merge
