Repository pixijs/pixijs, pull requests merged in 2021-03, with the labels that each got.

#7271 Fix missing removeEventListener in ResizePlugin
  packages/app/src/ResizePlugin.ts
Labels: ✅ Ready To Merge

#7269 Remove System inheritance
  packages/core/src/ISystem.ts
  packages/core/src/Renderer.ts
  packages/core/src/System.ts
  packages/core/src/batch/BatchSystem.ts
  packages/core/src/context/ContextSystem.ts
  packages/core/src/filters/FilterSystem.ts
  packages/core/src/framebuffer/FramebufferSystem.ts
  packages/core/src/geometry/GeometrySystem.ts
  packages/core/src/index.ts
  packages/core/src/mask/AbstractMaskSystem.ts
  packages/core/src/mask/MaskSystem.ts
  packages/core/src/projection/ProjectionSystem.ts
  packages/core/src/renderTexture/RenderTextureSystem.ts
  packages/core/src/shader/ShaderSystem.ts
  packages/core/src/state/StateSystem.ts
  packages/core/src/textures/TextureGCSystem.ts
  packages/core/src/textures/TextureSystem.ts
Labels: ✅ Ready To Merge

#7274 Respect projection destinationFrame
  packages/mixin-cache-as-bitmap/src/index.ts
  packages/mixin-cache-as-bitmap/test/index.js
Labels: ✅ Ready To Merge

#7286 Remove utils dependency to Node types
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/network/determineCrossOrigin.ts
  packages/utils/src/url.ts
Labels: ✅ Ready To Merge

#7289 Fix more documentation typos
  packages/runner/src/Runner.ts
Labels: ✅ Ready To Merge

#7291 Workaround webdoc parsing crash
  .eslintrc.json
  packages/core/src/batch/BatchSystem.ts
  packages/core/src/context/ContextSystem.ts
  packages/core/src/filters/FilterSystem.ts
  packages/core/src/framebuffer/FramebufferSystem.ts
  packages/core/src/geometry/GeometrySystem.ts
  packages/core/src/mask/AbstractMaskSystem.ts
  packages/core/src/mask/MaskSystem.ts
  packages/core/src/projection/ProjectionSystem.ts
  packages/core/src/renderTexture/RenderTextureSystem.ts
  packages/core/src/shader/ShaderSystem.ts
  packages/core/src/state/StateSystem.ts
  packages/core/src/textures/TextureGCSystem.ts
  packages/core/src/textures/TextureSystem.ts
Labels: ✅ Ready To Merge

#7273 Unbind integer textures
  packages/constants/src/index.ts
  packages/core/src/batch/AbstractBatchRenderer.ts
  packages/core/src/textures/GLTexture.ts
  packages/core/src/textures/TextureSystem.ts
  packages/core/test/TextureSystem.js
Labels: ✅ Ready To Merge

#7297 Remove Inch CI support for docs coverage
  README.md
  inch.json
Labels: ✅ Ready To Merge

#7107 Uniform Buffer Object integration
  packages/core/src/geometry/BufferSystem.ts
  packages/core/src/index.ts
  packages/core/src/shader/GLProgram.ts
  packages/core/src/shader/Program.ts
  packages/core/src/shader/Shader.ts
  packages/core/src/shader/ShaderSystem.ts
  packages/core/src/shader/UniformGroup.ts
  packages/core/src/shader/utils/generateUniformBufferSync.ts
  packages/core/src/shader/utils/generateUniformsSync.ts
  packages/core/src/shader/utils/uniformParsers.ts
  packages/core/test/shader/UniformBuffer.js
Labels: ✅ Ready To Merge

#7300 Remove spritesheet dependency from loader, fix resources type
  packages/loaders/src/Loader.ts
  packages/loaders/src/LoaderResource.ts
  packages/spritesheet/global.d.ts
  packages/spritesheet/src/Spritesheet.ts
Labels: ✅ Ready To Merge

#7268 Shader compiling optimization and better shader debugging
  package-lock.json
  packages/core/src/filters/Filter.ts
  packages/core/src/filters/FilterSystem.ts
  packages/core/src/geometry/GeometrySystem.ts
  packages/core/src/shader/Program.ts
  packages/core/src/shader/Shader.ts
  packages/core/src/shader/ShaderSystem.ts
  packages/core/src/shader/utils/compileProgram.ts
  packages/core/src/shader/utils/compileShader.ts
  packages/core/src/shader/utils/getAttributeData.ts
  packages/core/src/shader/utils/getUniformData.ts
  packages/core/src/shader/utils/index.ts
  packages/core/src/shader/utils/logProgramError.ts
Labels: ✅ Ready To Merge

#7150 Added support of line alignment on CanvasRenderer
  packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.ts
  packages/canvas/canvas-graphics/src/utils/PolygonUtils.ts
Labels: ✅ Ready To Merge

#7311 Fix Mesh render crash due new behaviour of ShaderSystem
  packages/mesh/src/Mesh.ts
Labels: ✅ Ready To Merge, 🔥 High Priority, 🕷 Bug

#7213 Federated Events API (v6+7)
  package-lock.json
  packages/core/src/Renderer.ts
  packages/display/src/DisplayObject.ts
  packages/events/README.md
  packages/events/global.d.ts
  packages/events/package.json
  packages/events/src/EventBoundary.ts
  packages/events/src/EventSystem.ts
  packages/events/src/FederatedEvent.ts
  packages/events/src/FederatedEventTarget.ts
  packages/events/src/FederatedMouseEvent.ts
  packages/events/src/FederatedPointerEvent.ts
  packages/events/src/FederatedWheelEvent.ts
  packages/events/src/index.ts
  packages/events/test/.eslintrc.json
  packages/events/test/EventBoundary.js
  packages/events/test/EventSystem.js
  packages/events/test/index.js
  packages/interaction/global.d.ts
  packages/interaction/src/InteractionManager.ts
  packages/interaction/src/interactiveTarget.ts
Labels: ✅ Ready To Merge

#7314 Fix wrong syncUniform creation due to loop in our logic
  packages/mesh/src/Mesh.ts
Labels: 🔥 High Priority, 🕷 Bug

#7318 Support running GitHub Actions on Forks and other workflow cleanup (take 2)
  .github/workflows/nodejs.yml
Labels: ✅ Ready To Merge

#7322 feat(DisplayObject): Add `destroyed` event
  packages/display/src/DisplayObject.ts
  packages/display/test/DisplayObject.js
Labels: ✅ Ready To Merge

#7315 Remove deprecation warnings in tests
  packages/mesh-extras/test/SimplePlane.js
  packages/sprite/test/Sprite.js
Labels: ✅ Ready To Merge

#7319 Fix video texture not working in SimplePlane
  packages/mesh-extras/src/SimplePlane.ts
Labels: ✅ Ready To Merge

#7326 Fix url package types for API extractor
  packages/utils/src/index.ts
  packages/utils/src/network/determineCrossOrigin.ts
  packages/utils/src/url.ts
Labels: ✅ Ready To Merge, 🔥 High Priority

#7327 Fix BitmapFont destroying respects external Textures
  packages/text-bitmap/src/BitmapFont.ts
  packages/text-bitmap/src/BitmapFontLoader.ts
  packages/text-bitmap/test/BitmapFontLoader.js
Labels: ✅ Ready To Merge

#7333 Upgrade @pixi-build-tools/api-extractor-lerna-monorepo to 1.0.3
  package-lock.json
  package.json
Labels: ✅ Ready To Merge

#7334 Upgrade floss and Electron dependencies for testing
  package-lock.json
  package.json
Labels: ✅ Ready To Merge

#7336 Fix Graphics currentPath access (protected to readonly)
  packages/graphics/src/Graphics.ts
Labels: ✅ Ready To Merge

#7348 Remove app dependency from ticker
  packages/ticker/src/TickerPlugin.ts
Labels: ✅ Ready To Merge

#7338 Fix Internal Format Constants for Compressed Textures
  packages/compressed-textures/src/const.ts
Labels: ✅ Ready To Merge

#7337 Fix typo in the names of rect drawing extras
  packages/graphics-extras/src/drawChamferRect.ts
  packages/graphics-extras/src/drawFilletRect.ts
Labels: ✅ Ready To Merge

#7350 Fix wheel events not getting a nativeEvent
  packages/events/src/EventSystem.ts
Labels: ✅ Ready To Merge

#7096 Add new BufferSystem to Renderer
  .eslintrc.json
  packages/basis/src/Basis.ts
  packages/constants/src/index.ts
  packages/core/src/Renderer.ts
  packages/core/src/geometry/Buffer.ts
  packages/core/src/geometry/BufferSystem.ts
  packages/core/src/geometry/Geometry.ts
  packages/core/src/geometry/GeometrySystem.ts
  packages/core/src/index.ts
  packages/core/src/shader/GLProgram.ts
  packages/core/src/shader/Program.ts
  packages/core/src/shader/Shader.ts
  packages/core/src/shader/ShaderSystem.ts
  packages/core/src/shader/UniformGroup.ts
  packages/core/src/shader/utils/generateUniformBufferSync.ts
  packages/core/src/shader/utils/generateUniformsSync.ts
  packages/core/src/shader/utils/getUniformData.ts
  packages/core/src/shader/utils/logProgramError.ts
  packages/core/src/shader/utils/uniformParsers.ts
  packages/core/test/shader/UniformBuffer.js
Labels: ✅ Ready To Merge

#7222 add support for R32F
  packages/constants/src/index.ts
  packages/core/src/textures/TextureSystem.ts
  packages/core/test/TextureSystem.js
Labels: ✅ Ready To Merge

#7353 Fix deprecation for System class
  packages/core/src/ISystem.ts
Labels: ✅ Ready To Merge

#7354 Populate the Loader resource with Texture objects for basis and compressed-textures
  packages/basis/src/BasisLoader.ts
  packages/compressed-textures/src/loaders/CompressedTextureLoader.ts
  packages/compressed-textures/src/loaders/DDSLoader.ts
  packages/compressed-textures/src/loaders/KTXLoader.ts
  packages/compressed-textures/src/loaders/registerCompressedTextures.ts
Labels: ✅ Ready To Merge

#7357 Remove Lerna bootstrap, replace with npm v7 workspaces
  .github/workflows/nodejs.yml
  lerna.json
  package-lock.json
  package.json
Labels: ✅ Ready To Merge
