Repository pixijs/pixijs, pull requests merged in 2022-10, with the labels that each got.

#8685 Fixed README webpack link formatting
  bundles/pixi.js-legacy/README.md
  bundles/pixi.js/README.md
Labels: ✅ Ready To Merge

#8691 Fix ASTC Resolving for basis
  packages/basis/src/Basis.ts
  packages/basis/src/loader/BasisParser.ts
  packages/compressed-textures/src/const.ts
Labels: ✅ Ready To Merge

#8541 Fix createImageBitmap with null alphaMode
  packages/core/src/textures/resources/ImageResource.ts
Labels: ✅ Ready To Merge

#8709 Fix `fromBuffer`
  packages/core/src/textures/BaseTexture.ts
Labels: ✅ Ready To Merge

#8699 Fix bitmapText frag alpha
  packages/text-bitmap/src/BitmapText.ts
  packages/text-bitmap/src/shader/msdf.frag
Labels: ✅ Ready To Merge

#8713 Fix dereferencing textures for BitmapText
  packages/text-bitmap/src/BitmapText.ts
Labels: ✅ Ready To Merge

#8719 Recycle PageMeshData when BitmapText is destroyed
  packages/text-bitmap/src/BitmapText.ts
Labels: ✅ Ready To Merge

#8723 Fix doc formatting warnings with TransformFeedback
  .eslintrc.json
  packages/core/src/transformFeedback/TransformFeedback.ts
  packages/core/src/transformFeedback/TransformFeedbackSystem.ts
Labels: ✅ Ready To Merge

#8724 Fix settings type error with v7.0.0-beta.2
  package-lock.json
  packages/settings/package.json
Labels: ✅ Ready To Merge

#8726 Fix ICanvas type issue in v7.0.0-beta.2
  packages/settings/src/ICanvas.ts
Labels: ✅ Ready To Merge

#8727 Adds more user-friendly background option
  packages/app/src/Application.ts
  packages/canvas-renderer/src/CanvasRenderer.ts
  packages/core/src/IRenderer.ts
  packages/core/src/Renderer.ts
  packages/core/src/autoDetectRenderer.ts
  packages/core/src/background/BackgroundSystem.ts
  packages/core/test/Renderer.tests.ts
  packages/settings/src/settings.ts
  packages/utils/src/color/hex.ts
  packages/utils/test/utils.tests.ts
Labels: ✅ Ready To Merge

#8717 Replaces mandatory console banner with opt-in debug info
  packages/app/src/Application.ts
  packages/app/test/Application.tests.ts
  packages/canvas-extract/test/CanvasExtract.tests.ts
  packages/canvas-renderer/src/CanvasRenderer.ts
  packages/core/src/IRenderer.ts
  packages/core/src/Renderer.ts
  packages/core/src/autoDetectRenderer.ts
  packages/core/src/startup/StartupSystem.ts
  packages/core/test/BatchRenderer.tests.ts
  packages/core/test/Renderer.tests.ts
  packages/core/test/Shader.tests.ts
  packages/core/test/ShaderSystem.tests.ts
  packages/core/test/UniformBuffer.tests.ts
  packages/extract/test/Extract.tests.ts
  packages/graphics/test/Graphics.tests.ts
  packages/mesh-extras/test/NineSlicePlane.tests.ts
  packages/mesh-extras/test/SimpleMesh.tests.ts
  packages/mesh-extras/test/SimplePlane.tests.ts
  packages/mesh-extras/test/SimpleRope.tests.ts
  packages/mesh/test/Mesh.tests.ts
  packages/particle-container/test/ParticleRenderer.tests.ts
  packages/settings/src/settings.ts
  packages/text/test/Text.tests.ts
  packages/utils/src/browser/hello.ts
Labels: ✅ Ready To Merge

#8728 Add removeFromParent method for DisplayObject
  packages/display/src/DisplayObject.ts
  packages/display/test/DisplayObject.tests.ts
Labels: ✅ Ready To Merge

#8729 Modernize documentation examples in utils
  packages/utils/src/color/hex.ts
  packages/utils/src/index.ts
Labels: ✅ Ready To Merge

#8730 Additional optional chaining and startsWith/includes
  bundles/pixi.js-node/src/adapter/NodeCanvasElement.ts
  bundles/pixi.js-node/src/adapter/NodeCanvasResource.ts
  bundles/pixi.js-node/src/adapter/loadNodeBitmapFont.ts
  packages/assets/src/loader/parsers/textures/loadTexture.ts
  packages/canvas-renderer/src/canvasUtils.ts
Labels: ✅ Ready To Merge

#8736 Add avif image support for Loader
  packages/loaders/src/LoaderResource.ts
Labels: ✅ Ready To Merge

#8734 Simplify conditions for identifying playing video
  packages/core/src/textures/resources/VideoResource.ts
Labels: ✅ Ready To Merge

#8742 Clarifying string2hex and rgb2hex examples in documentation (#8024)
  packages/utils/src/color/hex.ts
Labels: ✅ Ready To Merge

#7619 Allow non-RGBA8 multisampled framebuffers
  packages/core/src/framebuffer/FramebufferSystem.ts
  packages/core/test/FramebufferSystem.tests.ts
  packages/core/test/RenderTexture.tests.ts
Labels: ✅ Ready To Merge

#8737 Fix some Webdoc issues
  package-lock.json
  package.json
  packages/canvas-graphics/src/utils/PolygonUtils.ts
  packages/core/src/index.ts
  packages/events/src/EventSystem.ts
  packages/utils/src/url.ts
Labels: ✅ Ready To Merge

#8312 Don't render rectangles with negative width/height
  packages/graphics/src/utils/buildRectangle.ts
Labels: ✅ Ready To Merge

#8750 Chore: Update document for v6.x
  README.md
  packages/assets/src/Assets.ts
  packages/events/src/EventSystem.ts
  packages/text/src/TextMetrics.ts
  packages/utils/src/media/trimCanvas.ts
Labels: ✅ Ready To Merge

#7718 Stricter typings for event emitter and federated events
  package-lock.json
  packages/display/src/DisplayObject.ts
  packages/events/global.d.ts
  packages/events/src/FederatedEventMap.ts
  packages/events/src/FederatedEventTarget.ts
  packages/events/src/index.ts
  packages/utils/package.json
Labels: ✅ Ready To Merge

#8731 Fix: set current shader null when it is destroyed.
  packages/core/src/shader/Shader.ts
  packages/core/src/shader/ShaderSystem.ts
  packages/core/test/ShaderSystem.tests.ts
Labels: ✅ Ready To Merge

#8764 Fix gl.readPixels failure in tests
  packages/core/test/RenderTexture.tests.ts
Labels: ✅ Ready To Merge

#8763 Missing peers causing unnecessary bundling
  package-lock.json
  package.json
  packages/app/package.json
  packages/display/package.json
  packages/filter-blur/package.json
  packages/mixin-cache-as-bitmap/package.json
  packages/settings/package.json
  scripts/bundleCheck.ts
Labels: 🔥 High Priority, ✅ Ready To Merge

#8768 Auto update BitmapText when its font is replaced
  packages/text-bitmap/src/BitmapText.ts
  packages/text-bitmap/test/BitmapText.tests.ts
Labels: ✅ Ready To Merge

#8770 Add missing events to FederatedEventMap
  packages/events/src/FederatedEventMap.ts
Labels: ✅ Ready To Merge

#8771 Fix round line join on 180 degree corner
  packages/graphics/src/utils/buildLine.ts
  packages/graphics/test/Graphics.tests.ts
Labels: ✅ Ready To Merge

#8777 Render Immediate After Resize
  packages/app/src/ResizePlugin.ts
Labels: ✅ Ready To Merge

#8782 Chore: Automatically upload assets to release
  .github/workflows/nodejs.yml
Labels: ✅ Ready To Merge

#8784 Decouple events from display
  packages/display/global.d.ts
  packages/display/src/DisplayObject.ts
  packages/events/global.d.ts
Labels: ✅ Ready To Merge

#8785 Allow mipmap, scaleMode an other BaseTexture options with BitmapFonts
  packages/text-bitmap/src/BitmapFont.ts
Labels: ✅ Ready To Merge

#8795 Fix publishing unsafe-eval package
  packages/core/package.json
  packages/unsafe-eval/package.json
  packages/unsafe-eval/src/bundle.ts
Labels: ✅ Ready To Merge

#8796 Chore: Cleanup action dependencies, remove Codecov
  .github/workflows/nodejs.yml
Labels: ✅ Ready To Merge

#8800 Convert types reference to relative path
  scripts/fixTypes.ts
Labels: ✅ Ready To Merge

#8803 Hotfix Global Types
  scripts/fixTypes.ts
Labels: 🔥 High Priority

#8790 Fixed plugins duplicating
  packages/extensions/src/index.ts
  packages/extensions/test/extensions.tests.ts
Labels: ✅ Ready To Merge
