Repository pixijs/pixijs, pull requests merged in 2022-11, with the labels that each got.

#8807 Fix compatibility between `zone.js` and `FederatedEventTarget`
  packages/events/src/FederatedEventTarget.ts
Labels: ✅ Ready To Merge

#8806 VideoResource upload fix
  packages/core/src/textures/resources/BaseImageResource.ts
Labels: ✅ Ready To Merge

#8816 Fix negative coords for roundPixels
  packages/mesh/src/Mesh.ts
  packages/sprite/src/Sprite.ts
Labels: 🛸 X-Files, ✅ Ready To Merge

#8823 Fix: Make NodeCanvasElement compatible with ICanvas
  bundles/pixi.js-node/src/adapter/NodeCanvasElement.ts
  bundles/pixi.js-node/src/adapter/adapter.ts
  bundles/pixi.js-webworker/src/adapter.ts
  packages/settings/src/ICanvas.ts
Labels: ✅ Ready To Merge

#8820 Add view type as a template for IRenderer, Application
  packages/app/src/Application.ts
  packages/core/src/IRenderer.ts
  packages/core/src/autoDetectRenderer.ts
Labels: ✅ Ready To Merge

#8828 Event emitter types improvements
  packages/display/src/DisplayObject.ts
  packages/events/src/FederatedEventMap.ts
Labels: ✅ Ready To Merge

#8826 Feature: Flag to disable texture loading in Workers
  packages/assets/src/Assets.ts
  packages/assets/src/loader/parsers/textures/index.ts
  packages/assets/src/loader/parsers/textures/loadSVG.ts
  packages/assets/src/loader/parsers/textures/loadTextures.ts
Labels: ✅ Ready To Merge

#8805 Make @pixi/unsafe-eval self-installed
  packages/core/src/index.ts
  packages/unsafe-eval/README.md
  packages/unsafe-eval/src/install.ts
Labels: ✅ Ready To Merge

#8825 Add missing resolution setter for Renderer and CanvasRenderer
  packages/canvas-renderer/src/CanvasRenderer.ts
  packages/core/src/Renderer.ts
  packages/events/src/EventSystem.ts
  packages/events/test/EventSystem.tests.ts
Labels: ✅ Ready To Merge

#8827 Add dist build for optional packages
  package.json
  packages/basis/package.json
  packages/graphics-extras/package.json
  packages/math-extras/package.json
  packages/unsafe-eval/package.json
  rollup.config.js
Labels: ✅ Ready To Merge

#8832 Chore: Update document
  packages/core/src/textures/Texture.ts
  packages/display/src/Container.ts
  packages/graphics/src/Graphics.ts
  packages/graphics/src/GraphicsGeometry.ts
Labels: ✅ Ready To Merge

#8841 Change "lib/node_modules" to "lib/external" with preserveModules
  package-lock.json
  package.json
  rollup.config.js
Labels: ✅ Ready To Merge

#8797 Add support for specifying vertex attribute divisor
  packages/core/src/geometry/Attribute.ts
  packages/core/src/geometry/GeometrySystem.ts
Labels: 🙏 Feature Request, ✅ Ready To Merge

#8835 Fix loseContext/restoreContext
  packages/core/src/context/ContextSystem.ts
  packages/core/src/framebuffer/FramebufferSystem.ts
Labels: ✅ Ready To Merge

#8846 Chore: Fix the URLs for the repo
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  bundles/pixi.js-legacy/package.json
  bundles/pixi.js-node/package.json
  bundles/pixi.js-webworker/package.json
  bundles/pixi.js/package.json
  packages/accessibility/package.json
  packages/app/package.json
  packages/assets/package.json
  packages/basis/package.json
  packages/canvas-display/package.json
  packages/canvas-extract/package.json
  packages/canvas-graphics/package.json
  packages/canvas-mesh/package.json
  packages/canvas-particle-container/package.json
  packages/canvas-prepare/package.json
  packages/canvas-renderer/package.json
  packages/canvas-sprite-tiling/package.json
  packages/canvas-sprite/package.json
  packages/canvas-text/package.json
  packages/compressed-textures/package.json
  packages/constants/package.json
  packages/core/package.json
  packages/core/src/Renderer.ts
  packages/core/src/textures/resources/ImageResource.ts
  packages/core/src/textures/resources/VideoResource.ts
  packages/display/package.json
  packages/events/package.json
  packages/extensions/package.json
  packages/extract/package.json
  packages/filter-alpha/package.json
  packages/filter-blur/package.json
  packages/filter-color-matrix/package.json
  packages/filter-displacement/package.json
  packages/filter-fxaa/package.json
  packages/filter-noise/package.json
  packages/graphics-extras/package.json
  packages/graphics/package.json
  packages/math-extras/package.json
  packages/math/package.json
  packages/mesh-extras/package.json
  packages/mesh/package.json
  packages/mixin-cache-as-bitmap/package.json
  packages/mixin-get-child-by-name/package.json
  packages/mixin-get-global-position/package.json
  packages/particle-container/package.json
  packages/prepare/package.json
  packages/runner/package.json
  packages/settings/package.json
  packages/settings/src/settings.ts
  packages/sprite-animated/package.json
  packages/sprite-tiling/package.json
  packages/sprite/package.json
  packages/spritesheet/package.json
  packages/text-bitmap/package.json
  packages/text/package.json
  packages/ticker/package.json
  packages/unsafe-eval/package.json
  packages/utils/package.json
Labels: ✅ Ready To Merge

#8842 Updating WebGLRenderingContext for node
  bundles/pixi.js-node/package.json
  bundles/pixi.js-node/src/adapter/adapter.ts
  package-lock.json
Labels: ✅ Ready To Merge

#8844 Fix culling not working with projection transforms
  packages/display/src/Container.ts
Labels: ✅ Ready To Merge

#8850 Fix typo in basis readme
  packages/basis/README.md
Labels: ✅ Ready To Merge

#8864 Fix: Jest running on Windows
  package-lock.json
  package.json
  test/jest-global-setup.ts
  test/jest-global-teardown.ts
Labels: ✅ Ready To Merge

#8865 Deprecate FILTER_* settings, move to Filter static members
  packages/core/src/filters/Filter.ts
  packages/core/src/settings.ts
  packages/filter-blur/src/BlurFilter.ts
  packages/settings/src/settings.ts
  packages/settings/test/settings.tests.ts
Labels: ✅ Ready To Merge

#8866 Chore: Cleanup useContextAlpha deprecation
  packages/app/src/Application.ts
  packages/canvas-renderer/src/CanvasRenderer.ts
  packages/core/src/Renderer.ts
  packages/core/src/context/ContextSystem.ts
  packages/settings/src/settings.ts
Labels: ✅ Ready To Merge

#8869 Deprecate GRAPHICS_CURVES, move to Graphics.curves
  packages/graphics/src/Graphics.ts
  packages/graphics/src/const.ts
  packages/graphics/src/utils/ArcUtils.ts
  packages/graphics/src/utils/BezierUtils.ts
  packages/graphics/src/utils/QuadraticUtils.ts
  packages/graphics/src/utils/buildLine.ts
  packages/graphics/test/Graphics.tests.ts
Labels: ✅ Ready To Merge

#8868 Deprecate BaseTexture-related settings to BaseTexture.defaultOptions
  packages/constants/src/index.ts
  packages/core/src/context/ContextSystem.ts
  packages/core/src/framebuffer/FramebufferSystem.ts
  packages/core/src/geometry/GeometrySystem.ts
  packages/core/src/settings.ts
  packages/core/src/shader/utils/getTestContext.ts
  packages/core/src/textures/BaseTexture.ts
  packages/settings/src/settings.ts
  packages/settings/test/settings.tests.ts
  packages/text-bitmap/src/BitmapFont.ts
Labels: ✅ Ready To Merge

#8875 Include DEBUG statements in module output
  rollup.config.js
Labels: ✅ Ready To Merge

#8877 Deprecate SPRITE_* & CAN_UPLOAD_SAME_BUFFER settings, move to BatchRenderer
  packages/core/src/batch/BatchRenderer.ts
  packages/core/src/batch/canUploadSameBuffer.ts
  packages/core/src/batch/maxRecommendedTextures.ts
  packages/core/src/settings.ts
  packages/core/test/BatchRenderer.tests.ts
  packages/core/test/Renderer.tests.ts
  packages/graphics/src/Graphics.ts
  packages/graphics/src/GraphicsGeometry.ts
  packages/settings/src/settings.ts
  packages/settings/test/settings.tests.ts
Labels: ✅ Ready To Merge

#8879 Move UPLOADS_PER_FRAME to BasePrepare
  packages/prepare/src/BasePrepare.ts
  packages/prepare/src/settings.ts
  packages/settings/src/settings.ts
Labels: ✅ Ready To Merge

#8883 Deprecate SORTABLE_CHILDREN setting, move to Container
  packages/display/src/Container.ts
  packages/display/src/settings.ts
  packages/settings/src/settings.ts
Labels: ✅ Ready To Merge

#8885 Deprecated settings.TARGET_FPMS to Ticker.targetFPMS
  packages/settings/src/settings.ts
  packages/ticker/package.json
  packages/ticker/src/Ticker.ts
  packages/ticker/src/settings.ts
Labels: ✅ Ready To Merge

#8886 Deprecate GC settings
  packages/core/src/settings.ts
  packages/core/src/textures/TextureGCSystem.ts
  packages/settings/src/settings.ts
  packages/settings/test/settings.tests.ts
Labels: ✅ Ready To Merge

#8884 Cleanup deprecation warnings, disambiguate new static settings
  package-lock.json
  packages/app/src/Application.ts
  packages/basis/src/TranscoderWorker.ts
  packages/canvas-mesh/global.d.ts
  packages/canvas-mesh/src/Mesh.ts
  packages/canvas-mesh/src/settings.ts
  packages/core/global.d.ts
  packages/core/src/batch/BatchRenderer.ts
  packages/core/src/filters/Filter.ts
  packages/core/src/settings.ts
  packages/core/src/textures/resources/VideoResource.ts
  packages/display/global.d.ts
  packages/filter-blur/src/BlurFilter.ts
  packages/prepare/global.d.ts
  packages/settings/global.d.ts
  packages/settings/src/settings.ts
  packages/sprite-animated/src/AnimatedSprite.ts
  packages/ticker/global.d.ts
  packages/utils/global.d.ts
  packages/utils/src/browser/hello.ts
Labels: ✅ Ready To Merge

#8876 Added `.on<event>` checking for display objects
  packages/events/src/EventBoundary.ts
  packages/events/src/FederatedEventTarget.ts
Labels: ✅ Ready To Merge

#8887 Add overload signatures for Assets
  bundles/pixi.js-node/src/adapter/loadNodeBitmapFont.ts
  packages/assets/src/Assets.ts
  packages/assets/src/loader/Loader.ts
  packages/assets/test/assets.tests.ts
  packages/assets/test/loader.tests.ts
  packages/compressed-textures/test/compressed-textures.tests.ts
  packages/mesh-extras/test/SimplePlane.tests.ts
  packages/mesh-extras/test/SimpleRope.tests.ts
  packages/text-bitmap/src/loadBitmapFont.ts
  packages/text-bitmap/test/BitmapFontLoader.tests.ts
Labels: ✅ Ready To Merge

#8892 Deprecate MESH_CANVAS_PADDING setting
  packages/canvas-mesh/global.d.ts
  packages/canvas-mesh/src/Mesh.ts
  packages/canvas-mesh/src/settings.ts
  packages/core/src/settings.ts
  packages/mesh/src/Mesh.ts
Labels: ✅ Ready To Merge

#8893 Feature: Add `Text.graphemeSegmenter` option
  packages/text/src/Text.ts
Labels: ✅ Ready To Merge

#8898 Support loading font assets in data URLs
  packages/assets/src/loader/parsers/loadWebFont.ts
  packages/assets/src/loader/parsers/textures/loadTextures.ts
  packages/assets/src/loader/parsers/textures/utils/index.ts
  packages/assets/src/utils/checkDataUrl.ts
  packages/assets/src/utils/checkExtension.ts
  packages/assets/src/utils/index.ts
  packages/assets/test/assets.tests.ts
Labels: ✅ Ready To Merge

#8902 Fix typo in preferWorkers API
  packages/assets/src/Assets.ts
Labels: ✅ Ready To Merge

#8903 Cleanup unused Asset.init options
  packages/assets/src/Assets.ts
Labels: ✅ Ready To Merge

#8904 Support XML fonts in Webworker
  bundles/pixi.js-node/package.json
  bundles/pixi.js-node/src/adapter/adapter.ts
  bundles/pixi.js-node/src/adapter/index.ts
  bundles/pixi.js-node/src/adapter/loadNodeBitmapFont.ts
  bundles/pixi.js-node/src/index.ts
  bundles/pixi.js-webworker/package.json
  bundles/pixi.js-webworker/src/adapter.ts
  package-lock.json
  packages/settings/src/adapter.ts
  packages/text-bitmap/src/formats/XMLFormat.ts
  packages/text-bitmap/src/formats/XMLStringFormat.ts
Labels: ✅ Ready To Merge

#8911 Fix: Support font assets with space in URL
  packages/assets/src/loader/parsers/loadWebFont.ts
  packages/assets/test/assets.tests.ts
  packages/assets/test/assets/fonts/url with space.ttf
Labels: ✅ Ready To Merge
