Repository pixijs/pixijs, pull requests merged in 2023-01, with the labels that each got.

#8960 Add strict null checks to @pixijs/utils
  packages/utils/src/browser/isWebGLSupported.ts
  packages/utils/src/data/createIndicesForQuads.ts
  packages/utils/src/media/CanvasRenderTarget.ts
  packages/utils/src/media/getCanvasBoundingBox.ts
  packages/utils/src/media/trimCanvas.ts
  packages/utils/src/network/decomposeDataUri.ts
  packages/utils/src/network/getResolutionOfUrl.ts
  packages/utils/src/path.ts
  packages/utils/test/CanvasRenderTarget.tests.ts
  packages/utils/test/getCanvasBoundingBox.tests.ts
  packages/utils/test/trimCanvas.tests.ts
  packages/utils/test/utils.tests.ts
Labels: ✅ Ready To Merge

#8996 Fix ResolverAssetsArray.srcs type
  packages/assets/src/resolver/Resolver.ts
  packages/assets/src/resolver/types.ts
Labels: ✅ Ready To Merge

#9010 Expose options for Renderers
  packages/canvas-renderer/src/CanvasRenderer.ts
  packages/canvas-renderer/test/CanvasRenderer.tests.ts
  packages/core/src/IRenderer.ts
  packages/core/src/Renderer.ts
  packages/core/test/Renderer.tests.ts
Labels: ✅ Ready To Merge

#9020 Add CDN Install section in READMEs for browser builds
  README.md
  bundles/pixi.js-legacy/README.md
  bundles/pixi.js-webworker/README.md
  bundles/pixi.js/README.md
  packages/basis/README.md
  packages/graphics-extras/README.md
  packages/math-extras/README.md
  packages/unsafe-eval/README.md
Labels: ✅ Ready To Merge

#9022 Fix `TextMetrics.measureFont` breaking if passed a font with size 0
  packages/text/src/TextMetrics.ts
Labels: ✅ Ready To Merge

#9033 `@pixi/node` README.md improvements (Dockerfile example + `vxfb` install)
  bundles/pixi.js-node/README.md
Labels: ✅ Ready To Merge

#9037 Improve typing for `loader.load()` in spritesheetAsset
  packages/spritesheet/src/spritesheetAsset.ts
  packages/spritesheet/test/spritesheetAsset.tests.ts
Labels: ✅ Ready To Merge

#9038 Update trimCanvas.ts import
  packages/utils/src/media/trimCanvas.ts
Labels: ✅ Ready To Merge

#9039 Deprecate filters namespace
  bundles/pixi.js-node/src/filters.ts
  bundles/pixi.js-node/src/index.ts
  bundles/pixi.js-webworker/src/filters.ts
  bundles/pixi.js-webworker/src/index.ts
  bundles/pixi.js/src/filters.ts
  bundles/pixi.js/src/index.ts
  packages/core/src/filters/Filter.ts
  packages/filter-alpha/src/AlphaFilter.ts
  packages/filter-blur/src/BlurFilter.ts
  packages/filter-blur/src/BlurFilterPass.ts
  packages/filter-color-matrix/src/ColorMatrixFilter.ts
  packages/filter-displacement/src/DisplacementFilter.ts
  packages/filter-fxaa/src/FXAAFilter.ts
  packages/filter-noise/src/NoiseFilter.ts
Labels: ✅ Ready To Merge

#9045 Chore: Remove some duplicate definitions
  packages/canvas-renderer/src/CanvasRenderer.ts
  packages/core/src/Renderer.ts
Labels: ✅ Ready To Merge

#9046 Add SVG Assets parser to list of parsers
  packages/assets/src/Assets.ts
  packages/assets/src/loader/parsers/textures/loadSVG.ts
Labels: ✅ Ready To Merge

#9050 Fix inappropriate document for `arcTo`
  packages/graphics/src/Graphics.ts
  packages/graphics/src/utils/ArcUtils.ts
Labels: ✅ Ready To Merge

#9054 Pin GitHub Actions Ubuntu version for v6.x
  .github/workflows/nodejs.yml
Labels: 🔥 High Priority

#9060 Fix: Typos in deprecation messages
  packages/core/src/settings.ts
Labels: ✅ Ready To Merge

#9055 Fix defaultSearchParams to append to Spritesheets or BitmapFonts
  packages/assets/src/utils/copySearchParams.ts
  packages/assets/src/utils/index.ts
  packages/spritesheet/src/spritesheetAsset.ts
  packages/text-bitmap/src/loadBitmapFont.ts
  packages/text-bitmap/test/BitmapFontLoader.tests.ts
Labels: ✅ Ready To Merge

#9074 Updated License Year
  LICENSE
Labels: ✅ Ready To Merge

#9067 Add global move events
  packages/events/global.d.ts
  packages/events/src/EventBoundary.ts
  packages/events/src/FederatedEventMap.ts
  packages/events/src/FederatedEventTarget.ts
  packages/events/test/EventSystem.tests.ts
Labels: ✅ Ready To Merge

#9066 pointerout fired when interaction started outside of object
  packages/events/src/EventBoundary.ts
Labels: ✅ Ready To Merge

#9056 Add missing data pass-through for bundle assets
  packages/assets/src/resolver/Resolver.ts
  packages/assets/src/resolver/types.ts
  packages/assets/test/bundle.tests.ts
Labels: ✅ Ready To Merge

#9078 Fix use of deprecated calls
  packages/canvas-renderer/src/CanvasContextSystem.ts
  packages/constants/src/index.ts
  packages/core/global.d.ts
  packages/core/src/mask/MaskData.ts
  packages/core/src/renderTexture/BaseRenderTexture.ts
  packages/core/src/renderTexture/GenerateTextureSystem.ts
  packages/core/src/renderTexture/RenderTexture.ts
  packages/core/src/textures/Texture.ts
  packages/filter-blur/src/BlurFilterPass.ts
Labels: ✅ Ready To Merge

#9088 Fix circular dependencies in build process
  package.json
  packages/core/src/batch/BatchTextureArray.ts
  packages/core/src/mask/MaskData.ts
  packages/core/src/transformFeedback/TransformFeedback.ts
  packages/core/src/transformFeedback/TransformFeedbackSystem.ts
Labels: ✅ Ready To Merge

#9086 Chore: Update document for Extract and Prepare
  packages/extract/src/Extract.ts
  packages/prepare/src/Prepare.ts
Labels: ✅ Ready To Merge

#9073 Fix: Prevent filepath to be URLEncoded
  bundles/pixi.js-node/src/adapter/adapter.ts
Labels: ✅ Ready To Merge

#9093 Fix: Workaround for transpilation failure with create-react-app
  packages/core/src/textures/resources/ImageBitmapResource.ts
Labels: ✅ Ready To Merge

#9091 Fix xadvance calculating when rendering BitmapText
  packages/text-bitmap/src/BitmapFont.ts
  packages/text-bitmap/src/BitmapText.ts
Labels: ✅ Ready To Merge

#9099 Fix: Tests for Assets bundle
  packages/assets/src/resolver/Resolver.ts
  packages/assets/test/bundle.tests.ts
Labels: 🔥 High Priority, ✅ Ready To Merge

#9102 Fix: Extract should use multisample
  packages/extract/src/Extract.ts
  packages/extract/test/Extract.tests.ts
Labels: ✅ Ready To Merge

#9103 Fix: Extract should use multisample (for v6.x)
  packages/extract/package.json
  packages/extract/src/Extract.ts
  packages/extract/test/Extract.tests.ts
Labels: ✅ Ready To Merge

#9106 Chore: Cleanup GitHub Actions deprecation warnings (for v6.x)
  .github/workflows/nodejs.yml
Labels: ✅ Ready To Merge

#9110 Fix renderer options not being passed to plugins
  packages/canvas-renderer/src/CanvasRenderer.ts
  packages/core/src/Renderer.ts
Labels: ✅ Ready To Merge

#9122 Remove navigator.onLine check
  packages/assets/src/loader/parsers/loadWebFont.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9119 Fix glob expansion only working with .add and not with .load
  packages/assets/src/Assets.ts
  packages/assets/src/resolver/Resolver.ts
  packages/assets/test/assets.tests.ts
  packages/assets/test/assets/textures/texture.avif
  packages/assets/test/assets/textures/texture.png
  packages/assets/test/assets/textures/texture.webp
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9061 Add new @pixi/color package and Color class
  package-lock.json
  packages/canvas-renderer/src/CanvasContextSystem.ts
  packages/canvas-renderer/src/CanvasObjectRendererSystem.ts
  packages/canvas-renderer/src/CanvasRenderer.ts
  packages/canvas-renderer/src/canvasUtils.ts
  packages/color/LICENSE
  packages/color/README.md
  packages/color/package.json
  packages/color/src/Color.ts
  packages/color/src/index.ts
  packages/color/test/Color.tests.ts
  packages/core/package.json
  packages/core/src/IRenderer.ts
  packages/core/src/Renderer.ts
  packages/core/src/background/BackgroundSystem.ts
  packages/core/src/index.ts
  packages/core/src/renderTexture/RenderTextureSystem.ts
  packages/core/test/Renderer.tests.ts
  packages/filter-color-matrix/src/ColorMatrixFilter.ts
  packages/graphics/src/Graphics.ts
  packages/particle-container/src/ParticleContainer.ts
  packages/text-bitmap/src/utils/drawGlyph.ts
  packages/text/src/Text.ts
  packages/text/src/TextStyle.ts
  packages/utils/package.json
  packages/utils/src/color/hex.ts
  packages/utils/src/color/premultiply.ts
  packages/utils/src/index.ts
  packages/utils/test/utils.tests.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9087 Add color source support for Graphics' line and fill style
  package-lock.json
  packages/color/test/Color.tests.ts
  packages/graphics/src/Graphics.ts
  packages/graphics/test/Graphics.tests.ts
Labels: ✅ Ready To Merge

#9096 Color API additions: multiply, toLittleEndianNumber
  packages/canvas-graphics/src/CanvasGraphicsRenderer.ts
  packages/color/src/Color.ts
  packages/graphics/src/Graphics.ts
  packages/graphics/src/GraphicsGeometry.ts
  packages/mesh/src/MeshMaterial.ts
  packages/sprite/src/Sprite.ts
Labels: ✅ Ready To Merge

#9097 Support ColorSource in clear color methods
  packages/canvas-renderer/src/CanvasContextSystem.ts
  packages/canvas-renderer/src/CanvasObjectRendererSystem.ts
  packages/core/src/background/BackgroundSystem.ts
  packages/core/src/renderTexture/BaseRenderTexture.ts
  packages/core/src/renderTexture/RenderTextureSystem.ts
  packages/core/test/Renderer.tests.ts
Labels: ✅ Ready To Merge

#9089 Add new types of interaction
  packages/accessibility/src/AccessibilityManager.ts
  packages/events/global.d.ts
  packages/events/package.json
  packages/events/src/EventBoundary.ts
  packages/events/src/EventSystem.ts
  packages/events/src/FederatedEventTarget.ts
  packages/events/test/EventBoundary.tests.ts
  packages/events/test/EventSystem.tests.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9092 Adds EventsTicker to mock events when mouse is stationary
  packages/events/src/EventBoundary.ts
  packages/events/src/EventSystem.ts
  packages/events/src/EventTicker.ts
  packages/ticker/src/const.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9123 Chore: Cleanup document for renderer options (for v6.x)
  packages/app/src/Application.ts
  packages/canvas-renderer/src/CanvasRenderer.ts
  packages/core/src/AbstractRenderer.ts
  packages/core/src/Renderer.ts
  packages/core/src/autoDetectRenderer.ts
  packages/settings/src/settings.ts
Labels: ✅ Ready To Merge
