Repository pixijs/pixijs, pull requests merged in 2023-12, with the labels that each got.

#9913 feat: add trim property to text
  README.md
  src/app/Application.ts
  src/scene/text/TextStyle.ts
  src/scene/text/canvas/CanvasTextSystem.ts
  src/scene/text/utils/generateTextStyleKey.ts
  src/utils/canvas/getCanvasBoundingBox.ts
  tests/visual/scenes/text/text-trim.scene.ts
  tests/visual/snapshots/webgl-text-trim-scene-ts.png
  tests/visual/snapshots/webgpu-text-trim-scene-ts.png
Labels: v8

#9915 v8 add `boundsArea`
  src/scene/container/Container.ts
  src/scene/container/bounds/getGlobalBounds.ts
  src/scene/container/bounds/getLocalBounds.ts
  tests/scene/getGlobalBounds.tests.ts
  tests/scene/getLocalBounds.tests.ts
Labels: v8

#9917 allow tiling sprite constructor to accept a texture
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/sprite-tiling/shader/TilingSpriteShader.ts
Labels: v8

#9919 Add deprecation to v8 TilingSprite
  src/scene/sprite-tiling/TilingSprite.ts
Labels: v8

#9926 Chore/v8/rename-layer-group
  src/rendering/renderers/shared/ProxyRenderable.ts
  src/rendering/renderers/shared/RGRenderable.ts
  src/rendering/renderers/shared/Renderable.ts
  src/rendering/renderers/shared/system/SharedSystems.ts
  src/scene/container/Container.ts
  src/scene/container/RenderGroup.ts
  src/scene/container/RenderGroupPipe.ts
  src/scene/container/RenderGroupSystem.ts
  src/scene/container/bounds/getRenderableBounds.ts
  src/scene/container/container-mixins/childrenHelperMixin.ts
  src/scene/container/container-mixins/effectsMixin.ts
  src/scene/container/container-mixins/onRenderMixin.ts
  src/scene/container/container-mixins/sortMixin.ts
  src/scene/container/utils/buildInstructions.ts
  src/scene/container/utils/collectLayerGroups.ts
  src/scene/container/utils/collectRenderGroups.ts
  src/scene/container/utils/executeInstructions.ts
  src/scene/container/utils/updateRenderGroupTransforms.ts
  src/scene/container/utils/validateRenderables.ts
  src/scene/graphics/shared/BatchableGraphics.ts
  src/scene/graphics/shared/GraphicsPipe.ts
  src/scene/mesh/shared/BatchableMesh.ts
  src/scene/mesh/shared/MeshPipe.ts
  src/scene/sprite/BatchableSprite.ts
  src/scene/text/bitmap/BitmapTextPipe.ts
  src/utils/logging/logScene.ts
  tests/renderering/scene/RenderGroupSystem.test.ts
  tests/scene/Container.tests.ts
  tests/scene/getGlobalBounds.tests.ts
  tests/scene/getLocalBounds.tests.ts
  tests/scene/renderable.tests.ts
  tests/scene/scene.tests.ts
  tests/scene/transform-alpha.tests.ts
  tests/scene/transform-blend.tests.ts
  tests/scene/transform-tint.tests.ts
  tests/scene/transform-visibiity.tests.ts
  tests/scene/transform.tests.ts
  tests/visual/scenes/scene/layer-tint.scene.ts
Labels: v8

#9928 add latest v7 changes
  src/spritesheet/Spritesheet.ts
  src/spritesheet/spritesheetAsset.ts
  tests/renderering/sprite/spritesheetAsset.tests.ts
  tests/scene/depthSorting.tests.ts
Labels: v8

#9929 undo text deprecation
  src/scene/text/Text.ts
Labels: v8

#9914 Chore/v8/culling
  .eslintrc.json
  src/culling/Culler.ts
  src/culling/CullerPlugin.ts
  src/culling/CullingMixins.d.ts
  src/culling/cullingMixin.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/TexturePool.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/scene/container/Container.ts
  tests/scene/culler.test.ts
  types/PixiMixins.d.ts
Labels: v8

#9932 v8 little tweaks for texture unloading
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
Labels: v8

#9934 clean up TextMetrics test, unskip tests, add ticket
  tests/renderering/text/TextMetrics.tests.ts
Labels: v8

#9860 add display tests
  src/scene/container/Container.ts
  tests/display/Container.Culling.tests.ts
  tests/display/Container.Events.tests.ts
  tests/display/Container.Hierarchy.tests.ts
  tests/display/Container.Sort.tests.ts
  tests/display/Container.Visual.tests.ts
  tests/display/Container.tests.ts
  tests/display/toGlobal.tests.ts
  tests/display/toLocal.tests.ts
  tests/visual/scenes/container/container-visibility.scene.ts
  tests/visual/snapshots/webgl-container-visibility-scene-ts.png
  tests/visual/snapshots/webgpu-container-visibility-scene-ts.png
Labels: v8

#9931 v8 make pre the default for wordWrap
  src/scene/text/TextStyle.ts
  src/scene/text/html/utils/textStyleToCSS.ts
  tests/renderering/text/snapshots/HTMLTextStyle.tests.ts.snap
  tests/renderering/text/textStyleToCSS.test.ts
  tests/visual/scenes/text/html-text.scene.ts
Labels: v8, Backport to v7

#9787 Don't set `sortDirty` to true if the `zIndex` doesn't change
  packages/display/src/DisplayObject.ts
  packages/display/test/Container.tests.ts
Labels: ✅ Ready To Merge

#9896 Fix type error in `ISpritesheetData`
  packages/spritesheet/src/Spritesheet.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9937 Optimise/v8/fast-copy
  src/rendering/renderers/shared/buffer/utils/fastCopy.ts
  tests/renderering/buffer/fastCopy.test.ts
Labels: v8

#9940 add setFillStyle setStrokeStyle methods to graphics api
  src/scene/graphics/shared/Graphics.ts
  src/scene/graphics/shared/GraphicsContext.ts
  tests/renderering/graphics/Graphics.test.ts
Labels: v8

#9923 add more visual tests
  tests/assets/assets/textures/piece-newt-single.png
  tests/visual/scenes/container/nested-container.scene.ts
  tests/visual/scenes/graphics/circle.scene.ts
  tests/visual/scenes/graphics/lines-arc.scene.ts
  tests/visual/scenes/graphics/rect-fills.scene.ts
  tests/visual/scenes/graphics/rect.scene.ts
  tests/visual/scenes/graphics/shared-context.scene.ts
  tests/visual/scenes/sprite/sprite.scene.ts
  tests/visual/scenes/text/bitmap-text.scene.ts
  tests/visual/scenes/text/text.scene.ts
  tests/visual/snapshots/webgl-bezier-scene-ts.png
  tests/visual/snapshots/webgl-bitmap-text-scene-ts.png
  tests/visual/snapshots/webgl-circle-scene-ts.png
  tests/visual/snapshots/webgl-continue-path-scene-ts.png
  tests/visual/snapshots/webgl-extras-scene-ts.png
  tests/visual/snapshots/webgl-lines-arc-scene-ts.png
  tests/visual/snapshots/webgl-load-ttf-font-scene-ts.png
  tests/visual/snapshots/webgl-msdf-text-scene-ts.png
  tests/visual/snapshots/webgl-rect-fills-scene-ts.png
  tests/visual/snapshots/webgl-shared-context-scene-ts.png
  tests/visual/snapshots/webgl-sprite-scene-ts.png
  tests/visual/snapshots/webgl-svg-scene-ts.png
  tests/visual/snapshots/webgl-text-scene-ts.png
  tests/visual/snapshots/webgl-tiling-sprite-scene-ts.png
  tests/visual/snapshots/webgpu-bitmap-text-scene-ts.png
  tests/visual/snapshots/webgpu-circle-scene-ts.png
  tests/visual/snapshots/webgpu-continue-path-scene-ts.png
  tests/visual/snapshots/webgpu-extras-scene-ts.png
  tests/visual/snapshots/webgpu-lines-arc-scene-ts.png
  tests/visual/snapshots/webgpu-load-ttf-font-scene-ts.png
  tests/visual/snapshots/webgpu-meshrope-scene-ts.png
  tests/visual/snapshots/webgpu-msdf-text-scene-ts.png
  tests/visual/snapshots/webgpu-rect-fills-scene-ts.png
  tests/visual/snapshots/webgpu-shared-context-scene-ts.png
  tests/visual/snapshots/webgpu-sprite-scene-ts.png
  tests/visual/snapshots/webgpu-svg-scene-ts.png
  tests/visual/snapshots/webgpu-text-scene-ts.png
  tests/visual/snapshots/webgpu-tiling-sprite-scene-ts.png
Labels: v8

#9939 invert texture fill matrix
  src/scene/graphics/shared/utils/convertFillInputToFillStyle.ts
  tests/renderering/graphics/Graphics.test.ts
Labels: v8

#9941 Add number type support to scale field of SpritesheetData
  src/spritesheet/Spritesheet.ts
  tests/renderering/sprite/Spritesheet.tests.ts
Labels: v8

#9944 Chore/fix-graphics-scene-test
  tests/visual/scenes/graphics/rect-fills.scene.ts
  tests/visual/snapshots/webgl-rect-fills-scene-ts.png
  tests/visual/snapshots/webgpu-rect-fills-scene-ts.png
Labels: v8

#9954 Update documentation header content for assets
  src/assets/Assets.ts
Labels: v8

#9970 add geometry bounds
  src/rendering/renderers/shared/geometry/Geometry.ts
  src/rendering/renderers/shared/geometry/utils/getGeometryBounds.ts
  tests/renderering/Geometry.test.ts
  tests/renderering/utils/getGeometryBounds.test.ts
  tests/utils/getGeometry.ts
  tests/utils/getGlProgram.ts
Labels: v8

#9971 v8 Add Get Fast Global Bounds
  src/filters/FilterSystem.ts
  src/rendering/renderers/shared/view/View.ts
  src/scene/container/bounds/Bounds.ts
  src/scene/container/bounds/getFastGlobalBounds.ts
  src/scene/graphics/shared/GraphicsView.ts
  src/scene/mesh/shared/MeshView.ts
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/sprite-tiling/TilingSpriteView.ts
  src/scene/sprite/BatchableSprite.ts
  src/scene/sprite/SpriteView.ts
  src/scene/text-html/HTMLTextPipe.ts
  src/scene/text/TextView.ts
  src/scene/text/canvas/CanvasTextPipe.ts
  src/utils/data/updateQuadBounds.ts
  tests/scene/DummyView.ts
  tests/scene/getGlobalFastBounds.tests.ts
Labels: v8

#9972 v8 optimised `getGlobalbounds`
  src/scene/container/bounds/Bounds.ts
  src/scene/container/bounds/getFastGlobalBounds.ts
  src/scene/container/bounds/getGlobalBounds.ts
  src/scene/container/bounds/utils/matrixAndBoundsPool.ts
  src/scene/graphics/shared/GraphicsContext.ts
  src/scene/graphics/shared/path/ShapePath.ts
Labels: v8

#9979 enhance accessibility documentation
  src/accessibility/AccessibilitySystem.ts
  src/accessibility/accessibilityTarget.ts
Labels: v8

#9975 v8 Optimize getLocalBounds and add a cache
  src/accessibility/AccessibilitySystem.ts
  src/rendering/renderers/shared/RGRenderable.ts
  src/scene/container/Container.ts
  src/scene/container/bounds/Bounds.ts
  src/scene/container/bounds/getLocalBounds.ts
  src/scene/container/container-mixins/measureMixin.ts
  src/scene/container/utils/checkChildrenDidChange.ts
  src/scene/text/TextView.ts
  tests/scene/getLocalBounds.tests.ts
Labels: v8

#9962 fix: allow mask to be null or undefined
  src/scene/container/container-mixins/effectsMixin.ts
Labels: v8

#9967 add v7 graphics compatibility
  src/scene/graphics/shared/Graphics.ts
  src/scene/graphics/shared/GraphicsContext.ts
  tests/visual/scenes/graphics/v7-compatibility-complex.scene.ts
  tests/visual/scenes/graphics/v7-compatibility-simple.scene.ts
  tests/visual/snapshots/webgl-v7-compatibility-complex-scene-ts.png
  tests/visual/snapshots/webgl-v7-compatibility-simple-scene-ts.png
  tests/visual/snapshots/webgpu-v7-compatibility-complex-scene-ts.png
  tests/visual/snapshots/webgpu-v7-compatibility-simple-scene-ts.png
Labels: v8

#9973 reorder readme sections
  README.md
Labels: v8

#9981 v8 webGL - allow ubos to be optional
  src/rendering/batcher/gl/GlBatchAdaptor.ts
  src/rendering/high-shader/shader-bits/globalUniformsBit.ts
  src/rendering/renderers/gl/WebGLRenderer.ts
  src/rendering/renderers/gl/shader/GlShaderSystem.ts
  src/rendering/renderers/gpu/WebGPURenderer.ts
  src/rendering/renderers/shared/renderTarget/GlobalUniformSystem.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
Labels: v8

#9988 Chore: Remove peer utils from assets
  package-lock.json
  packages/assets/package.json
Labels: ✅ Ready To Merge

#9945 Fix: Assets comment change Asset => Assets
  packages/assets/src/Assets.ts
Labels: ✅ Ready To Merge

#9935 Add number type support to `scale` field of `ISpritesheetData`
  packages/spritesheet/src/Spritesheet.ts
  packages/spritesheet/test/Spritesheet.tests.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9984 enhance assets documentation
  src/assets/AssetExtension.ts
  src/assets/Assets.ts
  src/assets/cache/parsers/cacheTextureArray.ts
  src/assets/detections/parsers/detectAvif.ts
  src/assets/detections/parsers/detectDefaults.ts
  src/assets/detections/parsers/detectMp4.ts
  src/assets/detections/parsers/detectOgv.ts
  src/assets/detections/parsers/detectWebm.ts
  src/assets/detections/parsers/detectWebp.ts
  src/assets/loader/parsers/LoaderParser.ts
  src/assets/loader/parsers/loadJson.ts
  src/assets/loader/parsers/loadTxt.ts
  src/assets/loader/parsers/loadWebFont.ts
  src/assets/loader/parsers/textures/loadSVG.ts
  src/assets/loader/parsers/textures/loadTextures.ts
  src/assets/loader/parsers/textures/loadVideoTextures.ts
  src/assets/resolver/parsers/resolveTextureUrl.ts
  src/assets/types.ts
  src/spritesheet/spritesheetAsset.ts
Labels: v8

#9985 enhance color documentation
  src/color/Color.ts
Labels: v8

#9987 enhance events documentation
  src/events/FederatedEventTarget.ts
  src/events/init.ts
Labels: v8

#9990 enhance extensions docs
  src/extensions/Extensions.ts
Labels: v8

#9991 enhance filters documentation
  src/filters/Filter.ts
  src/filters/defaults/blur/BlurFilter.ts
Labels: v8

#9992 enhance maths documentation
  src/maths/matrix/Matrix.ts
  src/maths/misc/const.ts
  src/maths/point/Point.ts
  src/maths/shapes/Ellipse.ts
  src/maths/shapes/Polygon.ts
  src/maths/shapes/Rectangle.ts
  src/maths/shapes/RoundedRectangle.ts
  src/maths/shapes/Triangle.ts
Labels: v8

#9993 enhance rendering documentation
  src/rendering/init.ts
Labels: v8

#9994 enhance scene documentation
  src/scene/container/Container.ts
  src/scene/container/destroyTypes.ts
  src/scene/graphics/shared/Graphics.ts
  src/scene/mesh-nine-slice/NineSliceSprite.ts
  src/scene/mesh-plane/MeshPlane.ts
  src/scene/mesh-plane/PlaneGeometry.ts
  src/scene/mesh-simple/MeshRope.ts
  src/scene/mesh-simple/MeshSimple.ts
  src/scene/mesh-simple/RopeGeometry.ts
  src/scene/mesh/shared/Mesh.ts
  src/scene/mesh/shared/MeshView.ts
  src/scene/sprite-animated/AnimatedSprite.ts
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/sprite/Sprite.ts
  src/scene/text-html/HtmlTextStyle.ts
  src/scene/text/Text.ts
  src/scene/text/TextStyle.ts
Labels: v8

#9995 enhance ticker documentation
  src/ticker/Ticker.ts
  src/ticker/const.ts
Labels: v8

#9996 enhance utils documentation
  src/scene/container/utils/definedProps.ts
  src/utils/browser/isMobile.ts
  src/utils/const.ts
  src/utils/logging/deprecation.ts
  src/utils/misc/Transform.ts
  src/utils/path.ts
  src/utils/types.ts
Labels: v8

#10000 v8 add support for uint16
  src/rendering/batcher/shared/Batcher.ts
  src/rendering/renderers/gpu/GpuEncoderSystem.ts
  src/rendering/renderers/shared/geometry/Geometry.ts
  src/scene/graphics/shared/BatchableGraphics.ts
  src/scene/mesh/shared/BatchableMesh.ts
  src/scene/sprite/BatchableSprite.ts
  tests/renderering/batch/Batcher.test.ts
  tests/renderering/batch/checkCanUseTexture.tests.ts
  tests/visual/scenes/compressed-textures/dds.scene.ts
Labels: v8

#10002 fix for transform to behave like v7
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/scene/container/bounds/getFastGlobalBounds.ts
  src/scene/container/utils/buildInstructions.ts
  tests/scene/getGlobalFastBounds.tests.ts
Labels: v8

#10004 Bugfix/v8/gpu-mask
  src/rendering/renderers/gpu/state/GpuStencilModesToPixi.ts
  tests/visual/scenes/mask/circle-mask.scene.ts
  tests/visual/snapshots/webgl-circle-mask-scene-ts.png
  tests/visual/snapshots/webgpu-circle-mask-scene-ts.png
  tests/visual/snapshots/webgpu-circle-scene-ts.png
Labels: v8

#10003 Fix: Support building with TypeScript 5 with no errors
  .eslintrc.json
  package-lock.json
  package.json
  packages/assets/package.json
  packages/basis/src/TranscoderWorkerWrapper.ts
  packages/basis/src/loader/BasisParser.ts
  packages/canvas-graphics/src/utils/PolygonUtils.ts
  packages/canvas-renderer/src/CanvasContextSystem.ts
  packages/canvas-renderer/src/CanvasObjectRendererSystem.ts
  packages/color/src/Color.ts
  packages/compressed-textures/src/const.ts
  packages/core/src/geometry/Buffer.ts
  packages/core/src/mask/MaskData.ts
  packages/core/src/state/StateSystem.ts
  packages/core/test/FramebufferSystem.tests.ts
  packages/events/src/EventTicker.ts
  packages/events/src/FederatedEventMap.ts
  packages/events/test/EventSystem.tests.ts
  packages/graphics/src/Graphics.ts
  packages/graphics/src/index.ts
  packages/settings/package.json
  packages/settings/src/ICanvas.ts
  scripts/prepublish.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#10006 cleanup misc docs details
  package-lock.json
  package.json
  src/accessibility/AccessibilitySystem.ts
  src/assets/Assets.ts
  src/environment/adapter.ts
  src/filters/Filter.ts
  src/scene/text/TextStyle.ts
  src/scene/text/TextView.ts
  src/ticker/Ticker.ts
  src/utils/types.ts
Labels: v8

#9986 enhance environment documentation
  src/environment/adapter.ts
Labels: v8

#10012 Chore/v8/filter-uniform-name-tidy
  src/filters/Filter.ts
  src/filters/FilterSystem.ts
  src/filters/blend-modes/BlendModeFilter.ts
  src/filters/blend-modes/blend-template.frag
  src/filters/blend-modes/blend-template.vert
  src/filters/blend-modes/blend-template.wgsl
  src/filters/defaults/alpha/alpha.frag
  src/filters/defaults/alpha/alpha.wgsl
  src/filters/defaults/blur/BlurFilterPass.ts
  src/filters/defaults/blur/gl/generateBlurFragSource.ts
  src/filters/defaults/blur/gl/generateBlurVertSource.ts
  src/filters/defaults/blur/gpu/blur-template.wgsl
  src/filters/defaults/blur/gpu/generateBlurProgram.ts
  src/filters/defaults/color-matrix/colorMatrixFilter.frag
  src/filters/defaults/color-matrix/colorMatrixFilter.wgsl
  src/filters/defaults/defaultFilter.vert
  src/filters/defaults/displacement/DisplacementFilter.ts
  src/filters/defaults/displacement/displacement.frag
  src/filters/defaults/displacement/displacement.vert
  src/filters/defaults/displacement/displacement.wgsl
  src/filters/defaults/noise/noise.frag
  src/filters/defaults/noise/noise.wgsl
  src/filters/defaults/shockwave/shockwave.frag
  src/filters/defaults/shockwave/shockwave.vert
  src/filters/defaults/shockwave/shockwave.wgsl
  src/filters/mask/MaskFilter.ts
  src/filters/mask/mask.frag
  src/filters/mask/mask.vert
  src/filters/mask/mask.wgsl
  src/rendering/high-shader/shader-bits/generateTextureBatchBit.ts
  src/rendering/renderers/gl/shader/batchSamplersUniformGroup.ts
  src/rendering/renderers/gpu/shader/BindGroup.ts
  src/rendering/renderers/shared/shader/Shader.ts
Labels: v8

#10015 remove redundant `addResource`
  src/filters/Filter.ts
  src/scene/graphics/gl/GlGraphicsAdaptor.ts
  src/scene/graphics/gpu/GpuGraphicsAdaptor.ts
  src/scene/mesh/gl/GlMeshAdaptor.ts
  src/scene/text/sdfShader/SdfShader.ts
Labels: v8
