Repository pixijs/pixijs, pull requests merged in 2023-02, with the labels that each got.

#9124 Fix deprecation docs for global Settings mixins
  packages/canvas-mesh/global.d.ts
  packages/core/global.d.ts
  packages/display/global.d.ts
  packages/prepare/global.d.ts
  packages/ticker/global.d.ts
Labels: ✅ Ready To Merge

#9134 Chore: Add financial contributors badge
  README.md
Labels: ✅ Ready To Merge

#9133 Docs: Update document for ColorSource
  package-lock.json
  package.json
  packages/app/src/Application.ts
  packages/canvas-renderer/src/CanvasRenderer.ts
  packages/color/src/Color.ts
  packages/core/src/IRenderer.ts
  packages/core/src/Renderer.ts
  packages/core/src/autoDetectRenderer.ts
Labels: ✅ Ready To Merge

#9129 Add snapshotResolver for Jest
  jest.config.js
  packages/text-html/test/snapshots/HTMLTextStyle.tests.ts.snap
  test/jest-snapshot-resolver.js
Labels: ✅ Ready To Merge

#9135 Chore: Bump required Node.js to 18+
  .github/workflows/nodejs.yml
  package-lock.json
  package.json
Labels: ✅ Ready To Merge

#9147 Fix: Invalid Color value when using multiply or round methods
  packages/color/src/Color.ts
  packages/color/test/Color.tests.ts
Labels: ✅ Ready To Merge

#9127 Import HTMLText API
  bundles/pixi.js/package.json
  bundles/pixi.js/src/index.ts
  jest.config.js
  package-lock.json
  packages/text-html/README.md
  packages/text-html/package.json
  packages/text-html/src/HTMLText.ts
  packages/text-html/src/HTMLTextStyle.ts
  packages/text-html/src/index.ts
  packages/text-html/test/HTMLText.tests.ts
  packages/text-html/test/HTMLTextStyle.tests.ts
  packages/text-html/test/resources/Herborn.ttf
  packages/text-html/test/snapshots/HTMLTextStyle.tests.ts.snap
  test/jest-snapshot-resolver.js
Labels: ✅ Ready To Merge

#9128 Support Texture borders (e.g., NineSlicePlane) with Spritesheets
  packages/core/src/textures/Texture.ts
  packages/mesh-extras/src/NineSlicePlane.ts
  packages/mesh-extras/test/NineSlicePlane.tests.ts
  packages/mesh-extras/test/resources/sheet-9slice.json
  packages/mesh-extras/test/resources/sheet-9slice.png
  packages/spritesheet/src/Spritesheet.ts
Labels: ✅ Ready To Merge

#9151 Updated README.md
  README.md
Labels: ✅ Ready To Merge

#9130 Fix wrong DOM_DELTA_* values by getting them from WheelEvent API
  packages/events/src/FederatedWheelEvent.ts
Labels: ✅ Ready To Merge

#9154 Fix regression gracefully handling null color in Graphics
  packages/graphics/src/Graphics.ts
Labels: ✅ Ready To Merge

#9152 Fix building of optional packages
  package.json
  rollup.config.js
Labels: 🔥 High Priority, ✅ Ready To Merge

#9161 Docs: update documentation
  packages/assets/src/loader/parsers/LoaderParser.ts
  packages/assets/src/loader/parsers/loadWebFont.ts
  packages/basis/src/Basis.ts
  packages/canvas-renderer/src/CanvasContextSystem.ts
  packages/canvas-renderer/src/CanvasRenderer.ts
  packages/compressed-textures/src/const.ts
  packages/compressed-textures/src/resources/BlobResource.ts
  packages/constants/src/index.ts
  packages/core/src/Renderer.ts
  packages/core/src/filters/FilterSystem.ts
  packages/core/src/geometry/Buffer.ts
  packages/core/src/geometry/Geometry.ts
  packages/core/src/mask/MaskData.ts
  packages/core/src/projection/ProjectionSystem.ts
  packages/core/src/renderTexture/RenderTextureSystem.ts
  packages/core/src/settings.ts
  packages/core/src/textures/resources/BaseImageResource.ts
  packages/core/src/textures/resources/BufferResource.ts
  packages/core/src/textures/resources/ImageResource.ts
  packages/core/src/textures/resources/VideoResource.ts
  packages/display/src/Bounds.ts
  packages/display/src/DisplayObject.ts
  packages/events/src/EventBoundary.ts
  packages/events/src/EventSystem.ts
  packages/events/src/EventTicker.ts
  packages/events/src/FederatedEvent.ts
  packages/events/src/FederatedEventTarget.ts
  packages/events/src/FederatedMouseEvent.ts
  packages/graphics/src/GraphicsGeometry.ts
  packages/graphics/src/const.ts
  packages/math/src/Transform.ts
  packages/math/src/const.ts
  packages/math/src/groupD8.ts
  packages/math/src/index.ts
  packages/mesh/src/MeshMaterial.ts
  packages/settings/src/utils/isMobile.ts
  packages/spritesheet/src/spritesheetAsset.ts
  packages/text/src/const.ts
  packages/ticker/src/const.ts
  packages/utils/src/media/BoundingBox.ts
  packages/utils/src/media/caches.ts
Labels: ✅ Ready To Merge

#9163 Chore: Use workspaces-run fork and orderByDeps
  package-lock.json
  package.json
  rollup.config.js
  scripts/prepublish.ts
  test/packages.ts
Labels: ✅ Ready To Merge

#9162 Docs: Cleanup document
  packages/assets/src/cache/CacheParser.ts
  packages/assets/src/loader/parsers/LoaderParser.ts
  packages/color/src/Color.ts
  packages/core/src/geometry/Buffer.ts
  packages/core/src/renderTexture/BaseRenderTexture.ts
  packages/core/src/textures/Texture.ts
  packages/core/src/textures/resources/BufferResource.ts
  packages/core/src/textures/resources/CanvasResource.ts
  packages/core/src/textures/resources/CubeResource.ts
  packages/events/global.d.ts
  packages/events/src/EventSystem.ts
  packages/events/src/EventTicker.ts
  packages/events/src/FederatedEventTarget.ts
  packages/graphics/src/Graphics.ts
  packages/graphics/src/const.ts
  packages/spritesheet/src/Spritesheet.ts
  packages/text-html/src/HTMLText.ts
  packages/text-html/src/HTMLTextStyle.ts
Labels: ✅ Ready To Merge

#9157 Docs: Add defaultInteraction for renderer params
  packages/app/src/Application.ts
  packages/canvas-renderer/src/CanvasRenderer.ts
  packages/core/src/Renderer.ts
  packages/core/src/autoDetectRenderer.ts
Labels: ✅ Ready To Merge

#9112 Simplify renderer plugin startup
  packages/app/src/Application.ts
  packages/app/src/ResizePlugin.ts
  packages/canvas-renderer/src/CanvasRenderer.ts
  packages/core/global.d.ts
  packages/core/src/IRenderer.ts
  packages/core/src/Renderer.ts
  packages/core/src/autoDetectRenderer.ts
  packages/core/src/background/BackgroundSystem.ts
  packages/core/src/context/ContextSystem.ts
  packages/core/src/plugin/PluginSystem.ts
  packages/core/src/settings.ts
  packages/core/src/startup/StartupSystem.ts
  packages/core/src/system/ISystem.ts
  packages/core/src/view/ViewSystem.ts
  packages/events/src/EventSystem.ts
  packages/settings/src/settings.ts
  packages/ticker/src/TickerPlugin.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9166 Fix: events firing when they shouldn't
  packages/events/src/EventBoundary.ts
  packages/events/test/EventBoundary.tests.ts
  packages/events/test/EventSystem.tests.ts
Labels: ✅ Ready To Merge

#9170 adds back getLocalPosition from v6
  packages/events/src/FederatedMouseEvent.ts
  packages/events/test/EventSystem.tests.ts
Labels: ✅ Ready To Merge

#9171 Refactor premultiply utilities to the Color class
  packages/color/src/Color.ts
  packages/color/test/Color.tests.ts
  packages/core/src/batch/BatchRenderer.ts
  packages/graphics/src/GraphicsGeometry.ts
  packages/mesh/src/MeshMaterial.ts
  packages/particle-container/src/ParticleRenderer.ts
  packages/sprite-tiling/src/TilingSpriteRenderer.ts
  packages/utils/src/color/premultiply.ts
  packages/utils/test/utils.tests.ts
Labels: ✅ Ready To Merge

#9173 Chore: Update workspaces-run package
  package-lock.json
  package.json
  rollup.config.js
  scripts/prepublish.ts
  test/packages.ts
Labels: ✅ Ready To Merge

#9169 Add ability to set Color object on `vec3` or `vec4` uniforms
  packages/core/src/shader/utils/uniformParsers.ts
Labels: ✅ Ready To Merge

#9172 Deprecate interaction for eventMode
  packages/display/src/DisplayObject.ts
  packages/events/global.d.ts
  packages/events/src/EventBoundary.ts
  packages/events/src/EventSystem.ts
  packages/events/src/FederatedEventTarget.ts
  packages/events/test/EventBoundary.tests.ts
  packages/events/test/EventSystem.tests.ts
Labels: ✅ Ready To Merge

#9168 Feat: Add new config options for loadTextures
  packages/assets/src/loader/parsers/textures/loadTextures.ts
Labels: ✅ Ready To Merge

#9196 Bundle @pixi/color correctly
  rollup.config.js
Labels: ✅ Ready To Merge

#9188 Add strict null checks to @pixijs/color
  packages/color/src/Color.ts
  scripts/filterTypeScriptErrors.ts
Labels: ✅ Ready To Merge

#9185 Fixes missing global definition file reference in utils
  packages/utils/src/index.ts
Labels: ✅ Ready To Merge

#9184 Provide extensible Asset preferences
  packages/assets/global.d.ts
  packages/assets/package.json
  packages/assets/src/Assets.ts
  packages/assets/src/index.ts
  packages/assets/src/loader/parsers/LoaderParser.ts
  packages/assets/src/loader/parsers/textures/loadTextures.ts
  packages/assets/test/assets.tests.ts
Labels: ✅ Ready To Merge

#9193 Fix the flicker between text renders
  packages/text-html/src/HTMLText.ts
Labels: ✅ Ready To Merge

#9180 Support ColorSource with Graphics tint
  packages/graphics/src/Graphics.ts
  packages/graphics/test/Graphics.tests.ts
Labels: ✅ Ready To Merge

#9181 Support ColorSource with Mesh & BitmapText tint
  packages/canvas-mesh/src/CanvasMeshRenderer.ts
  packages/canvas-mesh/src/NineSlicePlane.ts
  packages/mesh/src/Mesh.ts
  packages/mesh/src/MeshMaterial.ts
  packages/mesh/test/Mesh.tests.ts
  packages/text-bitmap/src/BitmapText.ts
  packages/text-bitmap/src/BitmapTextStyle.ts
  packages/text-bitmap/test/BitmapText.tests.ts
Labels: ✅ Ready To Merge

#9182 Support ColorSource with Sprite tint
  packages/canvas-sprite-tiling/src/TilingSprite.ts
  packages/canvas-sprite/src/CanvasSpriteRenderer.ts
  packages/sprite/src/Sprite.ts
  packages/sprite/test/Sprite.tests.ts
Labels: ✅ Ready To Merge

#9183 Support ColorSource with ParticleContainer tint
  packages/particle-container/src/ParticleContainer.ts
  packages/particle-container/test/ParticleContainer.tests.ts
Labels: ✅ Ready To Merge

#9190 Fixes `rightclick` and `onrightclick` not triggering
  packages/events/src/EventBoundary.ts
Labels: ✅ Ready To Merge

#9209 Resolution isn't readonly in current renderer implementation
  packages/core/src/IRenderer.ts
Labels: ✅ Ready To Merge

#9203 Chore: Remove all dependencies from module bundles
  package-lock.json
  package.json
  packages/settings/package.json
  packages/settings/src/utils/isMobile.ts
  rollup.config.js
Labels: ✅ Ready To Merge

#9208 Fix: TilingSprite#tileScale inconsistency between WebGL and Canvas
  packages/canvas-sprite-tiling/src/TilingSprite.ts
Labels: ✅ Ready To Merge

#9211 Add strict null checks to packages with no errors
  package.json
  scripts/filterTypeScriptErrors.ts
Labels: ✅ Ready To Merge

#9031 Refactor `buildNonNativeLine`
  packages/graphics/src/utils/buildLine.ts
Labels: ✅ Ready To Merge

#9215 Add strict null checks to @pixi/math and @pixi/math-extras
  packages/math-extras/src/index.ts
  packages/math-extras/src/pointExtras.ts
  packages/math-extras/src/rectangleExtras.ts
  packages/math/test/Rectangle.tests.ts
  scripts/filterTypeScriptErrors.ts
Labels: ✅ Ready To Merge

#9218 Fix: Renderer#type not available
  packages/canvas-renderer/src/CanvasRenderer.ts
  packages/core/src/Renderer.ts
Labels: ✅ Ready To Merge

#9217 Migrate @pixi/node bundle
  .github/workflows/nodejs.yml
  README.md
  bundles/pixi.js-node/LICENSE
  bundles/pixi.js-node/README.md
  bundles/pixi.js-node/jest.config.js
  bundles/pixi.js-node/package.json
  bundles/pixi.js-node/src/adapter/NodeCanvasElement.ts
  bundles/pixi.js-node/src/adapter/NodeCanvasResource.ts
  bundles/pixi.js-node/src/adapter/adapter.ts
  bundles/pixi.js-node/src/adapter/index.ts
  bundles/pixi.js-node/src/adapter/loadNodeBase64.ts
  bundles/pixi.js-node/src/adapter/loadNodeFont.ts
  bundles/pixi.js-node/src/adapter/loadNodeTexture.ts
  bundles/pixi.js-node/src/adapter/polyfills.ts
  bundles/pixi.js-node/src/filters.ts
  bundles/pixi.js-node/src/index.ts
  bundles/pixi.js-node/test/NodeCanvasElement.tests.ts
  bundles/pixi.js-node/test/import.mjs
  bundles/pixi.js-node/test/require.cjs
  package-lock.json
  package.json
  scripts/filterTypeScriptErrors.ts
  tsconfig.json
Labels: ✅ Ready To Merge
