Repository pixijs/pixijs, pull requests merged in 2023-09, with the labels that each got.

#9596 Chore: Cache node_modules in GitHub Actions
  .github/workflows/nodejs.yml
Labels: ✅ Ready To Merge

#9602 fix: worldAlpha becomes abnormal
  packages/display/src/DisplayObject.ts
  packages/display/test/DisplayObject.tests.ts
Labels: ✅ Ready To Merge

#9608 Fixed colord type imports
  packages/color/src/Color.ts
Labels: ✅ Ready To Merge

#9624 grammar fixes on eventMode documentation
  packages/events/src/FederatedEventTarget.ts
Labels: ✅ Ready To Merge

#9591 fix: both touch and point events were called when using Apple pencil
  packages/events/src/EventSystem.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9580 Add the `Texture.destroyed` property/event. Log a warning if a `Texture` managed by `Assets` is destroyed but its `BaseTexture` is not
  packages/assets/src/loader/Loader.ts
  packages/assets/src/loader/parsers/textures/utils/createTexture.ts
  packages/assets/test/assets.tests.ts
  packages/core/src/textures/BaseTexture.ts
  packages/core/src/textures/Texture.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9649 tweaks to v8 html text
  src/rendering/text/Text.ts
  src/rendering/text/TextView.ts
Labels: v8

#9639 fix for bitmap text update bug v8 - fixes #9619
  src/rendering/text/bitmap/BitmapTextPipe.ts
Labels: v8

#9641 fix padding issue with text
  src/rendering/graphics/gl/graphics-batcher-template.vert
  src/rendering/graphics/shared/GraphicsContextSystem.ts
  src/rendering/sprite/shared/SpriteView.ts
  src/rendering/text/TextView.ts
  src/rendering/text/bitmap/BitmapTextPipe.ts
  src/rendering/text/canvas/CanvasTextPipe.ts
  src/rendering/text/canvas/CanvasTextSystem.ts
  src/rendering/text/html/HTMLTextPipe.ts
  src/utils/updateQuadBounds.ts
Labels: v8

#9648 Feature: Generate Texture and Extract
  src/rendering/renderers/gl/GlBackBufferSystem.ts
  src/rendering/renderers/gl/GlRenderTargetSystem.ts
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/gl/texture/utils/unpremultiplyAlpha.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  src/rendering/renderers/shared/ExtractSystem.ts
  src/rendering/renderers/shared/GenerateTextureSystem.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/system/SharedSystems.ts
  src/rendering/renderers/shared/texture/GenerateCanvas.ts
  tests/renderering/extract/Extract.test.ts
  tests/renderering/textures/GLTextureSystem.test.ts
  tests/renderering/textures/GenerateTexture.test.ts
  tests/utils/getRenderer.ts
Labels: v8

#9650 Migrate v7 changes
  src/assets/Assets.ts
  src/assets/loader/Loader.ts
  src/assets/loader/parsers/textures/utils/createTexture.ts
  src/assets/resolver/Resolver.ts
  src/assets/utils/convertToList.ts
  src/events/EventSystem.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/rendering/text/bitmap/asset/textFormat.ts
  src/rendering/text/bitmap/asset/xmlFormat.ts
  src/rendering/text/bitmap/asset/xmlStringFormat.ts
  src/spritesheet/Spritesheet.ts
  src/utils/path.ts
Labels: v8

#9480 fix(EventSystem): Bind touch events only if not supports pointer events
  packages/events/src/EventSystem.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9634 Handle data URLs & blob URLs properly
  packages/utils/src/path.ts
  packages/utils/test/path.tests.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9645 Fix an exception when installing a BitmapFont from an XML as a string
  packages/text-bitmap/src/formats/TextFormat.ts
  packages/text-bitmap/src/formats/XMLFormat.ts
  packages/text-bitmap/src/formats/XMLStringFormat.ts
  packages/text-bitmap/src/formats/index.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9653 add AnimatedSprite with tests
  src/rendering/animation/shared/AnimatedSprite.ts
  tests/renderering/animation/AnimatedSprite.test.ts
Labels: v8

#9657 rename type to renderPipeId
  src/rendering/graphics/shared/GraphicsView.ts
  src/rendering/mesh/shared/MeshView.ts
  src/rendering/renderers/shared/View.ts
  src/rendering/scene/LayerGroup.ts
  src/rendering/scene/utils/buildInstructions.ts
  src/rendering/scene/utils/validateRenderables.ts
  src/rendering/sprite/shared/SpriteView.ts
  src/rendering/text/TextView.ts
  src/tiling-sprite/TilingSpriteView.ts
  tests/scene/DummyView.ts
Labels: v8

#9655 ensure destroy() implemented on all Systems
  src/app/Application.ts
  src/events/EventSystem.ts
  src/rendering/filters/shared/FilterSystem.ts
  src/rendering/graphics/shared/GraphicsContextSystem.ts
  src/rendering/renderers/gl/GlBackBufferSystem.ts
  src/rendering/renderers/gl/GlColorMaskSystem.ts
  src/rendering/renderers/gl/GlEncoderSystem.ts
  src/rendering/renderers/gl/GlRenderTargetSystem.ts
  src/rendering/renderers/gl/GlStencilSystem.ts
  src/rendering/renderers/gl/buffer/GlBufferSystem.ts
  src/rendering/renderers/gl/geometry/GlGeometrySystem.ts
  src/rendering/renderers/gl/shader/GlShaderSystem.ts
  src/rendering/renderers/gl/shader/GlUniformGroupSystem.ts
  src/rendering/renderers/gl/state/GlStateSystem.ts
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/gpu/BindGroupSystem.ts
  src/rendering/renderers/gpu/GpuColorMaskSystem.ts
  src/rendering/renderers/gpu/GpuDeviceSystem.ts
  src/rendering/renderers/gpu/GpuEncoderSystem.ts
  src/rendering/renderers/gpu/GpuStencilSystem.ts
  src/rendering/renderers/gpu/buffer/GpuBufferSystem.ts
  src/rendering/renderers/gpu/pipeline/PipelineSystem.ts
  src/rendering/renderers/gpu/renderTarget/GpuRenderTargetSystem.ts
  src/rendering/renderers/gpu/shader/GpuShaderSystem.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  src/rendering/renderers/shared/GenerateTextureSystem.ts
  src/rendering/renderers/shared/ViewSystem.ts
  src/rendering/renderers/shared/background/BackgroundSystem.ts
  src/rendering/renderers/shared/renderTarget/GlobalUniformSystem.ts
  src/rendering/renderers/shared/shader/UniformBufferSystem.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/system/System.ts
  src/rendering/scene/LayerSystem.ts
  src/rendering/scene/destroyTypes.ts
  src/rendering/text/canvas/CanvasTextSystem.ts
  src/rendering/text/html/HTMLTextSystem.ts
Labels: v8

#9656 WebGL Shader Compiler
  src/rendering/batcher/gl/GlBatchAdaptor.ts
  src/rendering/batcher/gl/batcher-template.frag
  src/rendering/batcher/gl/batcher-template.vert
  src/rendering/batcher/gl/generateBatchGlProgram.ts
  src/rendering/batcher/gl/generateDefaultBatchGlProgram.ts
  src/rendering/batcher/gpu/GpuBatchAdaptor.ts
  src/rendering/graphics/gl/GlGraphicsAdaptor.ts
  src/rendering/graphics/gl/generateDefaultGraphicsBatchGlProgram.ts
  src/rendering/graphics/gl/graphics-batcher-template.frag
  src/rendering/graphics/gl/graphics-batcher-template.vert
  src/rendering/graphics/gpu/GpuGraphicsAdaptor.ts
  src/rendering/high-shader/compileHighShaderToProgram.ts
  src/rendering/high-shader/compiler/compileHighShader.ts
  src/rendering/high-shader/defaultProgramTemplate.ts
  src/rendering/high-shader/shader-bits/colorBit.ts
  src/rendering/high-shader/shader-bits/generateTextureBatchBit.ts
  src/rendering/high-shader/shader-bits/globalUniformsBit.ts
  src/rendering/high-shader/shader-bits/localUniformBit.ts
  src/rendering/high-shader/shader-bits/textureBit.ts
  src/rendering/mesh/gl/GlMeshAdaptor.ts
  src/rendering/mesh/gl/mesh-default.frag
  src/rendering/mesh/gl/mesh-default.vert
  src/rendering/mesh/gpu/GpuMeshAdapter.ts
  src/rendering/mesh/shared/MeshPipe.ts
  src/rendering/renderers/gpu/shader/GpuProgram.ts
  src/rendering/text/bitmap/BitmapTextPipe.ts
  src/rendering/text/sdfShader/SdfShader.ts
  src/rendering/text/sdfShader/generateDefaultSdfBatchGlProgram.ts
  src/rendering/text/sdfShader/sdf-batcher-template.frag
  src/rendering/text/sdfShader/sdf-batcher-template.vert
  src/rendering/text/sdfShader/shader-bits/localUniformMSDFBit.ts
  src/rendering/text/sdfShader/shader-bits/mSDFBit.ts
  src/tiling-sprite/shader/TilingSpriteShader.ts
  src/tiling-sprite/shader/tiling-sprite.frag
  src/tiling-sprite/shader/tiling-sprite.vert
  src/tiling-sprite/shader/tilingBit.ts
Labels: v8

#9662 Allow resolveCharacters to return empty set for empty strings
  src/rendering/text/bitmap/utils/resolveCharacters.ts
Labels: v8

#9668 Some misc v8 fixes and tweaks
  src/rendering/batcher/shared/BatcherPipe.ts
  src/rendering/high-shader/shader-bits/colorBit.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/sprite/shared/BatchableSprite.ts
  src/rendering/text/TextView.ts
  src/rendering/text/canvas/CanvasTextSystem.ts
  src/rendering/text/html/utils/getPo2TextureFromSource.ts
  src/utils/updateQuadBounds.ts
Labels: v8

#9673 v8-batch fixes
  src/rendering/batcher/shared/BatchTextureArray.ts
  src/rendering/batcher/shared/Batcher.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/text/bitmap/BitmapTextPipe.ts
Labels: v8

#9672 Feature/v8 video textures
  src/rendering/batcher/gpu/GpuBatchAdaptor.ts
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/gl/texture/uploaders/GLTextureUploader.ts
  src/rendering/renderers/gl/texture/uploaders/glUploadBufferImageResource.ts
  src/rendering/renderers/gl/texture/uploaders/glUploadImageResource.ts
  src/rendering/renderers/gl/texture/uploaders/glUploadVideoResource.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  src/rendering/renderers/gpu/texture/uploaders/gpuUploadImageSource.ts
  src/rendering/renderers/gpu/texture/uploaders/gpuUploadVideoSource.ts
  src/rendering/renderers/shared/texture/sources/BufferImageSource.ts
  src/rendering/renderers/shared/texture/sources/CanvasSource.ts
  src/rendering/renderers/shared/texture/sources/ImageSource.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/rendering/renderers/shared/texture/sources/VideoSource.ts
  src/rendering/renderers/shared/texture/utils/crossOrigin.ts
  src/rendering/sprite/shared/SpriteView.ts
  src/rendering/text/canvas/CanvasTextSystem.ts
  src/rendering/text/html/HTMLTextSystem.ts
  src/rendering/text/html/utils/getPo2TextureFromSource.ts
  tests/assets/assets/video/park.mp4
  tests/renderering/textures/VideoSource.test.ts
Labels: v8

#9678 v8 text texture gc fix
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
Labels: v8

#9675 v8 console log a texture
  src/rendering/renderers/shared/ExtractSystem.ts
Labels: v8

#9681 Feature/v8 video frame source
  src/rendering/renderers/gl/texture/uploaders/glUploadImageResource.ts
  src/rendering/renderers/gpu/texture/uploaders/gpuUploadImageSource.ts
  src/rendering/renderers/shared/texture/sources/ImageSource.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
Labels: v8

#9679 Feature/v8 load video texture asset
  src/assets/init.ts
  src/assets/loader/parsers/textures/loadVideoTextures.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/rendering/renderers/shared/texture/sources/VideoSource.ts
  src/rendering/renderers/shared/texture/utils/crossOrigin.ts
  tests/renderering/textures/VideoSource.test.ts
Labels: v8

#9684 - fix displacement uniform bug
  src/filters/displacement/displacement.frag
  src/rendering/filters/shared/FilterSystem.ts
  src/rendering/renderers/gl/GlRenderTargetSystem.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/texture/TexturePool.ts
Labels: v8

#9636 fix issue with loading asset without an alias
  packages/assets/src/Assets.ts
  packages/assets/src/resolver/Resolver.ts
  packages/assets/src/utils/convertToList.ts
  packages/assets/test/assets.tests.ts
  packages/assets/test/assets/textures/bunny.1.png
  packages/assets/test/assets/textures/bunny.1.webp
  packages/assets/test/assets/textures/bunny.2.png
  packages/assets/test/assets/textures/bunny.2.webp
  packages/assets/test/assets/textures/bunny.3.png
  packages/assets/test/assets/textures/bunny.3.webp
  packages/assets/test/assets/textures/bunny.4.png
  packages/assets/test/unresolved.tests.ts
Labels: ✅ Ready To Merge

#9643 Fix: Round `Sprite` vertices in `calculateTrimmedVertices` if `roundPixels`
  packages/sprite/src/Sprite.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9683 use renderer resolution for text by default
  src/rendering/text/TextView.ts
  src/rendering/text/bitmap/BitmapTextPipe.ts
  src/rendering/text/canvas/CanvasTextPipe.ts
  src/rendering/text/html/HTMLTextPipe.ts
Labels: v8

#9690 last v8 WebGPU bugs!
  src/assets/loader/parsers/textures/loadVideoTextures.ts
  src/filters/color-matrix/colorMatrixFilter.wgsl
  src/rendering/batcher/gpu/GpuBatchAdaptor.ts
  src/rendering/batcher/shared/BatcherPipe.ts
  src/rendering/filters/shared/FilterSystem.ts
  src/rendering/renderers/gl/GlBackBufferSystem.ts
  src/rendering/renderers/gl/GlRenderTargetSystem.ts
  src/rendering/renderers/gl/context/GlContextSystem.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/rendering/scene/LayerSystem.ts
  src/rendering/text/canvas/CanvasTextSystem.ts
Labels: v8

#9674 Adds background alias
  src/rendering/renderers/shared/background/BackgroundSystem.ts
Labels: v8

#9682 add and tidy util functions
  src/rendering/batcher/shared/Batcher.ts
  src/rendering/batcher/shared/BatcherStyleSource.ts
  src/rendering/graphics/shared/GraphicsContext.ts
  src/rendering/graphics/shared/GraphicsView.ts
  src/rendering/graphics/shared/fill/FillGradient.ts
  src/rendering/graphics/shared/fill/FillPattern.ts
  src/rendering/graphics/shared/path/GraphicsPath.ts
  src/rendering/mesh/shared/MeshView.ts
  src/rendering/renderers/gpu/texture/utils/logDebugTexture.ts
  src/rendering/renderers/gpu/texture/utils/logTexture.ts
  src/rendering/renderers/shared/LayerRenderable.ts
  src/rendering/renderers/shared/ProxyRenderable.ts
  src/rendering/renderers/shared/buffer/Buffer.ts
  src/rendering/renderers/shared/buffer/BufferResource.ts
  src/rendering/renderers/shared/geometry/Geometry.ts
  src/rendering/renderers/shared/instructions/InstructionSet.ts
  src/rendering/renderers/shared/renderTarget/RenderTarget.ts
  src/rendering/renderers/shared/shader/UniformGroup.ts
  src/rendering/renderers/shared/system/utils/logRenderFlow.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/rendering/scene/Container.ts
  src/rendering/sprite/shared/SpriteView.ts
  src/rendering/text/TextView.ts
  src/tiling-sprite/TilingSpriteView.ts
  src/utils/data/uid.ts
  src/utils/logging/logDebugTexture.ts
  src/utils/logging/logScene.ts
  src/utils/utils.ts
Labels: v8

#9687 v8 premultiply alpha
  src/assets/loader/parsers/textures/loadTextures.ts
  src/assets/loader/parsers/textures/loadVideoTextures.ts
  src/filters/color-matrix/colorMatrixFilter.frag
  src/filters/color-matrix/colorMatrixFilter.wgsl
  src/rendering/batcher/gpu/GpuBatchAdaptor.ts
  src/rendering/batcher/shared/BatcherPipe.ts
  src/rendering/filters/shared/FilterSystem.ts
  src/rendering/graphics/shared/Graphics.ts
  src/rendering/renderers/gl/GlBackBufferSystem.ts
  src/rendering/renderers/gl/GlRenderTargetSystem.ts
  src/rendering/renderers/gl/context/GlContextSystem.ts
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/gl/texture/uploaders/glUploadImageResource.ts
  src/rendering/renderers/gl/texture/uploaders/glUploadVideoResource.ts
  src/rendering/renderers/gl/texture/utils/applyStyleParams.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  src/rendering/renderers/gpu/texture/uploaders/gpuUploadImageSource.ts
  src/rendering/renderers/gpu/texture/uploaders/gpuUploadVideoSource.ts
  src/rendering/renderers/shared/texture/const.ts
  src/rendering/renderers/shared/texture/sources/CanvasSource.ts
  src/rendering/renderers/shared/texture/sources/ImageSource.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/rendering/renderers/shared/texture/sources/VideoSource.ts
  src/rendering/scene/LayerSystem.ts
  src/rendering/text/bitmap/DynamicBitmapFont.ts
  src/rendering/text/canvas/CanvasTextSystem.ts
  src/utils/browser/detectVideoAlphaMode.ts
Labels: v8

#9692 v8 warning logger
  src/assets/Assets.ts
  src/assets/cache/Cache.ts
  src/assets/loader/Loader.ts
  src/assets/loader/parsers/loadWebFont.ts
  src/assets/loader/parsers/textures/utils/createTexture.ts
  src/assets/resolver/Resolver.ts
  src/events/EventBoundary.ts
  src/rendering/filters/shared/FilterSystem.ts
  src/rendering/graphics/shared/path/GraphicsPath.ts
  src/rendering/graphics/shared/svg/SVGToGraphicsPath.ts
  src/rendering/high-shader/compiler/utils/addBits.ts
  src/rendering/mask/shared/addMaskLocalBounds.ts
  src/rendering/renderers/gl/context/GlContextSystem.ts
  src/rendering/renderers/gl/geometry/GlGeometrySystem.ts
  src/rendering/renderers/gl/shader/program/generateProgram.ts
  src/rendering/renderers/shared/BlendModePipe.ts
  src/rendering/scene/bounds/getLocalBounds.ts
  src/rendering/text/HtmlTextStyle.ts
  src/rendering/text/canvas/utils/getCanvasFillStyle.ts
  src/rendering/text/html/HTMLTextSystem.ts
  src/utils/color/convertColorToNumber.ts
  src/utils/logging/warn.ts
Labels: v8

#9693 v8 Texture style now only on source
  src/filters/displacement/DisplacementFilter.ts
  src/rendering/batcher/gpu/getTextureBatchBindGroup.ts
  src/rendering/batcher/shared/BatcherPipe.ts
  src/rendering/batcher/shared/BatcherStyleSource.ts
  src/rendering/filters/shared/FilterSystem.ts
  src/rendering/graphics/shared/fill/FillGradient.ts
  src/rendering/graphics/shared/fill/FillPattern.ts
  src/rendering/mesh/gl/GlMeshAdaptor.ts
  src/rendering/mesh/gpu/GpuMeshAdapter.ts
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/tiling-sprite/TilingSpritePipe.ts
  src/tiling-sprite/shader/TilingSpriteShader.ts
  src/utils/data/uid.ts
  tests/renderering/textures/TextureSource.test.ts
Labels: v8

#9658 add color package
  jest.config.js
  package-lock.json
  package.json
  src/assets/Assets.ts
  src/color/Color.ts
  src/filters/color-matrix/ColorMatrixFilter.ts
  src/rendering/graphics/shared/Graphics.ts
  src/rendering/graphics/shared/GraphicsContext.ts
  src/rendering/graphics/shared/fill/FillGradient.ts
  src/rendering/graphics/shared/svg/SVGParser.ts
  src/rendering/graphics/shared/utils/buildContextBatches.ts
  src/rendering/graphics/shared/utils/convertFillInputToFillStyle.ts
  src/rendering/renderers/gl/GlBackBufferSystem.ts
  src/rendering/renderers/gl/GlRenderTargetSystem.ts
  src/rendering/renderers/gpu/renderTarget/GpuRenderTargetSystem.ts
  src/rendering/renderers/shared/ExtractSystem.ts
  src/rendering/renderers/shared/GenerateTextureSystem.ts
  src/rendering/renderers/shared/background/BackgroundSystem.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/scene/Container.ts
  src/rendering/text/TextStyle.ts
  src/rendering/text/bitmap/DynamicBitmapFont.ts
  src/rendering/text/canvas/CanvasTextMetrics.ts
  src/rendering/text/canvas/CanvasTextSystem.ts
  src/rendering/text/canvas/utils/getCanvasFillStyle.ts
  src/rendering/text/html/utils/textStyleToCSS.ts
  src/rendering/text/shared/utils/generateTextStyleKey.ts
  src/utils/color/ColorNames.ts
  src/utils/color/convertColorToNumber.ts
  src/utils/color/convertNumberToHex.ts
  src/utils/color/hex.ts
  tests/color/Color.test.ts
Labels: v8

#9694 Chore deprecate children
  src/mesh-extras/NineSlicePlane.ts
  src/rendering/graphics/shared/Graphics.ts
  src/rendering/mesh/shared/Mesh.ts
  src/rendering/scene/Container.ts
  src/rendering/scene/container-mixins/childrenHelperMixin.ts
  src/rendering/sprite/shared/Sprite.ts
  src/rendering/text/Text.ts
  src/tiling-sprite/TilingSprite.ts
  tests/scene/Children.test.ts
Labels: v8

#9695 Update Graphics.ts
  src/rendering/graphics/shared/Graphics.ts
Labels: v8

#9696 Optimise/v8-weird-color-perf
  src/rendering/scene/Container.ts
  src/rendering/sprite/shared/BatchableSprite.ts
Labels: v8

#9698 Update GpuBatchAdaptor.ts
  src/rendering/batcher/gpu/GpuBatchAdaptor.ts
Labels: v8

#9708 Fixed issue with tiling texture
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/scene/sprite-tiling/TilingSpritePipe.ts
Labels: v8

#9685 Add accessibility support
  package.json
  src/accessibility/AccessibilityMixins.d.ts
  src/accessibility/AccessibilitySystem.ts
  src/accessibility/accessibilityTarget.ts
  src/accessibility/init.ts
  src/all.ts
  src/rendering/renderers/shared/system/SharedSystems.ts
  tests/accessibility/AccessibilitySystem.tests.ts
Labels: v8

#9702 add borders to texture
  src/rendering/renderers/shared/texture/TextureLayout.ts
  src/scene/mesh-extras/NineSliceSprite.ts
  src/spritesheet/Spritesheet.ts
  tests/scene/Children.test.ts
Labels: v8

#9710 v8 Constructor Options
  src/accessibility/AccessibilityMixins.d.ts
  src/accessibility/accessibilityTarget.ts
  src/events/EventsMixins.d.ts
  src/events/FederatedEventTarget.ts
  src/scene/SceneMixins.d.ts
  src/scene/container/Container.ts
  src/scene/container/container-mixins/effectsMixin.ts
  src/scene/container/container-mixins/findMixin.ts
  src/scene/container/container-mixins/measureMixin.ts
  src/scene/container/container-mixins/onRenderMixin.ts
  src/scene/container/container-mixins/sortMixin.ts
  src/scene/container/utils/definedProps.ts
  src/scene/graphics/shared/Graphics.ts
  src/scene/mesh-extras/NineSliceSprite.ts
  src/scene/mesh/shared/Mesh.ts
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/sprite/Sprite.ts
  src/scene/text/Text.ts
  src/scene/text/TextView.ts
  tests/scene/Container.tests.ts
  tests/tiling-sprite/TilingSprite.test.ts
Labels: v8

#9717 v8 fix text alignment issue for canvas text
  src/scene/text/canvas/CanvasTextSystem.ts
  src/scene/text/html/HTMLTextSystem.ts
  src/scene/text/html/utils/getPo2TextureFromSource.ts
  tests/renderering/scene/getPo2TextureFromSource.test.ts
Labels: v8

#9720 v7 migrations
  src/assets/Assets.ts
  src/assets/detections/parsers/detectAvif.ts
  src/assets/detections/parsers/detectWebp.ts
  src/assets/detections/utils/testImageFormat.ts
  src/assets/loader/parsers/loadWebFont.ts
  src/assets/loader/parsers/textures/loadVideoTextures.ts
  src/assets/resolver/Resolver.ts
  src/rendering/renderers/shared/texture/sources/VideoSource.ts
Labels: v8

#9718 Change element to canvas
  src/accessibility/AccessibilitySystem.ts
  src/app/Application.ts
  src/events/EventSystem.ts
  src/rendering/renderers/gl/GlRenderTargetSystem.ts
  src/rendering/renderers/gl/context/GlContextSystem.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/view/ViewSystem.ts
Labels: v8

#9714 v8 Pixel Rounding
  src/rendering/RenderingMixins.d.ts
  src/rendering/batcher/gl/GlBatchAdaptor.ts
  src/rendering/batcher/gpu/BatchGeometry.ts
  src/rendering/batcher/gpu/GpuBatchAdaptor.ts
  src/rendering/batcher/gpu/getBatchedGeometry.ts
  src/rendering/batcher/shared/Batcher.ts
  src/rendering/batcher/shared/BatcherPipe.ts
  src/rendering/high-shader/defaultProgramTemplate.ts
  src/rendering/high-shader/shader-bits/generateTextureBatchBit.ts
  src/rendering/high-shader/shader-bits/globalUniformsBit.ts
  src/rendering/high-shader/shader-bits/localUniformBit.ts
  src/rendering/high-shader/shader-bits/roundPixelsBit.ts
  src/rendering/mask/alpha/AlphaMaskPipe.ts
  src/rendering/renderers/shared/renderTarget/GlobalUniformSystem.ts
  src/rendering/renderers/shared/renderTarget/RenderTarget.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/view/View.ts
  src/scene/container/LayerPipe.ts
  src/scene/container/LayerSystem.ts
  src/scene/graphics/gl/GlGraphicsAdaptor.ts
  src/scene/graphics/gpu/GpuGraphicsAdaptor.ts
  src/scene/graphics/shared/BatchableGraphics.ts
  src/scene/graphics/shared/Graphics.ts
  src/scene/graphics/shared/GraphicsPipe.ts
  src/scene/graphics/shared/GraphicsView.ts
  src/scene/mesh-extras/NineSliceSprite.ts
  src/scene/mesh/gl/GlMeshAdaptor.ts
  src/scene/mesh/gpu/GpuMeshAdapter.ts
  src/scene/mesh/shared/BatchableMesh.ts
  src/scene/mesh/shared/Mesh.ts
  src/scene/mesh/shared/MeshPipe.ts
  src/scene/mesh/shared/MeshView.ts
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/sprite-tiling/TilingSpritePipe.ts
  src/scene/sprite-tiling/TilingSpriteView.ts
  src/scene/sprite-tiling/shader/TilingSpriteShader.ts
  src/scene/sprite/BatchableSprite.ts
  src/scene/sprite/Sprite.ts
  src/scene/sprite/SpritePipe.ts
  src/scene/sprite/SpriteView.ts
  src/scene/text/Text.ts
  src/scene/text/TextView.ts
  src/scene/text/bitmap/BitmapTextPipe.ts
  src/scene/text/canvas/CanvasTextPipe.ts
  src/scene/text/html/HTMLTextPipe.ts
  src/scene/text/sdfShader/SdfShader.ts
  src/scene/text/sdfShader/shader-bits/localUniformMSDFBit.ts
  src/utils/data/uid.ts
  tests/renderering/GlobalUniformSystem.test.ts
  tests/renderering/RoundPixels.test.ts
  tests/renderering/batch/checkCanUseTexture.tests.ts
Labels: v8

#9723 Warn if load parser doesn't have a name
  src/assets/AssetExtension.ts
  src/assets/loader/Loader.ts
  src/assets/loader/parsers/LoaderParser.ts
Labels: v8

#9722 Fix passive interaction
  src/events/EventBoundary.ts
Labels: v8
