Repository pixijs/pixijs, pull requests merged in 2023-10, with the labels that each got.

#9728 Little v8 fix when rendering huge Graphics
  src/rendering/high-shader/shader-bits/localUniformBit.ts
  src/scene/graphics/gpu/GpuGraphicsAdaptor.ts
Labels: v8

#9715 Fix: loadWebFont: Don't encodeURI if already valid
  packages/assets/src/loader/parsers/loadWebFont.ts
  packages/assets/test/assets.tests.ts
Labels: ✅ Ready To Merge

#9703 Fix: detectAvif/Webp not working in Worker
  packages/assets/src/detections/parsers/detectAvif.ts
  packages/assets/src/detections/parsers/detectWebp.ts
  packages/assets/src/detections/utils/testImageFormat.ts
Labels: ✅ Ready To Merge

#9735 Add visual testing
  .github/workflows/nodejs.yml
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  scripts/jest/jest-run.ts
  tests/renderering/RoundPixels.test.ts
  tests/visual/scenes/graphics/rect-stroke-alignment.scene.ts
  tests/visual/scenes/graphics/rect-stroke.scene.ts
  tests/visual/scenes/graphics/rect.scene.ts
  tests/visual/snapshots/webgpu-rect-stroke-alignment-scene-ts.png
  tests/visual/snapshots/webgpu-rect-stroke-scene-ts.png
  tests/visual/tester.ts
  tests/visual/types.ts
  tests/visual/visuals.test.ts
Labels: v8

#9738 v8 add a html-text test
  .github/workflows/nodejs.yml
  tests/visual/scenes/graphics/html-text.scene.ts
  tests/visual/snapshots/webgpu-html-text-scene-ts.png
  tests/visual/tester.ts
  tests/visual/types.ts
  tests/visual/visuals.test.ts
Labels: v8

#9734 v8 HTML tagStyles
  .github/workflows/nodejs.yml
  src/scene/text/TextView.ts
  src/scene/text/html/HTMLTextSystem.ts
  src/scene/text/html/HtmlTextStyle.ts
  src/scene/text/html/utils/extractFontFamilies.ts
  src/scene/text/html/utils/getSVGUrl.ts
  src/scene/text/html/utils/measureHtmlText.ts
  src/scene/text/html/utils/textStyleToCSS.ts
  tests/renderering/text/extractFontFamilies.test.ts
  tests/renderering/text/textStyleToCSS.test.ts
  tests/visual/scenes/graphics/html-text.scene.ts
  tests/visual/snapshots/webgpu-html-text-scene-ts.png
  tests/visual/tester.ts
  tests/visual/types.ts
  tests/visual/visuals.test.ts
Labels: v8

#9739 Fix graphics not apply alpha from Color fill
  src/scene/graphics/shared/GraphicsContext.ts
  src/scene/graphics/shared/utils/convertFillInputToFillStyle.ts
  tests/visual/scenes/graphics/color-alpha.scene.ts
  tests/visual/snapshots/webgpu-color-alpha-scene-ts.png
Labels: v8

#9736 Fixed resolutionChange runner emit
  src/rendering/renderers/shared/system/AbstractRenderer.ts
Labels: v8

#9741 v8 fix visual testing
  src/rendering/high-shader/shader-bits/generateTextureBatchBit.ts
  src/scene/text/html/HTMLTextSystem.ts
  tests/visual/snapshots/webgl-color-alpha-scene-ts.png
  tests/visual/snapshots/webgl-html-text-scene-ts.png
  tests/visual/snapshots/webgl-rect-scene-ts.png
  tests/visual/snapshots/webgl-rect-stroke-alignment-scene-ts.png
  tests/visual/snapshots/webgl-rect-stroke-scene-ts.png
  tests/visual/tester.ts
  tests/visual/visuals.test.ts
Labels: v8

#9737 Remove settings object
  src/assets/loader/parsers/loadJson.ts
  src/assets/loader/parsers/loadTxt.ts
  src/assets/loader/parsers/loadWebFont.ts
  src/assets/loader/parsers/textures/loadSVG.ts
  src/assets/loader/parsers/textures/loadTextures.ts
  src/assets/resolver/Resolver.ts
  src/assets/resolver/parsers/resolveTextureUrl.ts
  src/rendering/RenderingMixins.d.ts
  src/rendering/renderers/autoDetectRenderer.ts
  src/rendering/renderers/gl/shader/program/getTestContext.ts
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/texture/CanvasPool.ts
  src/rendering/renderers/shared/texture/sources/CanvasSource.ts
  src/rendering/renderers/shared/texture/sources/ImageSource.ts
  src/rendering/renderers/shared/view/ViewSystem.ts
  src/scene/graphics/shared/fill/FillGradient.ts
  src/scene/text/bitmap/asset/loadBitmapFont.ts
  src/scene/text/bitmap/asset/xmlStringFormat.ts
  src/scene/text/canvas/CanvasTextMetrics.ts
  src/scene/text/html/utils/loadFontAsBase64.ts
  src/settings/SettingsMixins.d.ts
  src/settings/adapter/adapter.ts
  src/settings/settings.ts
  src/spritesheet/spritesheetAsset.ts
  src/utils/browser/isWebGLSupported.ts
  src/utils/browser/isWebGPUSupported.ts
  src/utils/isSafari.ts
  src/utils/network/getResolutionOfUrl.ts
  src/utils/path.ts
  src/utils/sayHello.ts
  types/PixiMixins.d.ts
Labels: v8

#9740 type change: update Application to accept Renderer as a type
  src/app/Application.ts
  src/rendering/renderers/gl/WebGLRenderer.ts
  src/rendering/renderers/gpu/WebGPURenderer.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/types.ts
  src/settings/adapter/ICanvas.ts
Labels: v8

#9744 Add resource to texture function
  src/assets/cache/Cache.ts
  src/extensions/Extensions.ts
  src/rendering/init.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/sources/BufferImageSource.ts
  src/rendering/renderers/shared/texture/sources/CanvasSource.ts
  src/rendering/renderers/shared/texture/sources/ImageSource.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/rendering/renderers/shared/texture/sources/VideoSource.ts
  src/rendering/renderers/shared/texture/sources/resourceToTexture.ts
  tests/renderering/extract/Extract.test.ts
  tests/renderering/textures/Textures.test.ts
Labels: v8

#9760 v8 ixed issue with resolving preferred formats
  src/assets/resolver/Resolver.ts
  tests/assets/Resolver.tests.ts
Labels: Backport to v7

#9763 v8 fix up blend mode for non-premultiplied-alpha
  src/rendering/batcher/shared/Batcher.ts
  src/rendering/renderers/shared/state/State.ts
  src/rendering/renderers/shared/state/const.ts
  src/rendering/renderers/shared/state/getAdjustedBlendModeBlend.ts
  tests/renderering/extract/Extract.test.ts
  tests/visual/scenes/text/html-text.scene.ts
  tests/visual/scenes/textures/blurredCircle.ts
  tests/visual/scenes/textures/non-premultiplied-alpha.scene.ts
  tests/visual/snapshots/webgl-non-premultiplied-alpha-scene-ts.png
  tests/visual/snapshots/webgpu-non-premultiplied-alpha-scene-ts.png
Labels: v8

#9707 Fix resuming video playback not working
  packages/core/src/textures/resources/VideoResource.ts
Labels: ✅ Ready To Merge

#9721 Update Assets docs
  packages/assets/src/Assets.ts
  packages/assets/src/resolver/Resolver.ts
Labels: ✅ Ready To Merge

#9748 Fix: Handle getShaderPrecisionFormat error
  packages/core/src/shader/utils/getMaxFragmentPrecision.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9750 Fix: logical condition in code for adding interactive elements
  packages/events/src/EventBoundary.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9772 Fix: Resolve the asset format with query parameters
  packages/assets/src/resolver/Resolver.ts
  packages/assets/src/resolver/parsers/resolveTextureUrl.ts
  packages/assets/test/resolver.tests.ts
  packages/compressed-textures/src/loaders/resolveCompressedTextureUrl.ts
Labels: ✅ Ready To Merge

#9776 v8 use the pixi cdn to get transcoders
  src/compressed-textures/basis/utils/setBasisTranscoderPath.ts
  src/compressed-textures/basis/worker/BasisWorker.ts
  src/compressed-textures/ktx/utils/setKTXTranscoderPath.ts
  src/compressed-textures/ktx/worker/KTXWorker.ts
Labels: v8

#9790 add more accessibility tests
  tests/accessibility/accessibleTarget.tests.ts
Labels: v8

#9793 Shader doc changes
  src/filters/Filter.ts
  src/rendering/init.ts
  src/rendering/renderers/gl/GlEncoderSystem.ts
  src/rendering/renderers/gl/context/GlContextSystem.ts
  src/rendering/renderers/gl/geometry/GlGeometrySystem.ts
  src/rendering/renderers/gl/shader/GlProgram.ts
  src/rendering/renderers/gl/shader/GlProgramData.ts
  src/rendering/renderers/gl/shader/GlShaderSystem.ts
  src/rendering/renderers/gl/shader/GlUniformGroupSystem.ts
  src/rendering/renderers/gl/shader/program/ensurePrecision.ts
  src/rendering/renderers/gl/shader/program/generateProgram.ts
  src/rendering/renderers/gl/shader/program/logProgramError.ts
  src/rendering/renderers/gl/shader/program/uniformParsers.ts
  src/rendering/renderers/gpu/BindGroupSystem.ts
  src/rendering/renderers/gpu/GpuDeviceSystem.ts
  src/rendering/renderers/gpu/shader/BindGroup.ts
  src/rendering/renderers/gpu/shader/BindResource.ts
  src/rendering/renderers/gpu/shader/GpuProgram.ts
  src/rendering/renderers/shared/shader/Shader.ts
  src/rendering/renderers/shared/shader/UniformGroup.ts
  src/rendering/renderers/types.ts
  tests/accessibility/accessibleTarget.tests.ts
Labels: v8

#9788 document accessibility, app, and assets
  .eslintrc.json
  package.json
  src/accessibility/AccessibilitySystem.ts
  src/accessibility/accessibilityTarget.ts
  src/app/Application.ts
  src/app/ApplicationMixins.d.ts
  src/app/ResizePlugin.ts
  src/app/TickerPlugin.ts
  src/app/init.ts
  src/assets/AssetExtension.ts
  src/assets/Assets.ts
  src/assets/BackgroundLoader.ts
  src/assets/cache/Cache.ts
  src/assets/cache/CacheParser.ts
  src/assets/cache/parsers/cacheTextureArray.ts
  src/assets/detections/parsers/detectAvif.ts
  src/assets/detections/parsers/detectDefaults.ts
  src/assets/detections/parsers/detectMp4.ts
  src/assets/detections/parsers/detectOgv.ts
  src/assets/detections/parsers/detectWebm.ts
  src/assets/detections/parsers/detectWebp.ts
  src/assets/detections/types.ts
  src/assets/loader/Loader.ts
  src/assets/loader/parsers/LoaderParser.ts
  src/assets/loader/parsers/loadJson.ts
  src/assets/loader/parsers/loadTxt.ts
  src/assets/loader/parsers/loadWebFont.ts
  src/assets/loader/parsers/textures/loadSVG.ts
  src/assets/loader/parsers/textures/loadTextures.ts
  src/assets/loader/parsers/textures/loadVideoTextures.ts
  src/assets/loader/parsers/textures/utils/createTexture.ts
  src/assets/loader/types.ts
  src/assets/resolver/Resolver.ts
  src/assets/resolver/parsers/resolveTextureUrl.ts
  src/assets/resolver/types.ts
  src/assets/types.ts
  src/environment/canvas/ICanvas.ts
  src/ticker/TickerMixins.d.ts
  src/utils/browser/isMobile.ts
  types/PixiMixins.d.ts
  webdoc.conf.json
Labels: v8

#9789 Doc pass for Shaders in v8
  src/filters/Filter.ts
  src/rendering/batcher/gpu/GpuBatchAdaptor.ts
  src/rendering/init.ts
  src/rendering/renderers/gl/GlEncoderSystem.ts
  src/rendering/renderers/gl/geometry/GlGeometrySystem.ts
  src/rendering/renderers/gl/shader/GlProgram.ts
  src/rendering/renderers/gl/shader/GlProgramData.ts
  src/rendering/renderers/gl/shader/GlShaderSystem.ts
  src/rendering/renderers/gl/shader/GlUniformGroupSystem.ts
  src/rendering/renderers/gl/shader/program/ensurePrecision.ts
  src/rendering/renderers/gl/shader/program/generateProgram.ts
  src/rendering/renderers/gl/shader/program/getAttributeData.ts
  src/rendering/renderers/gl/shader/program/getUniformBufferData.ts
  src/rendering/renderers/gl/shader/program/getUniformData.ts
  src/rendering/renderers/gl/shader/program/logProgramError.ts
  src/rendering/renderers/gl/shader/program/uniformParsers.ts
  src/rendering/renderers/gpu/BindGroupSystem.ts
  src/rendering/renderers/gpu/GpuEncoderSystem.ts
  src/rendering/renderers/gpu/shader/BindGroup.ts
  src/rendering/renderers/gpu/shader/BindResource.ts
  src/rendering/renderers/gpu/shader/GpuProgram.ts
  src/rendering/renderers/gpu/shader/generateGpuLayoutGroups.ts
  src/rendering/renderers/gpu/shader/generateLayoutHash.ts
  src/rendering/renderers/shared/shader/Shader.ts
  src/rendering/renderers/shared/shader/UniformBufferSystem.ts
  src/rendering/renderers/shared/shader/UniformGroup.ts
  tests/accessibility/accessibleTarget.tests.ts
  tests/renderering/BindGroup.test.ts
  tests/renderering/Shader.test.ts
  tests/visual/scenes/textures/non-premultiplied-alpha.scene.ts
Labels: v8

#9794 Document shared systems up to B
  src/rendering/init.ts
  src/rendering/renderers/autoDetectRenderer.ts
  src/rendering/renderers/gl/shader/GlShaderSystem.ts
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/gpu/BindGroupSystem.ts
  src/rendering/renderers/gpu/shader/BindGroup.ts
  src/rendering/renderers/gpu/shader/BindResource.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  src/rendering/renderers/shared/background/BackgroundSystem.ts
  src/rendering/renderers/shared/blendModes/BlendModePipe.ts
  src/rendering/renderers/shared/buffer/Buffer.ts
  src/rendering/renderers/shared/buffer/BufferResource.ts
  src/rendering/renderers/shared/buffer/const.ts
  src/rendering/renderers/shared/buffer/utils/fastCopy.ts
  src/rendering/renderers/shared/shader/Shader.ts
  src/rendering/renderers/shared/shader/UniformGroup.ts
  src/rendering/renderers/shared/texture/TextureGCSystem.ts
  src/rendering/renderers/shared/texture/TextureStyle.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  tests/renderering/BindGroup.test.ts
  tests/visual/tester.ts
  tests/visual/visuals.test.ts
Labels: v8

#9792 add application tests, fix EventSystem clean up bug
  src/events/EventSystem.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  tests/app/Application.tests.ts
  tests/utils/getApp.ts
  tests/utils/nextTick.ts
Labels: v8

#9798 remove `Writeable` type from the code base
  src/rendering/renderers/gl/GlEncoderSystem.ts
  src/rendering/renderers/gl/buffer/GlBufferSystem.ts
  src/rendering/renderers/gl/shader/GlProgram.ts
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/gpu/BindGroupSystem.ts
  src/rendering/renderers/gpu/GpuColorMaskSystem.ts
  src/rendering/renderers/gpu/GpuEncoderSystem.ts
  src/rendering/renderers/gpu/GpuStencilSystem.ts
  src/rendering/renderers/gpu/buffer/GpuBufferSystem.ts
  src/rendering/renderers/gpu/pipeline/PipelineSystem.ts
  src/rendering/renderers/gpu/renderTarget/GpuRenderTargetSystem.ts
  src/rendering/renderers/gpu/shader/GpuProgram.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  src/rendering/renderers/shared/buffer/Buffer.ts
  src/rendering/renderers/shared/extract/GenerateTextureSystem.ts
  src/rendering/renderers/shared/renderTarget/GlobalUniformSystem.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/scene/container/LayerSystem.ts
  src/scene/text/bitmap/AbstractBitmapFont.ts
  src/scene/text/bitmap/BitmapFont.ts
  src/scene/text/bitmap/DynamicBitmapFont.ts
  src/scene/text/canvas/CanvasTextMetrics.ts
  src/utils/types.ts
Labels: v8

#9797 fix text style update bug
  src/rendering/renderers/gl/GlEncoderSystem.ts
  src/rendering/renderers/gl/buffer/GlBufferSystem.ts
  src/rendering/renderers/gl/shader/GlProgram.ts
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/gpu/BindGroupSystem.ts
  src/rendering/renderers/gpu/GpuColorMaskSystem.ts
  src/rendering/renderers/gpu/GpuEncoderSystem.ts
  src/rendering/renderers/gpu/GpuStencilSystem.ts
  src/rendering/renderers/gpu/buffer/GpuBufferSystem.ts
  src/rendering/renderers/gpu/pipeline/PipelineSystem.ts
  src/rendering/renderers/gpu/renderTarget/GpuRenderTargetSystem.ts
  src/rendering/renderers/gpu/shader/GpuProgram.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  src/rendering/renderers/shared/buffer/Buffer.ts
  src/rendering/renderers/shared/extract/GenerateTextureSystem.ts
  src/rendering/renderers/shared/renderTarget/GlobalUniformSystem.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/scene/container/LayerSystem.ts
  src/scene/text/TextView.ts
  src/scene/text/bitmap/AbstractBitmapFont.ts
  src/scene/text/bitmap/BitmapFont.ts
  src/scene/text/bitmap/DynamicBitmapFont.ts
  src/scene/text/canvas/CanvasTextMetrics.ts
  src/utils/types.ts
  tests/visual/scenes/text/text.scene.ts
  tests/visual/snapshots/webgl-text-scene-ts.png
  tests/visual/snapshots/webgpu-text-scene-ts.png
Labels: v8

#9803 remove the texture listener on sprite view
  src/scene/sprite/SpriteView.ts
Labels: v8

#9806 fix premultiply alpha issue with the white texture
  src/rendering/renderers/shared/texture/sources/ImageSource.ts
  tests/renderering/textures/Textures.test.ts
Labels: v8

#9796 v8 added SDF visual test
  src/scene/text/sdfShader/SdfShader.ts
  src/scene/text/sdfShader/shader-bits/localUniformMSDFBit.ts
  src/scene/text/sdfShader/shader-bits/mSDFBit.ts
  tests/visual/assets/fonts/msdf/comicmsdf.fnt
  tests/visual/assets/fonts/msdf/fontmsdf.png
  tests/visual/assets/fonts/sdf/comicsdf.fnt
  tests/visual/assets/fonts/sdf/fontsdf.png
  tests/visual/scenes/text/msdf-text.scene.ts
  tests/visual/scenes/text/sdf-text.scene.ts
  tests/visual/snapshots/webgl-msdf-text-scene-ts.png
  tests/visual/snapshots/webgl-sdf-text-scene-ts.png
  tests/visual/snapshots/webgpu-msdf-text-scene-ts.png
  tests/visual/snapshots/webgpu-sdf-text-scene-ts.png
Labels: v8

#9805 docs for geometry
  src/rendering/renderers/shared/geometry/Geometry.ts
  src/rendering/renderers/shared/geometry/const.ts
  src/rendering/renderers/shared/geometry/utils/buildUvs.ts
  src/rendering/renderers/shared/geometry/utils/ensureIsBuffer.ts
  src/rendering/renderers/shared/geometry/utils/transformVertices.ts
Labels: v8

#9808 fix issue with font format not parsing if only id is provided
  src/scene/text/bitmap/asset/textFormat.ts
  tests/assets/TextFormat.test.ts
Labels: v8

#9813 docs for maths classes
  src/maths/matrix/Matrix.ts
  src/maths/matrix/groupD8.ts
  src/maths/misc/Size.ts
  src/maths/misc/const.ts
  src/maths/misc/pow2.ts
  src/maths/point/ObservablePoint.ts
  src/maths/point/Point.ts
  src/maths/point/PointData.ts
  src/maths/point/PointLike.ts
  src/maths/shapes/Circle.ts
  src/maths/shapes/Ellipse.ts
  src/maths/shapes/Polygon.ts
  src/maths/shapes/Rectangle.ts
  src/maths/shapes/RoundedRectangle.ts
  src/maths/shapes/ShapePrimitive.ts
  src/maths/shapes/Triangle.ts
  src/ticker/Ticker.ts
Labels: v8

#9795 Docs for color and environment
  src/color/Color.ts
  src/environment/adapter.ts
  src/environment/autoDetectEnvironment.ts
  src/environment/browser/BrowserAdapter.ts
  src/environment/browser/browserExt.ts
  src/environment/canvas/ICanvas.ts
  src/environment/canvas/ICanvasRenderingContext2D.ts
  src/environment/webworker/WebWorkerAdapter.ts
  src/environment/webworker/webworkerExt.ts
Labels: v8

#9810 add extensions tests
  tests/extensions/extensions.tests.ts
Labels: v8

#9811 add filter tests
  tests/filter-alpha/AlphaFilter.tests.ts
  tests/filter-blur/BlurFilter.tests.ts
  tests/filter-color-matrix/ColorMatrixFilter.tests.ts
Labels: v8

#9804 docs for events, filters, and extensions
  src/accessibility/AccessibilitySystem.ts
  src/assets/AssetExtension.ts
  src/assets/loader/parsers/textures/loadTextures.ts
  src/events/EventBoundary.ts
  src/events/EventBoundaryTypes.ts
  src/events/EventSystem.ts
  src/events/EventTicker.ts
  src/events/FederatedEvent.ts
  src/events/FederatedEventTarget.ts
  src/events/FederatedMouseEvent.ts
  src/events/FederatedPointerEvent.ts
  src/events/FederatedWheelEvent.ts
  src/events/init.ts
  src/extensions/Extensions.ts
  src/filters/defaults/alpha/AlphaFilter.ts
  src/filters/defaults/blur/BlurFilter.ts
  src/filters/defaults/blur/BlurFilterPass.ts
  src/filters/defaults/color-matrix/ColorMatrixFilter.ts
  src/filters/defaults/displacement/DisplacementFilter.ts
  src/filters/defaults/noise/NoiseFilter.ts
  src/filters/defaults/shockwave/ShockwaveFilter.ts
  src/maths/point/ObservablePoint.ts
  src/maths/point/Point.ts
  src/maths/shapes/Circle.ts
  src/maths/shapes/Ellipse.ts
  src/maths/shapes/Polygon.ts
  src/maths/shapes/Rectangle.ts
  src/maths/shapes/RoundedRectangle.ts
  src/rendering/renderers/gl/shader/GlUniformGroupSystem.ts
  src/rendering/renderers/shared/state/State.ts
  src/rendering/renderers/shared/system/SystemRunner.ts
  src/rendering/renderers/shared/texture/TextureUvs.ts
  src/scene/container/bounds/Bounds.ts
  src/utils/Transform.ts
  tests/accessibility/AccessibilitySystem.tests.ts
Labels: v8

#9812 add container mixin tests
  tests/mixin-get-child-by-name/getChildByName.tests.ts
  tests/mixin-get-global-position/getGlobalPosition.tests.ts
Labels: v8
