Repository pixijs/pixijs, pull requests merged in 2024-01, with the labels that each got.

#10030 Fix: path.join incorrectly joining urls that contain periods
  packages/utils/src/path.ts
  packages/utils/test/path.tests.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#10048 Chore/rename-rg
  src/scene/container/Container.ts
  src/scene/container/RenderGroup.ts
  src/scene/container/bounds/getFastGlobalBounds.ts
  src/scene/container/utils/buildInstructions.ts
  src/scene/container/utils/updateRenderGroupTransforms.ts
  src/scene/graphics/shared/BatchableGraphics.ts
  src/scene/graphics/shared/GraphicsPipe.ts
  src/scene/mesh/shared/BatchableMesh.ts
  src/scene/mesh/shared/MeshPipe.ts
  src/scene/sprite-tiling/TilingSpritePipe.ts
  src/scene/sprite/BatchableSprite.ts
  src/scene/text-bitmap/BitmapTextPipe.ts
  src/utils/logging/logScene.ts
  tests/display/Container.Visual.tests.ts
  tests/display/Container.tests.ts
  tests/scene/transform-alpha.tests.ts
  tests/scene/transform-blend.tests.ts
  tests/scene/transform-tint.tests.ts
  tests/scene/transform.tests.ts
Labels: v8

#10005 fix depthTexture issue
  src/rendering/renderers/shared/renderTarget/RenderTarget.ts
Labels: v8

#10049 v8 rename `onUpdate` to `_onUpdate`
  src/maths/point/ObservablePoint.ts
  src/scene/container/Container.ts
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/sprite/Sprite.ts
  src/scene/text-html/HTMLTextPipe.ts
  src/scene/text/Text.ts
  src/utils/misc/Transform.ts
  tests/math-extras/Point.tests.ts
  tests/math/ObservablePoint.tests.ts
  tests/scene/DummyView.ts
  tests/scene/transform-tint.tests.ts
Labels: v8

#10051 fix: stop text warning when using detectRenderMode
  src/scene/text/utils/detectRenderType.ts
Labels: v8

#10050 Fix: path.join incorrectly joining urls that contain periods (v8)
  src/utils/path.ts
  tests/renderering/utils/path.test.ts
Labels: v8

#10031 chore: add shader.from
  src/filters/Filter.ts
  src/rendering/renderers/shared/shader/Shader.ts
Labels: v8

#10052 Feat: add graphics clone
  src/scene/graphics/shared/Graphics.ts
  src/scene/graphics/shared/GraphicsContext.ts
  tests/visual/scenes/graphics/circle-clone.scene.ts
  tests/visual/snapshots/circle-clone-scene-ts-webgl1.png
  tests/visual/snapshots/circle-clone-scene-ts-webgl2.png
  tests/visual/snapshots/circle-clone-scene-ts-webgpu.png
Labels: v8

#10033 chore: update dependencies
  .eslintrc.json
  package-lock.json
  package.json
  src/accessibility/AccessibilitySystem.ts
  src/events/EventBoundaryTypes.ts
  src/rendering/mask/alpha/AlphaMaskPipe.ts
  src/rendering/renderers/gl/buffer/GlBufferSystem.ts
  src/rendering/renderers/gl/context/GlContextSystem.ts
  src/rendering/renderers/shared/shader/utils/createUniformBufferSync.ts
  src/rendering/renderers/shared/texture/TexturePool.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/scene/container/Container.ts
  src/scene/graphics/shared/Graphics.ts
  src/scene/graphics/shared/buildCommands/buildAdaptiveBezier.ts
  tests/renderering/Buffer.test.ts
  types/PixiMixins.d.ts
  types/Shaders.d.ts
Labels: v8

#10032 Chore: remove ObjectPool and update docs
  src/color/Color.ts
  src/events/FederatedEventTarget.ts
  src/maths/misc/const.ts
  src/maths/shapes/Ellipse.ts
  src/maths/shapes/Polygon.ts
  src/maths/shapes/Triangle.ts
  src/rendering/renderers/shared/shader/UniformBufferSystem.ts
  src/scene/container/bounds/getFastGlobalBounds.ts
  src/scene/container/bounds/getGlobalBounds.ts
  src/scene/container/bounds/getLocalBounds.ts
  src/scene/container/bounds/utils/matrixAndBoundsPool.ts
  src/ticker/Ticker.ts
Labels: v8

#10025 flatten TextureSource.style options
  src/rendering/renderers/shared/texture/TextureStyle.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/scene/graphics/shared/fill/FillGradient.ts
  tests/renderering/extract/Extract.test.ts
Labels: v8

#10053 Fix: alpha transparency
  src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts
  tests/visual/scenes/textures/render-texture.scene.ts
  tests/visual/snapshots/render-texture-scene-ts-webgl1.png
  tests/visual/snapshots/render-texture-scene-ts-webgl2.png
  tests/visual/snapshots/render-texture-scene-ts-webgpu.png
Labels: v8

#10056 chore: strict null checks for extensions
  src/extensions/Extensions.ts
  tests/extensions/extensions.tests.ts
Labels: v8

#10055 Feat: Add signal and once option to addEventListener
  src/events/FederatedEventTarget.ts
  tests/events/EventSystem.tests.ts
Labels: v8

#9960 Fix: running on webworker
  package.json
  scripts/utils/exports.ts
  src/accessibility/AccessibilitySystem.ts
  src/assets/Assets.ts
  src/assets/init.ts
  src/environment/browser/browserAll.ts
  src/environment/webworker/webworkerAll.ts
  src/rendering/renderers/gl/GlBackBufferSystem.ts
  src/rendering/renderers/shared/renderTarget/isRenderingToScreen.ts
  src/rendering/renderers/shared/texture/sources/ImageSource.ts
  src/scene/graphics/shared/GraphicsContext.ts
  src/scene/text-bitmap/init.ts
  src/scene/text/TextStyle.ts
  tests/accessibility/AccessibilitySystem.tests.ts
  tests/renderering/graphics/Graphics.test.ts
Labels: v8

#10058 Fix: displacement scale y not updating
  src/filters/FilterSystem.ts
  src/filters/defaults/displacement/displacement.wgsl
  src/rendering/renderers/shared/shader/utils/createUBOElements.ts
Labels: v8

#9961 Fix: bundle builds
  .eslintignore
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  rollup.config.mjs
  scripts/index/generateIndexFiles.ts
  scripts/index/index.ts
  scripts/utils/exports.ts
  src/assets/loader/parsers/textures/loadTextures.ts
  src/assets/loader/workers/WorkerManager.ts
  src/assets/loader/workers/checkImageBitmap.worker.js
  src/assets/loader/workers/loadImageBitmap.worker.js
  src/bundle.browser.ts
  src/bundle.math-extras.ts
  src/bundle.unsafe-eval.ts
  src/bundle.webworker.ts
  src/compressed-textures/basis/worker/basis.worker.ts
  src/compressed-textures/basis/worker/loadBasisOnWorker.ts
  src/compressed-textures/ktx/worker/ktx.worker.ts
  src/compressed-textures/ktx/worker/loadKTXonWorker.ts
  src/environment-browser/BrowserAdapter.ts
  src/environment-browser/browserAll.ts
  src/environment-browser/browserExt.ts
  src/environment-webworker/WebWorkerAdapter.ts
  src/environment-webworker/webworkerAll.ts
  src/environment-webworker/webworkerExt.ts
  src/environment/adapter.ts
  src/environment/autoDetectEnvironment.ts
  src/environment/browser/browserAll.ts
  src/environment/webworker/webworkerAll.ts
  src/index.ts
  src/math-extras/init.ts
  src/math-extras/pointExtras.ts
  src/math-extras/rectangleExtras.ts
  src/rendering/renderers/shared/texture/sources/ImageSource.ts
  tests/events/EventSystem.tests.ts
  tests/graphics/Graphics.AdaptiveBezierSmoothing.tests.ts
  tests/math-extras/Rectangle.tests.ts
  tests/renderering/RoundPixels.test.ts
  tests/renderering/textures/VideoSource.test.ts
  tests/utils/getApp.ts
  tests/utils/getRenderer.ts
  tests/visual/visuals.test.ts
  tsconfig.types.json
  types/Temp.d.ts
Labels: v8

#10059 chore: deprecate app.view
  src/app/Application.ts
  src/assets/loader/parsers/textures/utils/createTexture.ts
  src/rendering/renderers/shared/view/ViewSystem.ts
Labels: v8

#9487 Support VideoFrame as a Texture resource.
  packages/core/src/textures/BaseTexture.ts
  packages/core/src/textures/resources/BaseImageResource.ts
  packages/core/src/textures/resources/VideoFrameResource.ts
  packages/core/src/textures/resources/index.ts
  packages/core/test/autoDetectResource.tests.ts
  packages/settings/src/ICanvasRenderingContext2D.ts
Labels: ✅ Ready To Merge

#9920 Add data.texture and data.imageFilename to spritesheetLoader
  packages/spritesheet/src/Spritesheet.ts
  packages/spritesheet/src/spritesheetAsset.ts
  packages/spritesheet/test/spritesheetAsset.tests.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#9948 Feature: Make Runner type-safe
  packages/runner/src/Runner.ts
  packages/runner/test/Runner.tests.ts
Labels: ✅ Ready To Merge

#10022 Add strict null checks to @pixijs/runner
  packages/runner/src/Runner.ts
  packages/runner/test/Runner.tests.ts
  scripts/filterTypeScriptErrors.ts
Labels: ✅ Ready To Merge

#10027 Add strict null checks to @pixi/extensions
  packages/extensions/src/index.ts
  packages/extensions/test/extensions.tests.ts
  scripts/filterTypeScriptErrors.ts
Labels: 💞 Migrate to v8

#10060 Fix: gpu sprite being undefined
  src/scene/sprite/SpritePipe.ts
Labels: v8

#10061 Fix: render group issue causing canvas.extract to be wrong
  src/scene/container/Container.ts
  src/scene/container/RenderGroup.ts
  src/scene/container/RenderGroupSystem.ts
  src/scene/container/bounds/Bounds.ts
  src/scene/container/bounds/getFastGlobalBounds.ts
  src/scene/container/bounds/getLocalBounds.ts
  src/scene/container/bounds/getRenderableBounds.ts
  src/scene/container/utils/buildInstructions.ts
  src/scene/container/utils/updateRenderGroupTransforms.ts
  src/scene/text-bitmap/BitmapTextPipe.ts
  src/utils/logging/logScene.ts
  tests/display/Container.Visual.tests.ts
  tests/scene/transform-visibiity.tests.ts
  tests/scene/transform.tests.ts
  tests/visual/scenes/container/render-group.scene.ts
  tests/visual/snapshots/render-group-scene-ts-webgl1.png
  tests/visual/snapshots/render-group-scene-ts-webgl2.png
  tests/visual/snapshots/render-group-scene-ts-webgpu.png
Labels: v8

#10047 Add support for 'signal' option to FederatedEventTarget.addEventListener
  packages/events/src/FederatedEventTarget.ts
  packages/events/test/EventSystem.tests.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#10074 fix: calling FederatedEventTarget.off() with original listener now works when using signal
  packages/events/src/FederatedEventTarget.ts
  packages/events/test/EventSystem.tests.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#10066 Fix: buffer firing multiple events
  src/rendering/renderers/gpu/buffer/GpuBufferSystem.ts
  tests/accessibility/AccessibilitySystem.tests.ts
  tests/accessibility/accessibleTarget.tests.ts
  tests/events/EventSystem.tests.ts
  tests/prepare/PrepareSystem.test.ts
  tests/renderering/Buffer.test.ts
  tests/renderering/Geometry.test.ts
  tests/renderering/GlBackBufferSystem.test.ts
  tests/renderering/State.test.ts
  tests/renderering/extract/Extract.test.ts
  tests/renderering/graphics/Graphics.Destroy.test.ts
  tests/renderering/mesh/Mesh.test.ts
  tests/renderering/scene/RenderGroupSystem.test.ts
  tests/renderering/sprite/Sprite.test.ts
  tests/renderering/sprite/TilingSprite.test.ts
  tests/renderering/text/BitmapFontLoader.tests.ts
  tests/renderering/text/BitmapText.tests.ts
  tests/renderering/text/Text.tests.ts
  tests/renderering/textures/GLTextureSystem.test.ts
  tests/renderering/textures/GenerateTexture.test.ts
  tests/renderering/utils/detectVideoAlphaMode.test.ts
  tests/utils/getRenderer.ts
  tests/utils/localTest.ts
Labels: v8

#10067 Fix: background color not being set correctly
  src/rendering/renderers/shared/system/AbstractRenderer.ts
Labels: v8

#10063 Fix: prevent error when creating text with anchor option
  src/scene/text/Text.ts
Labels: v8

#10071 Fix: environment extensions being treeshaken
  package.json
  scripts/utils/exports.ts
  src/rendering/init.ts
Labels: v8

#10075 Fix: constructor options not being set correctly
  src/scene/graphics/shared/Graphics.ts
  src/scene/mesh/shared/Mesh.ts
  src/scene/sprite-nine-slice/NineSliceSprite.ts
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/sprite/Sprite.ts
  src/scene/text/Text.ts
Labels: v8

#10068 Fix: masks not rendering correctly when nested
  src/rendering/renderers/gpu/state/GpuStencilModesToPixi.ts
  tests/visual/scenes/mask/nested-mask.scene.ts
  tests/visual/snapshots/nested-mask-scene-ts-webgl1.png
  tests/visual/snapshots/nested-mask-scene-ts-webgl2.png
  tests/visual/snapshots/nested-mask-scene-ts-webgpu.png
Labels: v8

#10062 Fix: filter issue with skipped filter effects
  src/filters/FilterSystem.ts
  src/scene/container/container-mixins/effectsMixin.ts
  tests/scene/filter-effect.tests.ts
  tests/visual/scenes/container/skip-filter.scene.ts
  tests/visual/snapshots/skip-filter-scene-ts-webgl1.png
  tests/visual/snapshots/skip-filter-scene-ts-webgl2.png
  tests/visual/snapshots/skip-filter-scene-ts-webgpu.png
Labels: v8

#10077 Fix: uniforms generation not working with bundlers
  src/rendering/renderers/gl/shader/program/generateUniformsSyncTypes.ts
  src/rendering/renderers/shared/shader/utils/createUniformBufferSync.ts
  src/rendering/renderers/shared/shader/utils/createUniformBufferSyncTypes.ts
  src/rendering/renderers/shared/shader/utils/uniformBufferParsers.ts
  src/unsafe-eval/generateUniformBufferSyncPolyfill.ts
Labels: v8

#9399 Move worker codes to seperate files
  global.d.ts
  jest.config.js
  package-lock.json
  package.json
  packages/assets/src/loader/parsers/WorkerManager.ts
  packages/assets/src/loader/parsers/workers/checkImageBitmap.worker.ts
  packages/assets/src/loader/parsers/workers/loadImageBitmap.worker.ts
  packages/assets/src/loader/parsers/workers/tsconfig.json
  packages/core/package.json
  rollup.config.mjs
  tsconfig.json
  tsconfig.types.json
  tsconfig.worker.json
Labels: ✅ Ready To Merge

#10080 fix up uniform parsers
  src/rendering/renderers/gl/shader/program/generateUniformsSync.ts
  src/rendering/renderers/gl/shader/program/uniformParsers.ts
  src/unsafe-eval/generateUniformsSyncPolyfill.ts
Labels: v8

#10079 fix: calling FederatedEventTarget.off() with original listener now works when using signal
  src/events/FederatedEventTarget.ts
  tests/events/EventSystem.tests.ts
Labels: v8

#10082 v8 Fix render effects issue
  src/scene/container/utils/buildInstructions.ts
Labels: v8

#10083 Fix: transparency for WebGPU and default tint for BitmapText
  src/rendering/renderers/gpu/renderTarget/GpuRenderTargetAdaptor.ts
  src/rendering/renderers/shared/texture/sources/CanvasSource.ts
  src/rendering/renderers/shared/view/ViewSystem.ts
  src/scene/container/utils/buildInstructions.ts
  src/scene/text/Text.ts
Labels: v8

#10081 Fix: Mesh rendering
  src/rendering/renderers/gl/GlEncoderSystem.ts
  src/rendering/renderers/gl/context/GlContextSystem.ts
  src/rendering/renderers/gl/context/WebGLExtensions.ts
  src/rendering/renderers/gl/geometry/GlGeometrySystem.ts
  src/rendering/renderers/gl/geometry/utils/getGlInfoFromFormat.ts
  src/rendering/renderers/gl/geometry/utils/getGlTypeFromFormat.ts
  src/rendering/renderers/gpu/GpuEncoderSystem.ts
  src/rendering/renderers/gpu/pipeline/PipelineSystem.ts
  src/rendering/renderers/shared/geometry/Geometry.ts
  src/rendering/renderers/shared/shader/Shader.ts
  src/rendering/renderers/shared/shader/utils/getUniformInfoFromFormat.ts
  src/scene/mesh/gl/GlMeshAdaptor.ts
  src/scene/mesh/gpu/GpuMeshAdapter.ts
  src/scene/mesh/shared/Mesh.ts
  src/scene/mesh/shared/MeshPipe.ts
  tests/visual/assets/bg_scene_rotate.jpg
  tests/visual/scenes/mesh/custom-mesh-instanced.scene.ts
  tests/visual/scenes/mesh/custom-mesh.scene.ts
  tests/visual/scenes/mesh/triangle.scene.ts
  tests/visual/snapshots/custom-mesh-instanced-scene-ts-webgl1.png
  tests/visual/snapshots/custom-mesh-instanced-scene-ts-webgl2.png
  tests/visual/snapshots/custom-mesh-instanced-scene-ts-webgpu.png
  tests/visual/snapshots/custom-mesh-scene-ts-webgl1.png
  tests/visual/snapshots/custom-mesh-scene-ts-webgl2.png
  tests/visual/snapshots/custom-mesh-scene-ts-webgpu.png
  tests/visual/snapshots/triangle-scene-ts-webgl1.png
  tests/visual/snapshots/triangle-scene-ts-webgl2.png
  tests/visual/snapshots/triangle-scene-ts-webgpu.png
Labels: v8

#10088 Fix: mipmap issue with WebGL1
  src/rendering/renderers/gl/context/GlContextSystem.ts
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/scene/sprite/Sprite.ts
  src/scene/text/Text.ts
  tests/visual/assets/bunny.1.png
  tests/visual/assets/bunny.png
  tests/visual/assets/profile-abel@2x.jpg
  tests/visual/scenes/sprite/sprite.scene.ts
  tests/visual/scenes/textures/mipmap.scene.ts
  tests/visual/snapshots/mipmap-scene-ts-webgl1.png
  tests/visual/snapshots/mipmap-scene-ts-webgl2.png
  tests/visual/snapshots/mipmap-scene-ts-webgpu.png
Labels: v8

#10089 Fix: issue with antialiased filters on WebGL2
  src/filters/Filter.ts
  src/filters/FilterSystem.ts
  src/filters/defaults/alpha/AlphaFilter.ts
  src/filters/defaults/blur/BlurFilter.ts
  src/filters/defaults/color-matrix/ColorMatrixFilter.ts
  src/filters/defaults/displacement/DisplacementFilter.ts
  src/filters/defaults/noise/NoiseFilter.ts
  src/filters/mask/MaskFilter.ts
  tests/visual/scenes/filters/anitalias-filter.scene.ts
  tests/visual/snapshots/anitalias-filter-scene-ts-webgl1.png
  tests/visual/snapshots/anitalias-filter-scene-ts-webgl2.png
  tests/visual/snapshots/anitalias-filter-scene-ts-webgpu.png
Labels: v8

#10092 Fix: nine slice not updating correctly
  src/filters/FilterSystem.ts
  src/scene/sprite-nine-slice/NineSliceGeometry.ts
  src/scene/sprite-nine-slice/NineSliceSprite.ts
  tests/visual/assets/big-rect-button-border.png
  tests/visual/scenes/sprite/nine-slice.scene.ts
  tests/visual/snapshots/nine-slice-scene-ts-webgl1.png
  tests/visual/snapshots/nine-slice-scene-ts-webgl2.png
  tests/visual/snapshots/nine-slice-scene-ts-webgpu.png
Labels: v8

#10095 Fix: issues with TextStyle getter/setters and BitmapText default fill
  src/scene/text/Text.ts
  src/scene/text/TextStyle.ts
  tests/renderering/text/BitmapText.tests.ts
  tests/visual/scenes/text/bitmap-text.scene.ts
Labels: v8

#10099 Fix: graphics destroy, drawing regular polygon, and setting render group parent
  src/scene/container/RenderGroupSystem.ts
  src/scene/container/bounds/getFastGlobalBounds.ts
  src/scene/container/bounds/getGlobalBounds.ts
  src/scene/graphics/shared/GraphicsPipe.ts
  src/scene/graphics/shared/path/ShapePath.ts
  tests/renderering/graphics/Graphics.test.ts
  tests/visual/scenes/graphics/regular-poly.scene.ts
  tests/visual/snapshots/regular-poly-scene-ts-webgl1.png
  tests/visual/snapshots/regular-poly-scene-ts-webgl2.png
  tests/visual/snapshots/regular-poly-scene-ts-webgpu.png
Labels: v8

#10100 Tweaks to visual tests
  jest.config.js
  src/filters/FilterSystem.ts
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  tests/visual/tester.ts
  tests/visual/visuals.test.ts
Labels: v8

#10094 added context loss set up to WebGL
  .github/workflows/nodejs.yml
  jest.config.js
  src/filters/FilterSystem.ts
  src/rendering/batcher/gl/GlBatchAdaptor.ts
  src/rendering/batcher/shared/BatcherPipe.ts
  src/rendering/renderers/gl/buffer/GlBufferSystem.ts
  src/rendering/renderers/gl/context/GlContextSystem.ts
  src/rendering/renderers/gl/geometry/GlGeometrySystem.ts
  src/rendering/renderers/gl/shader/GlShaderSystem.ts
  src/rendering/renderers/gl/state/GlStateSystem.ts
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/gpu/renderTarget/GlRenderTargetAdaptor.ts
  src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts
  tests/utils/getRenderer.ts
  tests/visual/tester.ts
  tests/visual/visuals.test.ts
Labels: v8

#10091 Breaking: load svgs as texture instead of graphics by default
  .github/workflows/nodejs.yml
  jest.config.js
  src/assets/Assets.ts
  src/assets/loader/parsers/textures/loadSVG.ts
  src/assets/types.ts
  src/filters/FilterSystem.ts
  src/rendering/batcher/gl/GlBatchAdaptor.ts
  src/rendering/batcher/shared/BatcherPipe.ts
  src/rendering/renderers/gl/buffer/GlBufferSystem.ts
  src/rendering/renderers/gl/context/GlContextSystem.ts
  src/rendering/renderers/gl/geometry/GlGeometrySystem.ts
  src/rendering/renderers/gl/shader/GlShaderSystem.ts
  src/rendering/renderers/gl/state/GlStateSystem.ts
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/gpu/renderTarget/GlRenderTargetAdaptor.ts
  src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts
  tests/assets/loader.tests.ts
  tests/utils/getRenderer.ts
  tests/visual/assets/logo.svg
  tests/visual/scenes/graphics/svg-graphics-context.scene.ts
  tests/visual/scenes/graphics/svg-texture.scene.ts
  tests/visual/snapshots/svg-graphics-context-scene-ts-webgl1.png
  tests/visual/snapshots/svg-graphics-context-scene-ts-webgl2.png
  tests/visual/snapshots/svg-graphics-context-scene-ts-webgpu.png
  tests/visual/snapshots/svg-texture-scene-ts-webgl1.png
  tests/visual/snapshots/svg-texture-scene-ts-webgl2.png
  tests/visual/snapshots/svg-texture-scene-ts-webgpu.png
  tests/visual/tester.ts
  tests/visual/visuals.test.ts
Labels: v8

#10101 Chore: only add the artifacts if they fail
  tests/visual/tester.ts
  tests/visual/visuals.test.ts
Labels: v8

#10109 Chore: split CI into multiple workflows
  .editorconfig
  .github/actions/lint/action.yml
  .github/actions/setup/action.yml
  .github/actions/unit/action.yml
  .github/workflows/nodejs.yml
  .github/workflows/pull-unit.yml
  .github/workflows/pull-visuals.yml
  .github/workflows/push.yml
  .github/workflows/release-unit.yml
  .github/workflows/release-visuals.yml
  .github/workflows/release.yml
  .github/workflows/trigger-website-build.yml
  package.json
Labels: v8

#10103 Fix: types for anchor and tiling sprite transforms
  .editorconfig
  .github/actions/lint/action.yml
  .github/actions/setup/action.yml
  .github/actions/unit/action.yml
  .github/workflows/nodejs.yml
  .github/workflows/pull-unit.yml
  .github/workflows/pull-visuals.yml
  .github/workflows/push.yml
  .github/workflows/release-unit.yml
  .github/workflows/release-visuals.yml
  .github/workflows/release.yml
  .github/workflows/trigger-website-build.yml
  package.json
  src/scene/container/Container.ts
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/sprite/Sprite.ts
Labels: v8

#10104 Feat: add clear function to renderer
  src/rendering/mask/stencil/StencilMaskPipe.ts
  src/rendering/renderers/gpu/GpuEncoderSystem.ts
  src/rendering/renderers/gpu/renderTarget/GpuRenderTargetAdaptor.ts
  src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
Labels: v8

#10111 Fix: only call restoreContext if forceContextLoss was called
  src/rendering/renderers/gl/context/GlContextSystem.ts
Labels: v8

#10107 Fix: stencil issue with nested renderGroups and bounds caching issue
  src/rendering/mask/stencil/StencilMaskPipe.ts
  src/rendering/renderers/gpu/state/GpuStencilModesToPixi.ts
  src/scene/container/bounds/getLocalBounds.ts
  src/scene/container/utils/checkChildrenDidChange.ts
  tests/scene/checkChildrenDidChange.tests.ts
  tests/scene/getLocalBounds.tests.ts
Labels: v8

#10113 Use `GpuProgram.from` in filters
  src/filters/blend-modes/BlendModeFilter.ts
  src/filters/defaults/alpha/AlphaFilter.ts
  src/filters/defaults/noise/NoiseFilter.ts
Labels: v8

#10110 Feat: allow devs to add `#version 300 es` to shaders
  src/rendering/renderers/gl/shader/GlProgram.ts
  src/rendering/renderers/gl/shader/program/preprocessors/addProgramDefines.ts
  src/rendering/renderers/gl/shader/program/preprocessors/ensurePrecision.ts
  src/rendering/renderers/gl/shader/program/preprocessors/insertVersion.ts
  src/rendering/renderers/gl/shader/program/preprocessors/setProgramName.ts
  src/rendering/renderers/gl/shader/program/preprocessors/stripVersion.ts
  src/rendering/renderers/gl/shader/program/setProgramVersion.ts
  src/rendering/renderers/shared/geometry/utils/getGeometryBounds.ts
Labels: v8

#10116 Feat: add ability to set width/height of Container together
  src/scene/container/container-mixins/measureMixin.ts
  tests/display/Container.Visual.tests.ts
Labels: v8

#10118 Breaking: smarter geometry attributes
  src/filters/FilterSystem.ts
  src/rendering/batcher/gpu/BatchGeometry.ts
  src/rendering/renderers/gl/GlBackBufferSystem.ts
  src/rendering/renderers/gl/geometry/GlGeometrySystem.ts
  src/rendering/renderers/gl/shader/GlProgram.ts
  src/rendering/renderers/gl/shader/program/ensureAttributes.ts
  src/rendering/renderers/gl/shader/program/generateProgram.ts
  src/rendering/renderers/gl/shader/program/getAttributeData.ts
  src/rendering/renderers/gl/shader/program/getTestContext.ts
  src/rendering/renderers/gl/shader/program/mapType.ts
  src/rendering/renderers/gpu/GpuEncoderSystem.ts
  src/rendering/renderers/gpu/pipeline/PipelineSystem.ts
  src/rendering/renderers/gpu/shader/GpuProgram.ts
  src/rendering/renderers/gpu/shader/utils/extractAttributesFromGpuProgram.ts
  src/rendering/renderers/gpu/shader/utils/extractStructAndGroups.ts
  src/rendering/renderers/gpu/shader/utils/generateGpuLayoutGroups.ts
  src/rendering/renderers/gpu/shader/utils/generateLayoutHash.ts
  src/rendering/renderers/gpu/shader/utils/removeStructAndGroupDuplicates.ts
  src/rendering/renderers/shared/geometry/Geometry.ts
  src/rendering/renderers/shared/shader/utils/extractAttributesFromGlProgram.ts
  src/scene/mesh/shared/MeshGeometry.ts
  tests/renderering/Geometry.test.ts
  tests/renderering/extractAttributesFromGpuProgram.test.ts
  tests/renderering/glEnsureAttributes.test.ts
  tests/utils/getGeometry.ts
  tests/visual/scenes/mesh/custom-mesh-instanced.scene.ts
  tests/visual/scenes/mesh/custom-mesh.scene.ts
  tests/visual/scenes/mesh/triangle.scene.ts
Labels: v8

#10121 Fix: add State to Mesh constructor
  src/scene/mesh/shared/Mesh.ts
Labels: v8

#10125 Add: Spritesheet option cachePrefix
  packages/spritesheet/src/Spritesheet.ts
  packages/spritesheet/src/spritesheetAsset.ts
  packages/spritesheet/test/Spritesheet.tests.ts
  packages/spritesheet/test/spritesheetAsset.tests.ts
Labels: ✅ Ready To Merge, 💞 Migrate to v8

#10123 Fix: Culler not accurately culling objects
  src/culling/Culler.ts
  tests/scene/culler.test.ts
Labels: v8

#10127 Feat: add Filter.from
  src/filters/Filter.ts
Labels: v8

#10143 Fix: attribute locations not being set automatically
  src/rendering/batcher/gpu/BatchGeometry.ts
  src/rendering/renderers/gl/shader/program/extractAttributesFromGlProgram.ts
  src/rendering/renderers/gl/shader/program/generateProgram.ts
  src/scene/mesh/shared/MeshGeometry.ts
Labels: v8

#10144 Fix: auto assignment of gpu pixi groups
  src/rendering/renderers/gpu/shader/GpuProgram.ts
  src/scene/mesh/gl/GlMeshAdaptor.ts
  src/scene/mesh/gpu/GpuMeshAdapter.ts
  tests/visual/scenes/mesh/fully-custom-mesh.scene.ts
Labels: v8

#10134 Feat: Allow for localTransform calculations to be overridden
  src/maths/matrix/Matrix.ts
  src/rendering/mask/utils/addMaskLocalBounds.ts
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/sources/CanvasSource.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/scene/container/Container.ts
  src/scene/container/bounds/getGlobalBounds.ts
  src/scene/container/bounds/getLocalBounds.ts
  src/scene/container/container-mixins/toLocalGlobalMixin.ts
  src/scene/container/utils/updateRenderGroupTransforms.ts
  src/scene/text/utils/getPo2TextureFromSource.ts
  tests/renderering/textures/TextureSource.test.ts
Labels: v8

#10139 Fix: masks not working correctly when sub rendering a container
  src/rendering/mask/stencil/StencilMaskPipe.ts
  src/rendering/renderers/shared/extract/GenerateTextureSystem.ts
Labels: v8

#10140 Fix: geometry buffer should listen to change event
  Notes.md
  src/rendering/renderers/shared/geometry/Geometry.ts
  tests/renderering/Geometry.test.ts
Labels: v8

#10141 Fix: update shaders to use correct uniform names
  src/rendering/high-shader/defaultProgramTemplate.ts
  src/rendering/high-shader/shader-bits/globalUniformsBit.ts
  src/rendering/renderers/shared/renderTarget/GlobalUniformSystem.ts
  tests/renderering/GlobalUniformSystem.test.ts
  tests/visual/scenes/mesh/custom-mesh-instanced.scene.ts
  tests/visual/scenes/mesh/custom-mesh.scene.ts
  tests/visual/scenes/mesh/triangle.scene.ts
Labels: v8

#10147 v8 Merge bugs
  src/rendering/batcher/gpu/BatchGeometry.ts
  src/rendering/high-shader/compiler/compileHighShader.ts
  src/rendering/renderers/gpu/pipeline/PipelineSystem.ts
  src/rendering/renderers/gpu/shader/GpuProgram.ts
  tests/visual/scenes/mesh/fully-custom-mesh.scene.ts
  tests/visual/snapshots/fully-custom-mesh-scene-ts-webgl1.png
  tests/visual/snapshots/fully-custom-mesh-scene-ts-webgl2.png
  tests/visual/snapshots/fully-custom-mesh-scene-ts-webgpu.png
Labels: v8

#10148 Fix: allow texture.from to accept resource directly
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/sources/resourceToTexture.ts
  tests/renderering/textures/Textures.test.ts
Labels: v8

#10149 Fix: add blend mode warning
  src/rendering/renderers/shared/blendModes/BlendModePipe.ts
Labels: v8

#10152 Fix: advanced blend modes not being bundled
  package.json
  rollup.config.mjs
  scripts/index/index.ts
  scripts/utils/exports.ts
  src/advanced-blend-modes/ColorBlend.ts
  src/advanced-blend-modes/ColorBurnBlend.ts
  src/advanced-blend-modes/ColorDodgeBlend.ts
  src/advanced-blend-modes/DarkenBlend.ts
  src/advanced-blend-modes/DifferenceBlend.ts
  src/advanced-blend-modes/DivideBlend.ts
  src/advanced-blend-modes/ExclusionBlend.ts
  src/advanced-blend-modes/HardLightBlend.ts
  src/advanced-blend-modes/HardMixBlend.ts
  src/advanced-blend-modes/LightenBlend.ts
  src/advanced-blend-modes/LinearBurnBlend.ts
  src/advanced-blend-modes/LinearDodgeBlend.ts
  src/advanced-blend-modes/LinearLightBlend.ts
  src/advanced-blend-modes/LuminosityBlend.ts
  src/advanced-blend-modes/NegationBlend.ts
  src/advanced-blend-modes/OverlayBlend.ts
  src/advanced-blend-modes/PinLightBlend.ts
  src/advanced-blend-modes/SaturationBlend.ts
  src/advanced-blend-modes/SoftLightBlend.ts
  src/advanced-blend-modes/SubtractBlend.ts
  src/advanced-blend-modes/VividLightBlend.ts
  src/advanced-blend-modes/init.ts
  src/bundle.advanced-blend-modes.ts
Labels: v8

#10146 v8: Fix for Texture GC and Resource Managment
  src/rendering/renderers/gl/texture/GlTextureSystem.ts
  src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/TextureGCSystem.ts
  src/rendering/renderers/shared/texture/TexturePool.ts
  src/rendering/renderers/shared/texture/sources/ImageSource.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  tests/renderering/textures/TextureSource.test.ts
Labels: v8

#10154 Fix: culler no longer overrides visible property
  src/culling/Culler.ts
  src/scene/container/Container.ts
  src/scene/container/RenderGroup.ts
  src/scene/container/bounds/getFastGlobalBounds.ts
  src/scene/container/bounds/getRenderableBounds.ts
  src/scene/container/utils/buildInstructions.ts
  src/scene/container/utils/updateRenderGroupTransforms.ts
  src/scene/text-bitmap/BitmapTextPipe.ts
  tests/display/Container.Visual.tests.ts
  tests/scene/culler.test.ts
  tests/scene/transform-visibiity.tests.ts
Labels: v8

#10156 v8 WebGL syncShader optimisation
  src/rendering/renderers/gl/geometry/GlGeometrySystem.ts
  src/rendering/renderers/gl/shader/GenerateShaderSyncCode.ts
  src/rendering/renderers/gl/shader/GlProgram.ts
  src/rendering/renderers/gl/shader/GlShaderSystem.ts
  src/rendering/renderers/gl/shader/GlUniformGroupSystem.ts
  src/rendering/renderers/gl/state/GlStateSystem.ts
  src/rendering/renderers/shared/geometry/Geometry.ts
  src/rendering/renderers/shared/shader/UniformGroup.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/unsafe-eval/init.ts
  src/unsafe-eval/shader/generateShaderSyncPolyfill.ts
  src/unsafe-eval/ubo/generateUboSyncPolyfill.ts
  src/unsafe-eval/ubo/uboSyncFunctions.ts
  src/unsafe-eval/uniforms/generateUniformsSyncPolyfill.ts
  src/unsafe-eval/uniforms/uniformSyncFunctions.ts
Labels: v8

#10157 Fix: remove eval in workers
  src/compressed-textures/basis/worker/basis.worker.ts
  src/compressed-textures/ktx/worker/ktx.worker.ts
Labels: v8

#10142 Fix: Sprite width/height so they work like v7.
  src/rendering/mask/utils/addMaskLocalBounds.ts
  src/scene/container/container-mixins/measureMixin.ts
  src/scene/sprite/Sprite.ts
  src/scene/text/Text.ts
Labels: v8

#10164 Fix: Texture.update not updating texture
  src/rendering/renderers/shared/texture/sources/CanvasSource.ts
Labels: v8

#10163 Fix: json url resolutions not being parsed
  src/assets/Assets.ts
  src/assets/resolver/parsers/resolveJsonUrl.ts
Labels: v8
