Repository pixijs/pixijs, pull requests merged in 2024-07, with the labels that each got.

#10601 fix: Event handlers firing twice on non-interacting root display objects
  src/events/EventBoundary.ts
  tests/events/EventBoundary.tests.ts
Labels: ✅ Ready To Merge, v8

#10677 fix: events firing twice when using dynamic mode
  src/events/EventTicker.ts
Labels: ✅ Ready To Merge, v8

#10687 fix: incorrect font family being applied to text
  src/scene/text-html/utils/getFontCss.ts
  tests/visual/scenes/text/html-text-family.scene.ts
  tests/visual/snapshots/html-text-family-scene-ts-webgl1.png
  tests/visual/snapshots/html-text-family-scene-ts-webgl2.png
  tests/visual/snapshots/html-text-family-scene-ts-webgpu.png
Labels: ✅ Ready To Merge, v8

#10667 fix: typos all around
  .husky/pre-commit
  src/assets/Assets.ts
  src/color/Color.ts
  src/compressed-textures/basis/transcoder/basis_transcoder.js
  src/filters/Filter.ts
  src/filters/defaults/color-matrix/ColorMatrixFilter.ts
  src/rendering/batcher/gpu/GpuBatchAdaptor.ts
  src/rendering/batcher/shared/Batcher.ts
  src/rendering/renderers/gl/GlBackBufferSystem.ts
  src/rendering/renderers/gl/shader/GenerateShaderSyncCode.ts
  src/rendering/renderers/gl/shader/GlUniformGroupSystem.ts
  src/rendering/renderers/gpu/shader/GpuProgram.ts
  src/rendering/renderers/shared/shader/Shader.ts
  src/rendering/renderers/shared/shader/UboSystem.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/rendering/renderers/types.ts
  src/scene/container/RenderContainer.ts
  src/scene/container/RenderGroup.ts
  src/scene/graphics/shared/utils/buildGeometryFromPath.ts
  src/scene/text-bitmap/BitmapTextPipe.ts
  src/scene/text-bitmap/DynamicBitmapFont.ts
  src/scene/text/canvas/CanvasTextMetrics.ts
  src/spritesheet/Spritesheet.ts
  src/utils/logging/deprecation.ts
  tests/extensions/extensions.tests.ts
  tests/math/Rectangle.tests.ts
  tests/renderering/graphics/Graphics.Drawing.test.ts
  tests/renderering/text/TextMetrics.tests.ts
  tests/renderering/textures/TextureSource.test.ts
  tests/scene/RenderGroup.tests.ts
Labels: ✅ Ready To Merge, v8

#10678 fix: Ensure `depthStencilRenderBuffer` gets resized when render target has depth enabled
  src/rendering/renderers/gl/renderTarget/GlRenderTargetAdaptor.ts
Labels: ✅ Ready To Merge, v8

#10689 chore: update workflows
  .github/workflows/pull-unit.yml
  .github/workflows/pull-visuals.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
Labels: v8

#10691 fix: triple slash reference in types files
  types/Jest.d.ts
  types/PixiMixins.d.ts
  types/Shaders.d.ts
Labels: v8

#10690 chore: update pre commit
  .husky/pre-commit
  package-lock.json
  package.json
Labels: v8

#10694 fix: ensure data is passed to loader
  src/assets/loader/Loader.ts
  tests/assets/assets.tests.ts
  tests/assets/assets/spritesheet/svgSpritesheet.json
  tests/assets/assets/spritesheet/svgSpritesheet.svg
  tests/renderering/sprite/spritesheetAsset.tests.ts
Labels: v8

#10693 fix: GpuBufferSystem Managed Buffers
  src/rendering/renderers/gpu/buffer/GpuBufferSystem.ts
Labels: ✅ Ready To Merge, v8

#10695 fix: passing 0 width/height to AbstractText/Sprite constructor
  src/scene/sprite/Sprite.ts
  src/scene/text/AbstractText.ts
Labels: v8

#10686 fix: Filter constructor blendMode option
  src/filters/Filter.ts
  src/filters/defaults/blur/BlurFilter.ts
Labels: ✅ Ready To Merge, v8

#10698 fix: create instructionSet parameter from addToBatch
  src/rendering/renderers/shared/instructions/RenderPipe.ts
  src/scene/graphics/shared/GraphicsPipe.ts
  src/scene/text-html/HTMLTextPipe.ts
Labels: ✅ Ready To Merge, v8

#10699 fix: BatchGeometry location
  src/rendering/batcher/shared/BatchGeometry.ts
  src/rendering/batcher/shared/BatcherPipe.ts
  src/scene/graphics/shared/GraphicsContextSystem.ts
Labels: ✅ Ready To Merge, v8

#10717 fix: Ellipse#getBounds ignoring out parameter
  src/maths/shapes/Ellipse.ts
Labels: ✅ Ready To Merge, v8

#10705 fix: maxTextures argument of generateTextureBatchBit
  src/rendering/high-shader/shader-bits/generateTextureBatchBit.ts
Labels: ✅ Ready To Merge, v8

#10707 fix: _didLocalTransformChangeId check
  src/scene/container/Container.ts
Labels: ✅ Ready To Merge, v8

#10711 fix: Batch Pooling
  src/rendering/batcher/shared/Batcher.ts
  src/rendering/renderers/shared/shader/Shader.ts
  tests/visual/assets/fonts/msdf/Roboto-Regular.fnt
  tests/visual/assets/fonts/msdf/atlas.0.png
  tests/visual/assets/fonts/msdf/atlas.1.png
  tests/visual/assets/fonts/msdf/atlas.2.png
  tests/visual/assets/fonts/msdf/atlas.3.png
  tests/visual/assets/fonts/msdf/atlas.4.png
  tests/visual/assets/fonts/msdf/comicmsdf.fnt
  tests/visual/assets/fonts/msdf/fontmsdf.png
  tests/visual/scenes/text/msdf-text.scene.ts
  tests/visual/snapshots/msdf-text-scene-ts-webgl1.png
  tests/visual/snapshots/msdf-text-scene-ts-webgl2.png
  tests/visual/snapshots/msdf-text-scene-ts-webgpu.png
Labels: ✅ Ready To Merge, v8

#10714 chore: remove instructionSet parameter from updateRenderable
  src/rendering/renderers/shared/instructions/RenderPipe.ts
Labels: ✅ Ready To Merge, v8

#10715 chore: make validateRenderable nonoptional
  src/rendering/renderers/shared/instructions/RenderPipe.ts
Labels: ✅ Ready To Merge, v8

#10718 fix: Batch Pooling follow-up
  src/rendering/batcher/shared/Batcher.ts
Labels: ✅ Ready To Merge, v8

#10720 fix: culling issues
  src/culling/Culler.ts
  src/scene/container/Container.ts
  tests/scene/culler.test.ts
  tests/scene/transform-visibility.tests.ts
Labels: ✅ Ready To Merge, v8

#10733 fix: batcher passing null textures
  src/rendering/batcher/gl/GlBatchAdaptor.ts
  src/scene/graphics/gl/GlGraphicsAdaptor.ts
Labels: ✅ Ready To Merge, v8

#10726 chore: make uid members public
  src/rendering/batcher/shared/Batcher.ts
  src/rendering/renderers/shared/buffer/Buffer.ts
  src/rendering/renderers/shared/buffer/BufferResource.ts
  src/rendering/renderers/shared/instructions/InstructionSet.ts
  src/rendering/renderers/shared/renderTarget/RenderTarget.ts
  src/rendering/renderers/shared/shader/UniformGroup.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/rendering/renderers/shared/view/View.ts
  src/scene/container/Container.ts
  src/scene/graphics/shared/GraphicsContext.ts
  src/scene/graphics/shared/fill/FillGradient.ts
  src/scene/graphics/shared/fill/FillPattern.ts
  src/scene/graphics/shared/path/GraphicsPath.ts
Labels: ✅ Ready To Merge

#10683 fix: restore automatic filter resolution and mask resolution/antialias
  src/filters/Filter.ts
  src/filters/FilterSystem.ts
  src/filters/defaults/blur/BlurFilter.ts
  src/rendering/mask/alpha/AlphaMaskPipe.ts
Labels: ✅ Ready To Merge

#10730 chore: make Mesh#shader nullable
  src/scene/mesh/shared/Mesh.ts
Labels: ✅ Ready To Merge

#10740 fix: update check for visible / blend / alpha updates
  src/scene/container/utils/updateRenderGroupTransforms.ts
Labels: ✅ Ready To Merge

#10745 fix: clean our render lists after use!
  src/scene/container/RenderGroupSystem.ts
  src/scene/container/utils/clearList.ts
  src/scene/container/utils/updateRenderGroupTransforms.ts
  src/scene/container/utils/validateRenderables.ts
  src/utils/pool/Pool.ts
  tests/scene/RenderGroup.tests.ts
Labels: ✅ Ready To Merge, v8

#10748 fix: validateRenderable documentation
  src/rendering/renderers/shared/instructions/RenderPipe.ts
Labels: ✅ Ready To Merge

#10721 chore: add bunnymark to sandbox
  .codesandbox/sandbox/Bunny.js
  .codesandbox/sandbox/index.js
  .codesandbox/sandbox/package.json
  .codesandbox/sandbox/sandbox.config.json
Labels: ✅ Ready To Merge

#10739 fix: inconsistencies in docs (10663)
  src/app/Application.ts
  src/app/TickerPlugin.ts
  src/prepare/PrepareBase.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/types.ts
Labels: ✅ Ready To Merge

#10681 feat: add a renderable GC
  src/rendering/mask/alpha/AlphaMaskPipe.ts
  src/rendering/mask/stencil/StencilMaskPipe.ts
  src/rendering/renderers/shared/SchedulerSystem.ts
  src/rendering/renderers/shared/instructions/InstructionSet.ts
  src/rendering/renderers/shared/system/SharedSystems.ts
  src/rendering/renderers/shared/texture/RenderableGCSystem.ts
  src/rendering/renderers/shared/texture/TextureGCSystem.ts
  src/rendering/renderers/shared/view/View.ts
  src/scene/container/Container.ts
  src/scene/container/RenderContainer.ts
  src/scene/container/RenderGroupSystem.ts
  src/scene/container/utils/buildInstructions.ts
  src/scene/graphics/shared/Graphics.ts
  src/scene/graphics/shared/GraphicsPipe.ts
  src/scene/mesh/shared/BatchableMesh.ts
  src/scene/mesh/shared/Mesh.ts
  src/scene/mesh/shared/MeshPipe.ts
  src/scene/sprite-nine-slice/NineSliceSprite.ts
  src/scene/sprite-nine-slice/NineSliceSpritePipe.ts
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/sprite-tiling/TilingSpritePipe.ts
  src/scene/sprite/Sprite.ts
  src/scene/sprite/SpritePipe.ts
  src/scene/text-bitmap/BitmapTextPipe.ts
  src/scene/text-html/HTMLTextPipe.ts
  src/scene/text/AbstractText.ts
  src/scene/text/canvas/CanvasTextPipe.ts
  tests/renderering/RenderablesGC.test.ts
  tests/scene/DummyView.ts
Labels: ✅ Ready To Merge

#10684 feat: add 'min' and 'max' blend modes
  src/rendering/renderers/gl/state/mapWebGLBlendModesToPixi.ts
  src/rendering/renderers/gpu/state/GpuBlendModesToPixi.ts
  src/rendering/renderers/shared/state/State.ts
  src/rendering/renderers/shared/state/const.ts
  tests/visual/scenes/blend-modes/blend-mode-max.scene.ts
  tests/visual/scenes/blend-modes/blend-mode-min.scene.ts
  tests/visual/snapshots/blend-mode-max-scene-ts-webgl1.png
  tests/visual/snapshots/blend-mode-max-scene-ts-webgl2.png
  tests/visual/snapshots/blend-mode-max-scene-ts-webgpu.png
  tests/visual/snapshots/blend-mode-min-scene-ts-webgl1.png
  tests/visual/snapshots/blend-mode-min-scene-ts-webgl2.png
  tests/visual/snapshots/blend-mode-min-scene-ts-webgpu.png
Labels: ✅ Ready To Merge

#10703 feat: reserve texture units for batching
  src/rendering/batcher/shared/Batcher.ts
Labels: ✅ Ready To Merge

#10713 feat: add ShaderSystem#maxTextures
  src/rendering/batcher/gl/utils/checkMaxIfStatementsInShader.ts
  src/rendering/batcher/gl/utils/maxRecommendedTextures.ts
  src/rendering/renderers/gl/shader/GlShaderSystem.ts
  src/rendering/renderers/gpu/shader/GpuShaderSystem.ts
  src/rendering/renderers/shared/shader/ShaderSystem.ts
Labels: ✅ Ready To Merge

#10771 fix: split out update id and view update id
  src/scene/container/Container.ts
  src/scene/container/container-mixins/childrenHelperMixin.ts
  src/scene/container/container-mixins/measureMixin.ts
  src/scene/container/utils/checkChildrenDidChange.ts
  src/scene/graphics/shared/Graphics.ts
  src/scene/mesh/shared/Mesh.ts
  src/scene/sprite-nine-slice/NineSliceSprite.ts
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/sprite/Sprite.ts
  src/scene/text/AbstractText.ts
  tests/scene/checkChildrenDidChange.tests.ts
Labels: ✅ Ready To Merge

#10774 fix: attributes locations
  src/filters/FilterSystem.ts
  src/rendering/batcher/gpu/GpuBatchAdaptor.ts
  src/rendering/batcher/shared/BatchGeometry.ts
  src/rendering/renderers/gl/geometry/GlGeometrySystem.ts
  src/rendering/renderers/gl/shader/program/ensureAttributes.ts
  src/rendering/renderers/gl/shader/program/extractAttributesFromGlProgram.ts
  src/rendering/renderers/gpu/GpuEncoderSystem.ts
  src/rendering/renderers/gpu/pipeline/PipelineSystem.ts
  src/rendering/renderers/gpu/shader/GpuProgram.ts
  src/rendering/renderers/shared/geometry/Geometry.ts
  src/scene/graphics/gpu/GpuGraphicsAdaptor.ts
  tests/renderering/Geometry.test.ts
  tests/renderering/glEnsureAttributes.test.ts
  tests/utils/getGeometry.ts
Labels: ✅ Ready To Merge
