Repository pixijs/pixijs, pull requests merged in 2024-05, with the labels that each got.

#10531 fix: simplify masking
  src/events/EventBoundary.ts
  src/rendering/mask/MaskEffectManager.ts
  src/scene/container/Container.ts
  src/scene/container/container-mixins/effectsMixin.ts
Labels: ✅ Ready To Merge, v8, korbit-code-analysis

#10514 fix: unicode support for BitmapFontManager
  src/scene/text-bitmap/BitmapFontManager.ts
  tests/renderering/text/BitmapFontManager.test.ts
Labels: ✅ Ready To Merge, v8

#10509 Fix missing commas in the documentation of Spritesheet.ts
  src/spritesheet/Spritesheet.ts
Labels: ✅ Ready To Merge, v8

#10503 Fix: Text bounds calculation with padding
  src/scene/text/Text.ts
  tests/renderering/text/Text.tests.ts
Labels: ✅ Ready To Merge, v8

#10507 Fix: handling of getRenderTarget when passing in a canvas
  src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts
  tests/renderering/RenderTargetSystem.test.ts
Labels: ✅ Ready To Merge, v8

#10530 Fix: Filter hitArea not updating
  src/events/EventBoundary.ts
  src/filters/FilterEffect.ts
  src/rendering/mask/MaskEffectManager.ts
  src/rendering/mask/alpha/AlphaMaskPipe.ts
  src/rendering/renderers/shared/blendModes/BlendModePipe.ts
  src/scene/container/Container.ts
  src/scene/container/container-mixins/effectsMixin.ts
Labels: ✅ Ready To Merge, v8, korbit-code-analysis

#10505 Fix: destroy and removeChild performance
  src/scene/container/Container.ts
  src/scene/container/RenderGroup.ts
  src/scene/container/bounds/getFastGlobalBounds.ts
  src/scene/container/container-mixins/childrenHelperMixin.ts
  src/scene/container/container-mixins/effectsMixin.ts
  src/scene/container/container-mixins/onRenderMixin.ts
  src/scene/container/container-mixins/sortMixin.ts
  src/scene/container/utils/buildInstructions.ts
  src/scene/container/utils/updateRenderGroupTransforms.ts
  src/scene/graphics/shared/Graphics.ts
  src/scene/mesh/shared/Mesh.ts
  src/scene/sprite-nine-slice/NineSliceSprite.ts
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/sprite/Sprite.ts
  src/scene/text/AbstractText.ts
  src/utils/logging/logScene.ts
  tests/scene/Container.tests.ts
  tests/scene/DummyView.ts
  tests/scene/getGlobalFastBounds.tests.ts
  tests/scene/scene.tests.ts
  tests/visual/scenes/scene/layer-tint.scene.ts
Labels: ✅ Ready To Merge, v8, korbit-code-analysis

#10513 Fix: changing tiling sprite anchor not updating view
  src/scene/container/container-mixins/effectsMixin.ts
  src/scene/sprite-tiling/TilingSprite.ts
  tests/renderering/sprite/TilingSprite.test.ts
  tests/scene/scene.tests.ts
Labels: ✅ Ready To Merge, v8

#10536 fix mask issue when setting to null and back
  src/scene/container/container-mixins/effectsMixin.ts
  tests/scene/mask.test.ts
Labels: ✅ Ready To Merge, v8

#10537 fix: buffer upload for texture
  src/rendering/init.ts
  src/rendering/renderers/gl/texture/uploaders/glUploadBufferImageResource.ts
  src/rendering/renderers/gl/texture/uploaders/glUploadImageResource.ts
  src/rendering/renderers/gpu/texture/uploaders/gpuUploadBufferImageResource.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/sources/BufferImageSource.ts
  src/rendering/renderers/shared/texture/utils/textureFrom.ts
Labels: ✅ Ready To Merge, v8

#10543 fix: event mixin types
  src/events/EventBoundary.ts
  src/events/EventBoundaryTypes.ts
  src/events/EventsMixins.d.ts
  src/events/FederatedEvent.ts
  src/events/FederatedEventTarget.ts
  src/events/deprecatedTypes.ts
  src/scene/container/Container.ts
Labels: ✅ Ready To Merge, v8, korbit-code-analysis

#10561 fix: graphics clear not clearing mid path.
  src/scene/graphics/shared/GraphicsContext.ts
  tests/renderering/graphics/Graphics.test.ts
Labels: ✅ Ready To Merge, v8

#10557 fix: masks interfering with interaction
  src/events/EventBoundary.ts
Labels: ✅ Ready To Merge, v8

#10562 chore: add better error checking for unsupported shader uniform types
  src/rendering/renderers/shared/shader/UniformGroup.ts
  src/rendering/renderers/shared/shader/types.ts
Labels: ✅ Ready To Merge, v8

#10558 fix: max textures to run when needed, not at startup
  src/rendering/batcher/gl/GlBatchAdaptor.ts
  src/rendering/batcher/gpu/GpuBatchAdaptor.ts
  src/rendering/batcher/gpu/getTextureBatchBindGroup.ts
  src/rendering/batcher/shared/Batcher.ts
  src/rendering/batcher/shared/const.ts
  src/rendering/high-shader/shader-bits/generateTextureBatchBit.ts
  src/rendering/renderers/gl/shader/batchSamplersUniformGroup.ts
  src/rendering/renderers/gl/shader/getBatchSamplersUniformGroup.ts
  src/rendering/renderers/shared/texture/utils/maxRecommendedTextures.ts
  src/scene/graphics/gl/GlGraphicsAdaptor.ts
  src/scene/graphics/gpu/GpuGraphicsAdaptor.ts
  src/scene/text/sdfShader/SdfShader.ts
Labels: ✅ Ready To Merge, v8

#10560 fix: event leak in graphics pipe
  src/rendering/renderers/gl/texture/uploaders/glUploadImageResource.ts
  src/scene/graphics/shared/GraphicsContext.ts
  src/scene/graphics/shared/GraphicsContextSystem.ts
  src/scene/graphics/shared/GraphicsPipe.ts
  tests/renderering/graphics/Graphics.test.ts
Labels: ✅ Ready To Merge, v8

#10520 feat: add automated published branch releases for dev & main
  .github/workflows/publish-branch.yaml
  package.json
Labels: v8

#10566 fix: destroy renderGroups
  src/scene/container/Container.ts
  src/scene/container/RenderGroup.ts
  tests/renderering/scene/Container.test.ts
Labels: ✅ Ready To Merge, v8

#10567 fix: allow renderers to be created without autoDetectRenderer
  src/rendering/renderers/autoDetectRenderer.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/system/SharedSystems.ts
Labels: ✅ Ready To Merge, v8

#10568 fix: spritesheet resolver not working
  src/assets/resolver/parsers/resolveJsonUrl.ts
  tests/assets/Resolver.tests.ts
Labels: ✅ Ready To Merge, v8

#10573 fix: allow bitmap fonts to be loaded before renderer init
  src/assets/Assets.ts
  src/scene/text-bitmap/init.ts
Labels: ✅ Ready To Merge, v8

#10575 fix: containsPoint for TilingSprite and Text when anchor is set
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/text/AbstractText.ts
  tests/renderering/sprite/TilingSprite.test.ts
  tests/renderering/text/Text.tests.ts
Labels: ✅ Ready To Merge, v8

#10576 fix: uninstalling bitmap font containing space characters
  src/scene/text-bitmap/AbstractBitmapFont.ts
  tests/renderering/text/BitmapFontManager.test.ts
Labels: ✅ Ready To Merge, v8

#10569 chore: deprecate autoDetectEnvironment and manageImports
  src/environment/autoDetectEnvironment.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/system/SharedSystems.ts
Labels: ✅ Ready To Merge, v8

#10570 fix: sprite size changing when texture changes
  src/scene/sprite/Sprite.ts
  tests/visual/scenes/sprite/sprite-sizing.scene.ts
  tests/visual/snapshots/sprite-sizing-scene-ts-webgl1.png
  tests/visual/snapshots/sprite-sizing-scene-ts-webgl2.png
  tests/visual/snapshots/sprite-sizing-scene-ts-webgpu.png
Labels: ✅ Ready To Merge, v8

#10565 fix: msdf-text-tweaks
  src/scene/text-bitmap/BitmapTextPipe.ts
  src/scene/text-bitmap/asset/loadBitmapFont.ts
  src/scene/text/sdfShader/SdfShader.ts
  src/scene/text/sdfShader/shader-bits/localUniformMSDFBit.ts
  src/scene/text/sdfShader/shader-bits/mSDFBit.ts
Labels: ✅ Ready To Merge, v8

#10577 fix: text not updating when resolution or dropShadow changes
  src/scene/text-html/HtmlTextStyle.ts
  src/scene/text/AbstractText.ts
  src/scene/text/TextStyle.ts
  src/scene/text/utils/generateTextStyleKey.ts
  tests/visual/scenes/text/text-drop-shadow.scene.ts
  tests/visual/scenes/text/text-dynamic.scene.ts
  tests/visual/snapshots/text-drop-shadow-scene-ts-webgl1.png
  tests/visual/snapshots/text-drop-shadow-scene-ts-webgl2.png
  tests/visual/snapshots/text-drop-shadow-scene-ts-webgpu.png
  tests/visual/snapshots/text-dynamic-scene-ts-webgl1.png
  tests/visual/snapshots/text-dynamic-scene-ts-webgl2.png
  tests/visual/snapshots/text-dynamic-scene-ts-webgpu.png
Labels: ✅ Ready To Merge, v8

#10579 fix: Text deprecation not converting correctly
  src/scene/text/TextStyle.ts
  tests/renderering/text/TextStyle.tests.ts
Labels: ✅ Ready To Merge, v8

#10584 chore: update ci actions to latest
  .github/actions/setup/action.yml
  .github/actions/unit/action.yml
  .github/workflows/pull-name.yml
  .github/workflows/pull-unit.yml
  .github/workflows/pull-visuals.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .nvmrc
Labels: ✅ Ready To Merge, v8

#10587 fix: export type dependencies
  src/compressed-textures/dds/const.ts
  src/filters/defaults/blur/const.ts
  src/rendering/renderers/shared/renderTarget/GlobalUniformSystem.ts
  src/rendering/renderers/shared/shader/utils/uniformParsers.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
Labels: ✅ Ready To Merge, v8
