Repository pixijs/pixijs, pull requests merged in 2024-02, with the labels that each got.

#10171 Fix: filters not working for WebGPU
  src/filters/FilterSystem.ts
  src/rendering/renderers/gpu/shader/utils/generateArraySyncWGSL.ts
  src/rendering/renderers/shared/buffer/Buffer.ts
  src/rendering/renderers/shared/buffer/BufferResource.ts
  src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts
  src/rendering/renderers/shared/shader/UniformGroup.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/TextureStyle.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/scene/container/RenderGroupSystem.ts
  src/utils/data/uid.ts
  tests/renderering/BindGroup.test.ts
  tests/visual/scenes/filters/nested-filters.scene.ts
  tests/visual/snapshots/nested-filters-scene-ts-webgl1.png
  tests/visual/snapshots/nested-filters-scene-ts-webgl2.png
  tests/visual/snapshots/nested-filters-scene-ts-webgpu.png
Labels: v8

#10166 Fix: performance regression when overriding size methods
  src/scene/container/Container.ts
  src/scene/container/container-mixins/measureMixin.ts
  src/scene/sprite/Sprite.ts
  src/scene/text/Text.ts
Labels: v8

#10165 Fix: types not building correctly
  scripts/types/fixTypes.ts
Labels: v8

#10172 Fix: strokes on BitmapText not being applied
  src/scene/text-bitmap/BitmapFontManager.ts
  src/scene/text-bitmap/DynamicBitmapFont.ts
  tests/renderering/text/BitmapFont.tests.ts
  tests/visual/scenes/text/bitmap-install-text.scene.ts
  tests/visual/scenes/text/bitmap-text-stroke.scene.ts
  tests/visual/snapshots/bitmap-install-text-scene-ts-webgl1.png
  tests/visual/snapshots/bitmap-install-text-scene-ts-webgl2.png
  tests/visual/snapshots/bitmap-install-text-scene-ts-webgpu.png
  tests/visual/snapshots/bitmap-text-stroke-scene-ts-webgl1.png
  tests/visual/snapshots/bitmap-text-stroke-scene-ts-webgl2.png
  tests/visual/snapshots/bitmap-text-stroke-scene-ts-webgpu.png
Labels: v8

#10174 Fix: destroying renderer when using graphics
  src/scene/graphics/shared/GraphicsContextSystem.ts
  tests/renderering/graphics/Graphics.test.ts
Labels: v8

#10173 Feat: add ability to set custom render logic
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/system/SharedSystems.ts
  src/scene/container/CustomRenderPipe.ts
  src/scene/container/RenderContainer.ts
  tests/visual/scenes/container/custom-render.scene.ts
  tests/visual/snapshots/custom-render-scene-ts-webgl1.png
  tests/visual/snapshots/custom-render-scene-ts-webgl2.png
  tests/visual/snapshots/custom-render-scene-ts-webgpu.png
Labels: v8

#10184 Feat: support depth testing
  src/rendering/mask/stencil/StencilMaskPipe.ts
  src/rendering/renderers/gpu/pipeline/PipelineSystem.ts
  src/rendering/renderers/gpu/renderTarget/GlRenderTargetAdaptor.ts
  src/rendering/renderers/gpu/renderTarget/GpuRenderTargetAdaptor.ts
  src/rendering/renderers/gpu/state/GpuStencilModesToPixi.ts
  src/rendering/renderers/shared/renderTarget/RenderTarget.ts
  src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/rendering/renderers/shared/view/ViewSystem.ts
Labels: v8

#10187 Fix: rendering issues with uint16
  src/rendering/renderers/gl/buffer/GlBufferSystem.ts
  src/rendering/renderers/gpu/buffer/GpuBufferSystem.ts
  tests/visual/scenes/graphics/oddsize-polygon.scene.ts
  tests/visual/snapshots/oddsize-polygon-scene-ts-webgl1.png
  tests/visual/snapshots/oddsize-polygon-scene-ts-webgl2.png
  tests/visual/snapshots/oddsize-polygon-scene-ts-webgpu.png
Labels: v8

#10189 Fix: texture.update() now only updates uvs and dispatches an event
  src/rendering/renderers/shared/texture/Texture.ts
  tests/renderering/textures/Textures.test.ts
Labels: v8

#10188 Fix: allow setting bitmap text fill as 0x0
  src/scene/graphics/shared/utils/convertFillInputToFillStyle.ts
  src/scene/text/Text.ts
  src/scene/text/TextStyle.ts
  tests/visual/scenes/text/bitmap-text-fill.scene.ts
  tests/visual/snapshots/bitmap-text-fill-scene-ts-webgl1.png
  tests/visual/snapshots/bitmap-text-fill-scene-ts-webgl2.png
  tests/visual/snapshots/bitmap-text-fill-scene-ts-webgpu.png
Labels: v8

#10196 Fix: allow render function in RenderContainer to be overridable
  src/scene/container/RenderContainer.ts
Labels: v8

#10225 Updated example for PIXI.Geometry to draw a square instead of dovetail
  packages/core/src/geometry/Geometry.ts
Labels: ✅ Ready To Merge

#10227 Bump @pixi/webworker-plugins to 0.3.0
  global.d.ts
  package-lock.json
  package.json
  packages/assets/src/loader/parsers/WorkerManager.ts
Labels: ✅ Ready To Merge

#10211 Fix: graphics tint and mesh texture swap issues
  src/scene/container/RenderGroup.ts
  src/scene/graphics/shared/GraphicsContext.ts
  src/scene/graphics/shared/utils/buildGeometryFromPath.ts
  src/scene/mesh-plane/MeshPlane.ts
  tests/display/Container.Visual.tests.ts
  tests/visual/scenes/graphics/graphics-texture.scene.ts
  tests/visual/snapshots/graphics-texture-scene-ts-webgl1.png
  tests/visual/snapshots/graphics-texture-scene-ts-webgl2.png
  tests/visual/snapshots/graphics-texture-scene-ts-webgpu.png
Labels: ✅ Ready To Merge, v8

#10214 Feat: add number setters for transform points
  .eslintrc.json
  src/assets/resolver/Resolver.ts
  src/events/EventBoundary.ts
  src/scene/container/Container.ts
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/sprite/Sprite.ts
  src/scene/text/AbstractText.ts
Labels: ✅ Ready To Merge, v8

#10219 Fix: compressed textures priorities
  src/compressed-textures/basis/worker/basis.worker.ts
  src/compressed-textures/shared/resolveCompressedTextureUrl.ts
  src/rendering/renderers/gl/texture/utils/getSupportedGlCompressedTextureFormats.ts
Labels: ✅ Ready To Merge, v8

#10221 Fix: Deprecate constructor options on Application
  src/app/Application.ts
Labels: ✅ Ready To Merge, v8

#10223 Chore: Cleanup deprecations from release build
  src/filters/defaults/blur/BlurFilter.ts
  src/filters/defaults/displacement/DisplacementFilter.ts
  src/rendering/renderers/shared/geometry/const.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/TextureStyle.ts
  src/rendering/renderers/shared/texture/const.ts
  src/rendering/renderers/shared/view/ViewSystem.ts
  src/scene/container/Container.ts
  src/scene/container/container-mixins/childrenHelperMixin.ts
  src/scene/container/container-mixins/findMixin.ts
  src/scene/graphics/shared/Graphics.ts
  src/scene/graphics/shared/GraphicsContext.ts
  src/scene/mesh-plane/PlaneGeometry.ts
  src/scene/mesh/shared/Mesh.ts
  src/scene/mesh/shared/MeshGeometry.ts
  src/scene/sprite-nine-slice/NineSliceSprite.ts
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/text-bitmap/AbstractBitmapFont.ts
  src/scene/text-bitmap/BitmapFontManager.ts
  src/scene/text-bitmap/DynamicBitmapFont.ts
  src/scene/text/AbstractText.ts
  src/scene/text/TextStyle.ts
Labels: ✅ Ready To Merge, v8

#10224 Chore: Add caching to all lint
  package.json
Labels: ✅ Ready To Merge, v8

#10232 Fix: Spritesheet asset formats list
  src/spritesheet/spritesheetAsset.ts
  tests/compressed/CompressedTextures.test.ts
Labels: ✅ Ready To Merge, v8

#10236 Fix: canvas texture not updating
  src/rendering/renderers/shared/texture/sources/CanvasSource.ts
  tests/visual/scenes/textures/canvas-texture.scene.ts
  tests/visual/snapshots/canvas-texture-scene-ts-webgl1.png
  tests/visual/snapshots/canvas-texture-scene-ts-webgl2.png
  tests/visual/snapshots/canvas-texture-scene-ts-webgpu.png
Labels: ✅ Ready To Merge, v8

#10238 Fix: Make filters setting immutable
  src/scene/container/container-mixins/effectsMixin.ts
  tests/scene/filter-effect.tests.ts
Labels: ✅ Ready To Merge, v8

#10242 Fix: gl depth on creation
  src/rendering/renderers/gpu/renderTarget/GlRenderTargetAdaptor.ts
Labels: v8

#10235 Feat: allow simple object manifest
  src/assets/Assets.ts
  src/assets/resolver/Resolver.ts
  src/assets/types.ts
  tests/assets/assets/json/asset-manifest-object.json
  tests/assets/bundle.tests.ts
Labels: ✅ Ready To Merge, v8

#10257 Fix: bump webworker plugin
  jest.config.js
  package-lock.json
  package.json
  src/assets/loader/workers/WorkerManager.ts
  src/assets/loader/workers/checkImageBitmap.worker.ts
  src/assets/loader/workers/loadImageBitmap.worker.ts
  src/compressed-textures/basis/worker/loadBasisOnWorker.ts
  src/compressed-textures/ktx/worker/loadKTXonWorker.ts
  types/Temp.d.ts
  types/Worker.d.ts
Labels: v8
