Repository pixijs/pixijs, pull requests merged in 2024-03, with the labels that each got.

#10261 Chore: update class docs 1
  package-lock.json
  package.json
  src/app/Application.ts
  src/app/TickerPlugin.ts
  src/assets/Assets.ts
  src/assets/types.ts
  src/filters/defaults/alpha/AlphaFilter.ts
  src/maths/point/ObservablePoint.ts
  src/rendering/renderers/gl/WebGLRenderer.ts
  src/rendering/renderers/gl/const.ts
  src/rendering/renderers/gpu/shader/GpuProgram.ts
  src/rendering/renderers/shared/blendModes/BlendModePipe.ts
  src/rendering/renderers/shared/extract/GenerateTextureSystem.ts
  src/rendering/renderers/shared/renderTarget/GlobalUniformSystem.ts
  src/rendering/renderers/shared/renderTarget/RenderTarget.ts
  src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts
  src/rendering/renderers/shared/state/State.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/TextureStyle.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/rendering/renderers/shared/view/View.ts
  src/scene/container/Container.ts
  src/scene/graphics/shared/Graphics.ts
  src/scene/sprite-animated/AnimatedSprite.ts
  src/scene/sprite-nine-slice/NineSliceGeometry.ts
  src/scene/sprite-nine-slice/NineSliceSprite.ts
  src/scene/sprite-tiling/TilingSprite.ts
  src/scene/sprite/Sprite.ts
  src/scene/text-bitmap/AbstractBitmapFont.ts
  src/scene/text-html/HtmlTextStyle.ts
  src/scene/text/AbstractText.ts
  src/scene/text/TextStyle.ts
  src/scene/text/canvas/CanvasTextMetrics.ts
Labels: v8

#10262 Chore: update class docs 2
  src/filters/defaults/blur/BlurFilter.ts
  src/filters/defaults/blur/BlurFilterPass.ts
  src/rendering/batcher/shared/BatchTextureArray.ts
  src/rendering/batcher/shared/Batcher.ts
  src/rendering/renderers/shared/buffer/Buffer.ts
  src/scene/container/bounds/Bounds.ts
  src/scene/graphics/shared/BatchableGraphics.ts
  src/scene/mesh/shared/BatchableMesh.ts
  src/scene/sprite/BatchableSprite.ts
  src/scene/text-bitmap/BitmapFont.ts
  src/scene/text-bitmap/BitmapFontManager.ts
  src/scene/text-bitmap/BitmapText.ts
  src/scene/text/AbstractText.ts
Labels: v8

#10266 Chore: update class docs 3
  src/accessibility/accessibilityTarget.ts
  src/advanced-blend-modes/ColorBlend.ts
  src/advanced-blend-modes/ColorBurnBlend.ts
  src/advanced-blend-modes/ColorDodgeBlend.ts
  src/advanced-blend-modes/DarkenBlend.ts
  src/advanced-blend-modes/DifferenceBlend.ts
  src/advanced-blend-modes/DivideBlend.ts
  src/advanced-blend-modes/ExclusionBlend.ts
  src/advanced-blend-modes/HardLightBlend.ts
  src/advanced-blend-modes/HardMixBlend.ts
  src/advanced-blend-modes/LightenBlend.ts
  src/advanced-blend-modes/LinearBurnBlend.ts
  src/advanced-blend-modes/LinearDodgeBlend.ts
  src/advanced-blend-modes/LinearLightBlend.ts
  src/advanced-blend-modes/LuminosityBlend.ts
  src/advanced-blend-modes/NegationBlend.ts
  src/advanced-blend-modes/OverlayBlend.ts
  src/advanced-blend-modes/PinLightBlend.ts
  src/advanced-blend-modes/SaturationBlend.ts
  src/advanced-blend-modes/SoftLightBlend.ts
  src/advanced-blend-modes/SubtractBlend.ts
  src/advanced-blend-modes/VividLightBlend.ts
  src/color/Color.ts
  src/culling/Culler.ts
  src/events/FederatedEventTarget.ts
  src/maths/shapes/Circle.ts
  src/rendering/renderers/shared/state/const.ts
  src/scene/container/Container.ts
  src/scene/container/Effect.ts
  src/scene/container/destroyTypes.ts
  src/scene/text/canvas/CanvasTextSystem.ts
Labels: v8

#10241 Feat: add DDS DX10 support
  src/compressed-textures/dds/const.ts
  src/compressed-textures/dds/parseDDS.ts
  src/rendering/renderers/gl/context/GlContextSystem.ts
  src/rendering/renderers/gl/context/WebGLExtensions.ts
  src/rendering/renderers/gl/texture/uploaders/glUploadCompressedTextureResource.ts
  src/rendering/renderers/gl/texture/utils/getSupportedGlCompressedTextureFormats.ts
  src/rendering/renderers/gl/texture/utils/mapFormatToGlInternalFormat.ts
  tests/compressed/ParseDDS.test.ts
  tests/compressed/textures/test.bc4.dds
  tests/compressed/textures/test.bc4.mipmap.dds
  tests/compressed/textures/test.bc5.dds
  tests/compressed/textures/test.bc5.mipmap.dds
  tests/compressed/textures/test.bc7.dds
  tests/compressed/textures/test.dxt1.dds
  tests/compressed/textures/test.dxt1.mipmap.dds
  tests/compressed/textures/test.dxt3.dds
  tests/compressed/textures/test.dxt3.mipmap.dds
  tests/compressed/textures/test.dxt5.dds
  tests/compressed/textures/test.dxt5.mipmap.dds
  tests/compressed/textures/test.rgba8.dds
  tests/compressed/textures/test.rgba8.mipmap.dds
Labels: v8

#10263 Expose `FilterSystem`'s back texture as public property
  src/filters/FilterSystem.ts
Labels: v8

#10246 Feat: add KTX parser
  src/compressed-textures/ktx/const.ts
  src/compressed-textures/ktx/loadKTX.ts
  src/compressed-textures/ktx/parseKTX.ts
  src/compressed-textures/ktx/worker/ktx.worker.ts
  src/rendering/renderers/gl/texture/utils/mapFormatToGlInternalFormat.ts
  tests/compressed/ParseKTX.test.ts
  tests/compressed/textures/test.RGBA8.ktx
  tests/compressed/textures/test.astc.12x12.ktx
  tests/compressed/textures/test.astc.4x4.ktx
  tests/compressed/textures/test.astc.5x5.ktx
  tests/compressed/textures/test.astc.ktx
  tests/compressed/textures/test.bc1.ktx
  tests/compressed/textures/test.bc3.ktx
  tests/compressed/textures/test.bc3.mipmap.ktx
  tests/compressed/textures/test.etc2.ktx
  tests/visual/assets/test.bc3.mipmap.ktx
  tests/visual/scenes/compressed-textures/ktx.scene.ts
  tests/visual/snapshots/ktx-scene-ts-webgl1.png
  tests/visual/snapshots/ktx-scene-ts-webgl2.png
  tests/visual/snapshots/ktx-scene-ts-webgpu.png
Labels: v8

#10245 Chore: Update readme links
  README.md
Labels: ✅ Ready To Merge

#10298 Fix: tests failing locally
  package.json
  tests/unsafe-eval/WithUnsafeEval.tests.ts
  tests/unsafe-eval/WithoutUnsafeEval.tests.ts
  tests/utils/disableUnsafeEval.ts
Labels: v8

#10277 Fix: setting fill 0x0 on BitmapText
  src/scene/text-bitmap/BitmapTextPipe.ts
  tests/visual/scenes/text/bitmap-text-fill.scene.ts
  tests/visual/snapshots/bitmap-text-fill-scene-ts-webgl1.png
  tests/visual/snapshots/bitmap-text-fill-scene-ts-webgl2.png
  tests/visual/snapshots/bitmap-text-fill-scene-ts-webgpu.png
Labels: ✅ Ready To Merge, v8

#10280 Fix: circular deps
  package.json
  scripts/utils/exports.ts
  src/rendering/init.ts
  src/rendering/renderers/shared/texture/Texture.ts
  src/rendering/renderers/shared/texture/utils/textureFrom.ts
  src/scene/text-html/HTMLTextRenderData.ts
  src/scene/text-html/HTMLTextSystem.ts
  src/scene/text-html/utils/getFontCss.ts
  src/scene/text-html/utils/getSVGUrl.ts
  src/scene/text-html/utils/measureHtmlText.ts
  tests/renderering/text/getFontCss.tests.ts
Labels: ✅ Ready To Merge, v8

#10281 Fix: type errors
  src/accessibility/AccessibilitySystem.ts
  src/accessibility/accessibilityTarget.ts
  src/rendering/renderers/gl/GlBackBufferSystem.ts
  src/rendering/renderers/shared/background/BackgroundSystem.ts
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  src/rendering/renderers/shared/system/System.ts
  src/rendering/renderers/shared/texture/TextureGCSystem.ts
  src/rendering/renderers/shared/view/ViewSystem.ts
  src/scene/text-bitmap/AbstractBitmapFont.ts
  src/utils/pool/Pool.ts
  src/utils/pool/PoolGroup.ts
Labels: ✅ Ready To Merge, v8

#10282 Fix: removeChild bug
  src/scene/container/Container.ts
  tests/scene/scene.tests.ts
Labels: ✅ Ready To Merge

#10283 Fix: Respect the user-input for filters and don't freeze
  src/scene/container/container-mixins/effectsMixin.ts
  tests/scene/filter-effect.tests.ts
Labels: ✅ Ready To Merge, v8

#10279 Fix: allowing PointData for graphics.poly
  src/scene/graphics/shared/Graphics.ts
  src/scene/graphics/shared/GraphicsContext.ts
  src/scene/graphics/shared/path/GraphicsPath.ts
  src/scene/graphics/shared/path/ShapePath.ts
  tests/renderering/graphics/Graphics.Drawing.test.ts
  tests/visual/scenes/graphics/poly.scene.ts
  tests/visual/snapshots/poly-scene-ts-webgl1.png
  tests/visual/snapshots/poly-scene-ts-webgl2.png
  tests/visual/snapshots/poly-scene-ts-webgpu.png
Labels: ✅ Ready To Merge, v8

#10291 Fix: text measurement issue
  src/scene/text/AbstractText.ts
  src/scene/text/Text.ts
  tests/renderering/text/Text.tests.ts
Labels: ✅ Ready To Merge, v8

#10292 Fix: applying alpha on the stage
  src/scene/container/RenderGroupSystem.ts
Labels: ✅ Ready To Merge, v8

#10297 Fix: add missing resize event
  src/rendering/renderers/shared/system/AbstractRenderer.ts
  tests/renderering/Renderer.test.ts
Labels: ✅ Ready To Merge, v8

#10309 Fix: Assets not unloading all textures
  src/assets/loader/Loader.ts
  src/assets/loader/parsers/LoaderParser.ts
  src/assets/loader/parsers/textures/utils/createTexture.ts
  src/rendering/renderers/shared/texture/sources/TextureSource.ts
  src/scene/text-bitmap/AbstractBitmapFont.ts
  src/scene/text-bitmap/asset/loadBitmapFont.ts
  src/spritesheet/spritesheetAsset.ts
  tests/renderering/sprite/spritesheetAsset.tests.ts
Labels: ✅ Ready To Merge, v8

#10312 Chore: Fix docs for WebGLOptions and WebGPUOptions
  src/rendering/renderers/gl/GlBackBufferSystem.ts
  src/rendering/renderers/gl/WebGLRenderer.ts
  src/rendering/renderers/gl/context/GlContextSystem.ts
  src/rendering/renderers/gpu/GpuDeviceSystem.ts
  src/rendering/renderers/gpu/WebGPURenderer.ts
  src/rendering/renderers/shared/background/BackgroundSystem.ts
  src/rendering/renderers/shared/startup/HelloSystem.ts
  src/rendering/renderers/shared/system/SharedSystems.ts
  src/rendering/renderers/shared/texture/TextureGCSystem.ts
  src/rendering/renderers/shared/view/ViewSystem.ts
Labels: ✅ Ready To Merge, v8

#10313 Fix: allow meshes to have textures from sprite sheets
  src/maths/matrix/Matrix.ts
  src/rendering/high-shader/defaultProgramTemplate.ts
  src/rendering/high-shader/shader-bits/textureBit.ts
  src/scene/mesh-simple/MeshRope.ts
  src/scene/mesh-simple/RopeGeometry.ts
  src/scene/mesh/gl/GlMeshAdaptor.ts
  src/scene/mesh/gpu/GpuMeshAdapter.ts
  src/scene/mesh/shared/BatchableMesh.ts
  src/scene/mesh/shared/MeshPipe.ts
  src/scene/sprite-tiling/shader/tilingBit.ts
  tests/math/Matrix.tests.ts
  tests/visual/assets/building1.json
  tests/visual/assets/building1.png
  tests/visual/scenes/mesh/sprite-sheet-mesh.scene.ts
  tests/visual/snapshots/sprite-sheet-mesh-scene-ts-webgl1.png
  tests/visual/snapshots/sprite-sheet-mesh-scene-ts-webgl2.png
  tests/visual/snapshots/sprite-sheet-mesh-scene-ts-webgpu.png
Labels: ✅ Ready To Merge, v8

#10314 Fix: html text was not rendering all the time
  src/scene/text-html/HTMLTextPipe.ts
Labels: ✅ Ready To Merge, v8

#10320 Fix: shader preprocessor to support older chrome versions
  src/rendering/renderers/gl/shader/program/preprocessors/addProgramDefines.ts
Labels: ✅ Ready To Merge, v8

#10323 Fix: multilayered stencil mask issue
  src/rendering/mask/stencil/StencilMaskPipe.ts
  src/rendering/renderers/gpu/state/GpuStencilModesToPixi.ts
  tests/visual/scenes/mask/layer-mask.scene.ts
  tests/visual/snapshots/layer-mask-scene-ts-webgl1.png
  tests/visual/snapshots/layer-mask-scene-ts-webgl2.png
  tests/visual/snapshots/layer-mask-scene-ts-webgpu.png
Labels: ✅ Ready To Merge, v8

#10338 Fix: ICanvasRenderingContext2D extending letterSpacing (v7.x)
  packages/settings/src/ICanvasRenderingContext2D.ts
Labels: ✅ Ready To Merge

#10217 Assets resolver fix
  packages/assets/src/resolver/Resolver.ts
  packages/compressed-textures/src/loaders/resolveCompressedTextureUrl.ts
  packages/compressed-textures/src/resources/CompressedTextureResource.ts
  packages/compressed-textures/test/compressed-textures.tests.ts
  packages/spritesheet/src/spritesheetAsset.ts
Labels: ✅ Ready To Merge

#10218 Compressed textures priorities
  packages/basis/src/loader/BasisParser.ts
  packages/compressed-textures/src/loaders/detectCompressedTextures.ts
Labels: ✅ Ready To Merge

#10316 Fix: export jpg format error(v8)
  src/rendering/renderers/shared/extract/ExtractSystem.ts
Labels: ✅ Ready To Merge, v8

#10329 Fix: HTML Text font loading
  src/assets/loader/parsers/loadWebFont.ts
  src/scene/text-html/utils/getFontCss.ts
  tests/renderering/text/getFontCss.tests.ts
  tests/visual/assets/fonts/Crosterian.woff2
  tests/visual/scenes/text/html-text-loaded-font.scene.ts
  tests/visual/snapshots/html-text-loaded-font-scene-ts-webgl1.png
  tests/visual/snapshots/html-text-loaded-font-scene-ts-webgl2.png
  tests/visual/snapshots/html-text-loaded-font-scene-ts-webgpu.png
Labels: ✅ Ready To Merge, v8

#10337 Fix: ICanvasRenderingContext2D extending letterSpacing
  src/environment/canvas/ICanvasRenderingContext2D.ts
Labels: ✅ Ready To Merge, v8

#10340 Fix: Clean white implementation
  src/scene/container/utils/mixColors.ts
  tests/scene/utils/mixColors.tests.ts
Labels: ✅ Ready To Merge, v8

#10343 Fix: typo in the vertex shader of the bigTriangleProgram
  src/rendering/renderers/gl/GlBackBufferSystem.ts
Labels: ✅ Ready To Merge, v8

#10355 Fix: allow for optional destruction of textStyle
  src/scene/container/destroyTypes.ts
  src/scene/text/AbstractText.ts
  tests/renderering/text/Text.tests.ts
Labels: v8

#10357 Fix: NineSliceSprite not rendering correctly when used with a spritesheet texture
  src/rendering/renderers/shared/texture/TextureMatrix.ts
  src/scene/mesh/shared/BatchableMesh.ts
  src/scene/sprite-nine-slice/NineSliceGeometry.ts
  src/scene/sprite-nine-slice/NineSliceSprite.ts
Labels: ✅ Ready To Merge, v8
